// Übungsheft A2 — Lektion 07: Trennbare Verben
export default {
  lektion: 7,
  titel: 'Übungsheft — Trennbare Verben',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Wähle die richtige Form. ~~(Elige la forma correcta.)~~',
      items: [
        { typ: 'mc', frage: 'Der Film ___ um 20 Uhr an.', optionen: ['fängt', 'fangt', 'anfängt'], loesung: 0 },
        { typ: 'mc', frage: 'Ich ___ dich morgen an.', optionen: ['rufst', 'rufe', 'anrufe'], loesung: 1 },
        { typ: 'mc', frage: 'Wir haben im Supermarkt ___ .', optionen: ['geeinkauft', 'einkaufen', 'eingekauft'], loesung: 2 },
        {
          typ: 'luecke',
          text: 'Ich stehe um 6 Uhr {1}. Dann kaufe ich {2} und rufe meine Mutter {3}.',
          bank: ['auf', 'ein', 'an', 'mit'],
          loesungen: { 1: 'auf', 2: 'ein', 3: 'an' },
        },
        {
          typ: 'luecke',
          text: 'Gestern bin ich spät {1}. Heute muss ich früh {2}.',
          bank: ['aufgestanden', 'aufstehen', 'angerufen'],
          loesungen: { 1: 'aufgestanden', 2: 'aufstehen' },
        },
        { typ: 'satzbau', woerter: ['Ich', 'rufe', 'meine', 'Mutter', 'heute', 'an'], loesung: 'Ich rufe meine Mutter heute an.', alt: ['Ich rufe heute meine Mutter an.'] },
        { typ: 'satzbau', woerter: ['Kommst', 'du', 'am', 'Samstag', 'mit'], loesung: 'Kommst du am Samstag mit?' },
        {
          typ: 'zuordnen',
          links: ['aufstehen', 'anrufen', 'einkaufen', 'fernsehen', 'zurückkommen'],
          rechts: ['levantarse', 'llamar por teléfono', 'hacer la compra', 'ver la tele', 'volver'],
          loesung: {
            'aufstehen': 'levantarse',
            'anrufen': 'llamar por teléfono',
            'einkaufen': 'hacer la compra',
            'fernsehen': 'ver la tele',
            'zurückkommen': 'volver',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Ich muss früh stehen auf.', 'Ich muss früh aufstehen.'],
          loesung: 1,
          warum: 'Con un modal, el infinitivo va **entero** al final: Ich muss früh **aufstehen**. ~~(El prefijo no se separa cuando hay verbo modal.)~~',
        },
        {
          typ: 'korrektur',
          optionen: ['Der Kurs fängt um 9 Uhr an.', 'Der Kurs fängt um 9 Uhr.'],
          loesung: 0,
          warum: 'El prefijo **an** cierra la frase: Der Kurs fängt um 9 Uhr **an**. ~~(Sin el *an* del final, la frase queda incompleta.)~~',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die Notiz. Richtig oder falsch? ~~(Lee la nota. ¿Verdadero o falso?)~~',
      textTitel: 'Notiz von Papa',
      text: 'Hallo Kinder! Ich komme heute erst um 19 Uhr zurück — im Büro fängt um 17 Uhr noch ein Meeting an. Ich mache dann das Abendessen. Bitte kauft im Supermarkt ein: Brot, Milch und Obst. Die Liste hängt am Kühlschrank. Lena, ruf bitte Oma an — sie hat heute Geburtstag! Ihr dürft heute Abend fernsehen, aber nur bis 21 Uhr. Bis später! Papa',
      items: [
        { typ: 'rf', aussage: 'Papa kommt um 17 Uhr zurück.', loesung: false },
        { typ: 'rf', aussage: 'Die Kinder sollen im Supermarkt einkaufen.', loesung: true },
        { typ: 'rf', aussage: 'Oma hat heute Geburtstag.', loesung: true },
        { typ: 'mc', frage: 'Wie lange dürfen die Kinder fernsehen?', optionen: ['bis 21 Uhr', 'bis 19 Uhr', 'bis 17 Uhr'], loesung: 0 },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Hör die Nachricht auf dem Anrufbeantworter. Was ist richtig? ~~(Escucha el mensaje en el contestador. ¿Qué es correcto?)~~',
      audio: {
        transcript: 'Hallo Jonas, hier ist Carla. Morgen machen wir den Ausflug nach Potsdam. Kommst du mit? Der Zug fährt nicht um neun Uhr ab, sondern schon um halb neun. Ich stehe um sieben Uhr auf. Heute Nachmittag kaufe ich noch Brot, Käse und Obst ein. Bring bitte nur Wasser mit. Am Abend kommen wir um acht Uhr zurück. Ich bin jetzt noch im Büro. Ruf mich bitte nach sechs Uhr an. Tschüss!',
      },
      items: [
        { typ: 'mc', frage: 'Wann fährt der Zug ab?', optionen: ['um neun Uhr', 'um halb neun', 'um sieben Uhr'], loesung: 1 },
        { typ: 'rf', aussage: 'Jonas soll Brot und Käse mitbringen.', loesung: false },
        { typ: 'rf', aussage: 'Jonas soll Carla nach sechs Uhr anrufen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib 25-35 Wörter. ~~(Escribe 25-35 palabras.)~~',
      aufgabe: 'Dein Tag: Schreib einen kurzen Text mit trennbaren Verben.',
      punkte: [
        'Wann stehst du auf?',
        'Wann kaufst du ein?',
        'Was machst du am Abend?',
      ],
      minWoerter: 25,
      beispielLoesung: 'Ich stehe jeden Tag um halb sieben auf. Nach der Arbeit kaufe ich im Supermarkt ein. Am Abend rufe ich oft meine Schwester an und wir sehen zusammen fern. Um elf Uhr bin ich müde.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Sprich eine Nachricht für einen Freund. Sprich 45 Sekunden. ~~(Graba un mensaje para un amigo. Habla 45 segundos.)~~',
      aufgabe: 'Du gehst am Samstag ins Kino. Lade deinen Freund Tom ein. Benutze trennbare Verben.',
      punkte: [
        'Wann fängt der Film an?',
        'Frag Tom: Kommst du mit?',
        'Wann kommt ihr zurück?',
        'Wann rufst du noch einmal an?',
      ],
      redemittel: ['Hallo Tom, hier ist …', 'Der Film fängt um … an.', 'Kommst du mit?', 'Ich rufe dich … noch einmal an.'],
      maxSekunden: 45,
      beispielLoesung: 'Hallo Tom, hier ist Pablo. Am Samstag gehe ich ins Kino. Kommst du mit? Der Film fängt um acht Uhr an. Ich kaufe heute schon die Karten. Danach essen wir noch eine Pizza. Wir kommen um elf Uhr zurück. Ich rufe dich morgen Abend noch einmal an. Tschüss!',
    },
  ],
}
