// Übungsheft B2 — Lektion 38: Wohnen & Zusammenleben
export default {
  lektion: 38,
  titel: 'Übungsheft — Wohnen & Zusammenleben',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Wohnungssuche, Mietvertrag und Hausordnung: Wähle die passende Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Die {1} beträgt 650 Euro im Monat, die {2} für Heizung und Wasser kommen noch dazu.',
          bank: ['Kaltmiete', 'Nebenkosten', 'Kaution', 'Anzeige'],
          loesungen: { 1: 'Kaltmiete', 2: 'Nebenkosten' },
        },
        {
          typ: 'luecke',
          text: 'Frau Albers {1} die kleine Wohnung unter dem Dach an Studierende. Seit März {2} Leon dort ein Zimmer.',
          bank: ['vermietet', 'mietet', 'unterschreibt', 'zieht'],
          loesungen: { 1: 'vermietet', 2: 'mietet' },
        },
        {
          typ: 'luecke',
          text: 'Ich habe {1} eine Anzeige geantwortet und gleich einen Termin {2} Besichtigung vereinbart.',
          bank: ['auf', 'zur', 'für', 'an'],
          loesungen: { 1: 'auf', 2: 'zur' },
        },
        {
          typ: 'mc',
          frage: 'Wer in diesem Haus wohnt, muss sich an die Hausordnung ___.',
          optionen: ['achten', 'halten', 'richten'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Zwischen 22 und 6 Uhr müssen alle Mieter die Ruhezeiten ___.',
          optionen: ['behalten', 'festhalten', 'einhalten'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Laut Hausordnung ___ Fahrräder ausschließlich im Hof abzustellen.',
          optionen: ['sind', 'haben', 'werden'],
          loesung: 0,
        },
        {
          typ: 'zuordnen',
          links: ['den Mietvertrag', 'die Kaution', 'in eine WG', 'auf eine Anzeige', 'sich gut mit den Nachbarn'],
          rechts: ['unterschreiben', 'zurückbekommen', 'ziehen', 'antworten', 'verstehen'],
          loesung: {
            'den Mietvertrag': 'unterschreiben',
            'die Kaution': 'zurückbekommen',
            'in eine WG': 'ziehen',
            'auf eine Anzeige': 'antworten',
            'sich gut mit den Nachbarn': 'verstehen',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Wir haben die Wohnung von einem älteren Ehepaar vermietet.', 'Wir haben die Wohnung von einem älteren Ehepaar gemietet.'],
          loesung: 1,
          warum: 'Quien paga el alquiler **mietet**; solo el propietario **vermietet** (da en alquiler).',
        },
        {
          typ: 'korrektur',
          optionen: ['Letztes Jahr bin ich nach Köln umgezogen.', 'Letztes Jahr habe ich mich nach Köln umgezogen.'],
          loesung: 0,
          warum: '«Mudarse» no es reflexivo: **umziehen** con *sein*. *Sich umziehen* significa «cambiarse de ropa».',
        },
        {
          typ: 'satzbau',
          woerter: ['du', 'Mietvertrag', 'Bevor', 'den', 'unterschreibst', 'lies', 'ihn', 'genau'],
          loesung: 'Bevor du den Mietvertrag unterschreibst, lies ihn genau.',
          alt: ['Bevor du ihn unterschreibst, lies den Mietvertrag genau.', 'Lies den Mietvertrag genau, bevor du ihn unterschreibst.', 'Lies ihn genau, bevor du den Mietvertrag unterschreibst.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Auszug aus einem Zeitungsartikel und löse die Aufgaben.',
      textTitel: 'Zimmer gegen Hilfe: Wenn Jung und Alt zusammenziehen',
      text: 'In vielen Universitätsstädten ist die Wohnungssuche für Studierende ein Albtraum: Auf ein WG-Zimmer kommen oft Dutzende Bewerber, und die Kaltmiete für ein kleines Apartment ist schnell höher, als der Nebenjob einbringt. Gleichzeitig leben viele ältere Menschen allein in großen Wohnungen. Ein Modell, das inzwischen in mehreren Städten angeboten wird, bringt beide Seiten zusammen: Studierende wohnen bei Senioren und zahlen statt Miete nur die Nebenkosten. Dafür helfen sie im Alltag — sie kaufen ein, tragen Getränkekisten oder erklären das Smartphone. Als Faustregel gilt: eine Stunde Hilfe pro Monat für jeden Quadratmeter Wohnfläche. Pflege gehört ausdrücklich nicht dazu. Die 81-jährige Gerda Maurer aus Freiburg ist begeistert: „Seit nachts jemand im Haus ist, fühle ich mich viel sicherer.“ Ihr Mitbewohner Kwame, der Informatik studiert, schätzt vor allem die Ruhe. Ganz ohne Konflikte geht es aber nicht: Wer unterschiedliche Vorstellungen von Ordnung oder Ruhezeiten hat, sollte das vor dem Einzug klären. Deshalb organisieren die Vermittler zuerst ein Kennenlerngespräch.',
      items: [
        {
          typ: 'mc',
          frage: 'Was zahlen die Studierenden in diesem Modell?',
          optionen: ['Die halbe Kaltmiete.', 'Nur die Nebenkosten.', 'Einen festen Betrag pro Quadratmeter.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Zu den Aufgaben der Studierenden gehört auch die Pflege.', loesung: false },
        { typ: 'rf', aussage: 'Vor dem Einzug lernen sich beide Seiten in einem Gespräch kennen.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was gefällt Gerda Maurer an dem Modell besonders?',
          optionen: ['Sie fühlt sich sicherer.', 'Sie spart viel Geld.', 'Sie bekommt Hilfe bei der Pflege.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst eine Nachricht auf dem Anrufbeantworter. Entscheide bei jeder Aufgabe, welche Lösung dem Gehörten entspricht.',
      audio: {
        transcript: 'Guten Tag, Herr Demir, hier spricht Monika Lindner. Sie haben auf meine Anzeige für die Dreizimmerwohnung in der Gartenstraße geantwortet, vielen Dank für Ihre Nachricht. Ich möchte Ihnen gern einen Termin zur Besichtigung anbieten. Am Freitag bin ich leider verhindert, deshalb schlage ich Samstag um halb elf vor. Bitte klingeln Sie bei der Hausverwaltung, ich warte dann im Erdgeschoss auf Sie. Noch kurz zu den Kosten, weil in der Anzeige ein Fehler war. Die Kaltmiete beträgt nicht achthundertfünfzig, sondern achthundertfünfzehn Euro. Dazu kommen ungefähr zweihundert Euro Nebenkosten für Heizung und Wasser. Die Kaution beträgt zwei Kaltmieten und kann in drei Raten bezahlt werden. Die Wohnung wird zum ersten Mai frei, die jetzigen Mieter ziehen Mitte April aus. Bringen Sie zur Besichtigung bitte Ihre letzten drei Gehaltsabrechnungen mit. Den Mietvertrag würden wir erst später unterschreiben. Falls Ihnen der Termin nicht passt, rufen Sie mich bitte bis Donnerstagabend zurück. Sie erreichen mich am besten nach achtzehn Uhr. Auf Wiederhören!',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Welchen Termin schlägt Frau Lindner für die Besichtigung vor?',
          optionen: ['Freitag um 10:30 Uhr', 'Samstag um 11:30 Uhr', 'Samstag um 10:30 Uhr'],
          loesung: 2,
        },
        { typ: 'mc', frage: 'Wie hoch ist die Kaltmiete?', optionen: ['815 Euro', '850 Euro', '1.015 Euro'], loesung: 0 },
        { typ: 'rf', aussage: 'Herr Demir muss die Kaution auf einmal bezahlen.', loesung: false },
        { typ: 'rf', aussage: 'Zur Besichtigung soll Herr Demir Gehaltsabrechnungen mitbringen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib eine formelle E-Mail mit mindestens 60 Wörtern und geh auf alle drei Punkte ein.',
      aufgabe: 'Du hast eine Anzeige für eine Zweizimmerwohnung gelesen: 720 Euro Kaltmiete, Nebenkosten und Kaution „nach Vereinbarung“. Schreib an den Vermieter, Herrn Brandt.',
      punkte: [
        'Stell dich kurz vor und erklär, warum du umziehen möchtest.',
        'Frag nach der Höhe der Nebenkosten und der Kaution.',
        'Schlag einen Termin zur Besichtigung vor.',
      ],
      minWoerter: 60,
      beispielLoesung: 'Sehr geehrter Herr Brandt, mit großem Interesse habe ich Ihre Anzeige für die Zweizimmerwohnung gelesen. Mein Name ist Lucía Ortega, ich bin 29 Jahre alt und arbeite als Physiotherapeutin. Da ich ab Juni eine neue Stelle in Ihrer Stadt antrete, suche ich eine ruhige Wohnung in der Nähe. Bevor ich mich bewerbe, hätte ich zwei Fragen: Wie hoch sind die Nebenkosten ungefähr, und wie viele Kaltmieten beträgt die Kaution? Außerdem würde ich die Wohnung gern besichtigen. Wäre ein Termin am kommenden Samstagvormittag möglich? Über eine Antwort würde ich mich sehr freuen. Mit freundlichen Grüßen, Lucía Ortega',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Sprich eine Sprachnachricht, in der du zwei Möglichkeiten abwägst. Sprich etwa 100 Sekunden frei und in ganzen Sätzen.',
      aufgabe: 'Dein Freund Pablo hat eine Stelle in München gefunden und bittet dich um Rat: Soll er in ein WG-Zimmer in der Innenstadt ziehen oder in eine eigene, günstigere Wohnung in einem Dorf außerhalb? Sprich ihm eine Sprachnachricht (etwa 100 Sekunden), in der du beide Möglichkeiten abwägst und ihm eine Empfehlung gibst.',
      punkte: [
        'Nenne Vor- und Nachteile des WG-Zimmers in der Stadt.',
        'Nenne Vor- und Nachteile der Wohnung auf dem Land.',
        'Gib eine klare Empfehlung und begründe sie.',
      ],
      redemittel: ['Für … spricht, dass …', 'Dagegen spricht allerdings, dass …', 'Es kommt darauf an, …', 'An deiner Stelle würde ich …'],
      maxSekunden: 100,
      beispielLoesung: 'Hallo Pablo, danke für deine Nachricht und erst mal herzlichen Glückwunsch zur neuen Stelle! Du wolltest wissen, was ich an deiner Stelle machen würde. Also, für das WG-Zimmer in der Stadt spricht, dass du alles in der Nähe hast: die Arbeit, Cafés, Kultur. Du brauchst kein Auto, und über die Mitbewohner lernst du schnell Leute kennen. Dagegen spricht allerdings, dass du Küche und Bad teilen musst und trotzdem ziemlich viel Miete zahlst. Die Wohnung auf dem Land ist günstiger, du hättest mehr Platz und deine Ruhe. Dafür müsstest du jeden Tag pendeln, und abends fährt wahrscheinlich kaum noch ein Bus. Ich glaube, es kommt darauf an, was dir im Moment wichtiger ist. Du kennst in München ja noch niemanden. Deshalb würde ich an deiner Stelle zuerst in die WG ziehen, zumindest für das erste Jahr. Wenn du die Stadt besser kennst, kannst du immer noch umziehen. Lies aber den Mietvertrag genau durch, bevor du ihn unterschreibst! Melde dich, wenn du dich entschieden hast.',
    },
  ],
}
