// Übungsheft B2 — Lektion 39: Konsum & Geld
export default {
  lektion: 39,
  titel: 'Übungsheft — Konsum & Geld',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Einkaufen, Reklamieren und Geld: Wähle die passende Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Ich habe die Bestellung schon am Montag {1}, aber das Paket ist noch nicht da — ich warte immer noch auf die {2}.',
          bank: ['aufgegeben', 'Lieferung', 'eingereicht', 'Rücksendung'],
          loesungen: { 1: 'aufgegeben', 2: 'Lieferung' },
        },
        {
          typ: 'luecke',
          text: 'Letzten Monat habe ich viel zu viel Geld für Kleidung {1}. Deshalb habe ich dieses Wochenende ganz ohne Kosten im Park {2}.',
          bank: ['ausgegeben', 'verbracht', 'gespart', 'verdient'],
          loesungen: { 1: 'ausgegeben', 2: 'verbracht' },
        },
        {
          typ: 'luecke',
          text: 'Frau Novak hat sich {1} die kaputte Waschmaschine beschwert und {2} Kundenservice eine Reklamation eingereicht.',
          bank: ['über', 'von', 'beim', 'am'],
          loesungen: { 1: 'über', 2: 'beim' },
        },
        {
          typ: 'mc',
          frage: 'Im Schlussverkauf bekommt man auf fast alles zwanzig Prozent ___.',
          optionen: ['Rabatt', 'Rechnung', 'Rücksendung'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Je mehr Werbung man sieht, ___ mehr Geld gibt man aus.',
          optionen: ['als', 'desto', 'wie'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Der Betrag ___ Ihnen innerhalb von 14 Tagen erstattet.',
          optionen: ['hat', 'ist', 'wird'],
          loesung: 2,
        },
        {
          typ: 'zuordnen',
          links: ['eine Bestellung', 'eine Reklamation', 'einen Pullover', 'den Kassenbon', 'für den Urlaub'],
          rechts: ['aufgeben', 'einreichen', 'umtauschen', 'aufbewahren', 'sparen'],
          loesung: {
            'eine Bestellung': 'aufgeben',
            'eine Reklamation': 'einreichen',
            'einen Pullover': 'umtauschen',
            'den Kassenbon': 'aufbewahren',
            'für den Urlaub': 'sparen',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Ich habe mich über die späte Lieferung beschwert.', 'Ich habe mich von der späten Lieferung beschwert.'],
          loesung: 0,
          warum: '**sich beschweren über** + Akkusativ; *von* es un calco de «quejarse de».',
        },
        {
          typ: 'korrektur',
          optionen: ['Am Samstag habe ich drei Stunden im Einkaufszentrum ausgegeben.', 'Am Samstag habe ich drei Stunden im Einkaufszentrum verbracht.'],
          loesung: 1,
          warum: '«Gastar/pasar tiempo» = **Zeit verbringen**; *ausgeben* solo se usa con dinero.',
        },
        {
          typ: 'satzbau',
          woerter: ['dass', 'feststellen', 'Ware', 'ist', 'Leider', 'ich', 'beschädigt', 'musste', 'die'],
          loesung: 'Leider musste ich feststellen, dass die Ware beschädigt ist.',
          alt: ['Ich musste leider feststellen, dass die Ware beschädigt ist.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Kommentar und löse die Aufgaben.',
      textTitel: 'Kommentar: Gratis zurückschicken? Das hat seinen Preis',
      text: 'Kostenlose Rücksendungen gelten vielen als selbstverständlich. Man bestellt die Jeans in drei Größen, behält eine und schickt den Rest zurück — bequemer geht es kaum. Doch gratis ist daran nichts. Jede Rücksendung muss transportiert, geprüft und neu verpackt werden, und einen Teil der Ware können die Händler gar nicht mehr verkaufen. Diese Kosten stecken längst in den Preisen, die alle Kunden bezahlen — auch diejenigen, die nie etwas zurückschicken. Hinzu kommen lange Transportwege und Verpackungsmüll. Ich halte es deshalb für richtig, dass immer mehr Händler eine kleine Gebühr verlangen. Ein Verbot kostenloser Rücksendungen fordere ich aber nicht: Wer ein defektes Produkt reklamiert, darf dafür selbstverständlich nichts zahlen. Es geht um die Gewohnheit, das eigene Wohnzimmer als Umkleidekabine zu nutzen. Zwei oder drei Euro pro Paket würden viele dazu bringen, vor dem Kauf genauer zu überlegen. Und vielleicht probiert der eine oder andere die Jeans dann wieder im Geschäft an — gleich um die Ecke. — Henrik Sommer',
      items: [
        {
          typ: 'mc',
          frage: 'Welche Position vertritt der Autor?',
          optionen: ['Rücksendungen sollten grundsätzlich verboten werden.', 'Eine kleine Gebühr für Rücksendungen ist sinnvoll.', 'Die Händler sollten ihre Preise senken.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Laut dem Kommentar bezahlen auch Kunden, die nichts zurückschicken, die Kosten der Rücksendungen mit.', loesung: true },
        { typ: 'rf', aussage: 'Der Autor meint, dass man auch für die Reklamation defekter Ware zahlen sollte.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was erhofft sich der Autor von der Gebühr?',
          optionen: ['Dass die Kunden vor dem Kauf genauer überlegen.', 'Dass die Händler mehr Gewinn machen.', 'Dass die Kunden häufiger online bestellen.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst ein Gespräch in einem Elektrogeschäft. Entscheide bei jeder Aufgabe, welche Lösung dem Gehörten entspricht.',
      audio: {
        transcript: 'Verkäuferin: Guten Tag, was kann ich für Sie tun?\nKunde: Guten Tag. Ich habe letzte Woche bei Ihnen diese Kaffeemaschine gekauft, und sie funktioniert nicht richtig. Das Wasser wird nicht mehr heiß.\nVerkäuferin: Das tut mir leid. Haben Sie den Kassenbon aufbewahrt?\nKunde: Den finde ich leider nicht mehr. Ich habe aber mit Karte bezahlt, hier ist die Abbuchung auf meinem Kontoauszug.\nVerkäuferin: Das reicht als Nachweis. Dann nehme ich Ihre Reklamation auf. Möchten Sie das Gerät umtauschen, oder soll ich Ihnen den Betrag erstatten?\nKunde: Eigentlich wollte ich mein Geld zurück. Was kostet das Modell denn im Moment?\nVerkäuferin: Sie haben neunundachtzig Euro bezahlt. Seit Montag gibt es zwanzig Prozent Rabatt, also kostet es jetzt nur noch rund einundsiebzig Euro.\nKunde: Aber ich bekomme schon die neunundachtzig Euro zurück, oder?\nVerkäuferin: Selbstverständlich, den vollen Betrag. Das Geld ist in etwa fünf Werktagen auf Ihrem Konto.\nKunde: Gut. Wissen Sie was? Dann nehme ich dieselbe Maschine gleich noch einmal mit, zum günstigeren Preis.\nVerkäuferin: Gern. Diesmal heben Sie den Kassenbon aber bitte gut auf.',
      },
      items: [
        { typ: 'rf', aussage: 'Der Kunde kann der Verkäuferin den Kassenbon zeigen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was ist das Problem mit der Kaffeemaschine?',
          optionen: ['Sie verliert Wasser.', 'Sie erhitzt das Wasser nicht mehr.', 'Sie lässt sich nicht mehr einschalten.'],
          loesung: 1,
        },
        { typ: 'mc', frage: 'Welchen Betrag bekommt der Kunde erstattet?', optionen: ['71 Euro', '79 Euro', '89 Euro'], loesung: 2 },
        { typ: 'rf', aussage: 'Am Ende kauft der Kunde das gleiche Modell noch einmal.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib eine Stellungnahme mit mindestens 60 Wörtern und geh auf alle drei Punkte ein.',
      aufgabe: 'Auf der Website eines Verbrauchermagazins wird diskutiert: „Sollte Werbung, die sich an Kinder richtet, verboten werden?“ Schreib deine Stellungnahme.',
      punkte: [
        'Äußere deine Meinung und begründe sie.',
        'Nenne ein Argument für und eines gegen ein Verbot.',
        'Beschreib, wie die Situation in deinem Heimatland ist.',
      ],
      minWoerter: 60,
      beispielLoesung: 'Meiner Meinung nach sollte Werbung für Kinder stark eingeschränkt werden, denn Kinder lassen sich besonders leicht von Werbung beeinflussen. Sie verstehen oft nicht, dass ein Clip nur verkaufen will, und bitten ihre Eltern danach ständig um neues Spielzeug oder Süßigkeiten. Andererseits gehört Werbung zum Alltag, und ein komplettes Verbot wäre schwer zu kontrollieren, vor allem im Internet. Besser wäre es, wenn Kinder schon in der Schule lernen, wie Werbung funktioniert. In Chile, wo ich aufgewachsen bin, dürfen ungesunde Lebensmittel nicht mehr mit Comicfiguren beworben werden. Ich finde, das ist ein guter Kompromiss.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Sprich eine formelle Nachricht auf einen Anrufbeantworter. Sprich etwa 90 Sekunden frei und in ganzen Sätzen.',
      aufgabe: 'Du hast vor zwei Wochen bei einem Online-Händler einen Staubsauger bestellt. Geliefert wurde ein falsches Modell, und auf deine E-Mail hat niemand reagiert. Du rufst beim Kundenservice an, erreichst aber nur den Anrufbeantworter. Sprich deine Reklamation als formelle Nachricht im Sie-Register auf das Band (etwa 90 Sekunden).',
      punkte: [
        'Nenne deinen Namen und beschreib, was du bestellt und was du bekommen hast.',
        'Erkläre, was du bisher unternommen hast und worüber du dich beschwerst.',
        'Sag, welche Lösung du erwartest und bis wann du eine Rückmeldung möchtest.',
      ],
      redemittel: ['Ich rufe an, weil …', 'Leider musste ich feststellen, dass …', 'Ich möchte mich darüber beschweren, dass …', 'Ich bitte Sie, mir … zu schicken / zu erstatten.'],
      maxSekunden: 90,
      beispielLoesung: 'Guten Tag, mein Name ist Elena Ruiz. Ich rufe an, weil es ein Problem mit meiner Bestellung gibt. Vor zwei Wochen habe ich bei Ihnen einen Staubsauger bestellt, und zwar das Modell mit Akku. Die Lieferung kam zwar pünktlich, aber leider musste ich feststellen, dass im Paket ein ganz anderes Gerät war: ein älteres Modell mit Kabel. Auf der Rechnung steht trotzdem der Preis für das teurere Gerät. Ich habe Ihnen deshalb schon vor zehn Tagen eine E-Mail geschrieben und Fotos mitgeschickt. Ich möchte mich darüber beschweren, dass ich bis heute keine Antwort bekommen habe. Ich bitte Sie, mir entweder das richtige Modell zu schicken oder mir den vollen Betrag zu erstatten. Die Kosten für die Rücksendung des falschen Geräts sollten selbstverständlich Sie übernehmen. Bitte rufen Sie mich bis Ende dieser Woche zurück oder antworten Sie auf meine E-Mail. Vielen Dank und auf Wiederhören.',
    },
  ],
}
