// Übungsheft B2 — Lektion 37: Medien & Digitalisierung
export default {
  lektion: 37,
  titel: 'Übungsheft — Medien & Digitalisierung',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Kollokationen, Präpositionen und Konnektoren rund um Medien und Digitalisierung: Wähle die passende Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Bevor du die Meldung weiterschickst, solltest du die {1} prüfen. Viele Apps sammeln außerdem die Daten ihrer {2}.',
          bank: ['Quelle', 'Nutzer', 'Passwort', 'Bildschirmzeit'],
          loesungen: { 1: 'Quelle', 2: 'Nutzer' },
        },
        {
          typ: 'luecke',
          text: 'Tagsüber recherchiere ich viel {1} Internet, aber abends lege ich das Handy weg, um bewusst {2}.',
          bank: ['im', 'auf', 'abzuschalten', 'abschalten'],
          loesungen: { 1: 'im', 2: 'abzuschalten' },
        },
        {
          typ: 'luecke',
          text: 'Für neun Euro im Monat haben wir einen neuen Streamingdienst {1}. Gestern hat Jonas ein Foto von seinem Urlaub {2}, und schon fünfzig Leute haben es kommentiert.',
          bank: ['abonniert', 'gepostet', 'heruntergeladen', 'begrenzt'],
          loesungen: { 1: 'abonniert', 2: 'gepostet' },
        },
        {
          typ: 'mc',
          frage: 'Meine Schwester ___ die Bildschirmzeit ihrer Kinder auf eine Stunde pro Tag.',
          optionen: ['schützt', 'begrenzt', 'verbietet'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Für jedes Konto solltest du ein sicheres Passwort ___.',
          optionen: ['wählen', 'treffen', 'stellen'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Viele Apps sammeln persönliche Daten, ___ die Nutzer es merken.',
          optionen: ['damit', 'sodass', 'ohne dass'],
          loesung: 2,
        },
        {
          typ: 'zuordnen',
          links: ['eine App', 'die Quelle einer Information', 'einen Streamingdienst', 'die Bildschirmzeit', 'auf den Datenschutz'],
          rechts: ['herunterladen', 'prüfen', 'abonnieren', 'begrenzen', 'achten'],
          loesung: {
            'eine App': 'herunterladen',
            'die Quelle einer Information': 'prüfen',
            'einen Streamingdienst': 'abonnieren',
            'die Bildschirmzeit': 'begrenzen',
            'auf den Datenschutz': 'achten',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Ich habe den Artikel auf Internet gelesen.', 'Ich habe den Artikel im Internet gelesen.'],
          loesung: 1,
          warum: '«En internet» = **im Internet**, siempre con artículo (*das Internet*); *auf Internet* es un calco.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich verbringe jeden Abend zwei Stunden am Handy.', 'Ich passiere jeden Abend zwei Stunden am Handy.'],
          loesung: 0,
          warum: '«Pasar tiempo» = **Zeit verbringen**; *passieren* solo significa «ocurrir».',
        },
        {
          typ: 'satzbau',
          woerter: ['sammeln', 'es', 'Daten', 'Ohne', 'man', 'Apps', 'merkt', 'dass'],
          loesung: 'Ohne dass man es merkt, sammeln Apps Daten.',
          alt: ['Apps sammeln Daten, ohne dass man es merkt.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Forumsbeitrag und löse die Aufgaben.',
      textTitel: 'Forum „Digital leben“: Eine Woche ohne Smartphone',
      text: 'Letzten Monat habe ich ein Experiment gemacht: eine Woche ohne Smartphone. Auslöser war ein Blick auf meine Bildschirmzeit — im Durchschnitt fast fünf Stunden pro Tag, viel zu viel! Die ersten beiden Tage waren hart. Ich wollte ständig aufs Handy schauen, und ohne meine Apps musste ich den Fahrplan an der Haltestelle lesen. Ab dem dritten Tag wurde es besser: Abends habe ich zwei Bücher gelesen, und bei der Arbeit konnte ich mich deutlich besser konzentrieren. Nachrichten habe ich nur noch einmal am Tag am Laptop gelesen. Ganz ohne Nachteile war die Woche allerdings nicht. Meine Freunde organisieren fast alles über eine Chatgruppe, und so habe ich eine Geburtstagsfeier verpasst. Mein Fazit: Ein kompletter Verzicht ist für mich keine Lösung, aber ich habe einiges geändert. Die sozialen Netzwerke habe ich vom Handy gelöscht, und nach 21 Uhr bleibt das Gerät im Flur. Hat jemand von euch ähnliche Erfahrungen gemacht? — Tobias, 34',
      items: [
        {
          typ: 'mc',
          frage: 'Warum hat Tobias das Experiment begonnen?',
          optionen: ['Sein Arbeitgeber hat es verlangt.', 'Seine Bildschirmzeit war ihm zu hoch.', 'Er hatte sein Handy verloren.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'In den ersten Tagen fiel Tobias der Verzicht leicht.', loesung: false },
        { typ: 'rf', aussage: 'Während der Woche hat Tobias eine Feier verpasst.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was hat Tobias nach dem Experiment dauerhaft geändert?',
          optionen: ['Er benutzt gar kein Smartphone mehr.', 'Er organisiert keine Treffen mehr über Chatgruppen.', 'Er hat die sozialen Netzwerke vom Handy gelöscht.'],
          loesung: 2,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst einen Radiobeitrag über ein Angebot in einer Stadtbibliothek. Entscheide bei jeder Aufgabe, welche Lösung dem Gehörten entspricht.',
      audio: {
        transcript: 'Und nun zu unserem Thema der Woche, dem digitalen Alltag. In der Stadtbibliothek von Lüneburg gibt es seit dem Frühjahr eine Smartphone-Sprechstunde. Dort erklären Schülerinnen und Schüler eines Gymnasiums älteren Menschen, wie man eine App herunterlädt, ein sicheres Passwort wählt oder die Quelle einer Nachricht prüft. Ursprünglich war das Angebot nur für Menschen über siebzig gedacht, inzwischen kommen aber auch deutlich Jüngere. Die Sprechstunde findet nicht mehr dienstags statt, sondern jeden Donnerstag von sechzehn bis achtzehn Uhr. Eine Anmeldung ist nicht nötig, und die Teilnahme kostet nichts. Am häufigsten fragen die Besucher übrigens nicht nach sozialen Netzwerken, sondern nach dem Datenschutz. Viele möchten wissen, welche Daten ihre Apps sammeln und wie man das in den Einstellungen begrenzt. Auch die Jugendlichen profitieren. Sie bekommen dafür zwar kein Geld, aber eine Bescheinigung für ihre Bewerbungsunterlagen. Wegen der großen Nachfrage soll es ab Herbst eine zweite Sprechstunde in einem anderen Stadtteil geben. Wer mithelfen möchte, kann sich direkt an der Information der Bibliothek melden.',
      },
      items: [
        { typ: 'rf', aussage: 'Die Sprechstunde wird heute ausschließlich von Menschen über siebzig besucht.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wann findet die Sprechstunde statt?',
          optionen: ['dienstags von 16 bis 18 Uhr', 'donnerstags von 16 bis 18 Uhr', 'donnerstags von 18 bis 20 Uhr'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Wonach fragen die Besucher am häufigsten?',
          optionen: ['nach dem Datenschutz', 'nach sozialen Netzwerken', 'nach Streamingdiensten'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Die Schülerinnen und Schüler erhalten für ihre Hilfe eine Bescheinigung.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib eine Beschwerde-E-Mail mit mindestens 60 Wörtern und geh auf alle drei Punkte ein.',
      aufgabe: 'Du hast vor drei Monaten einen Streamingdienst abonniert. Seit zwei Wochen funktioniert die App auf deinem Fernseher nicht mehr, trotzdem wird jeden Monat Geld abgebucht. Außerdem bekommst du plötzlich Werbung von anderen Firmen. Schreib an den Kundenservice.',
      punkte: [
        'Beschreib das Problem mit der App genau.',
        'Frag, ob deine Daten an andere Firmen weitergegeben wurden.',
        'Fordere eine Lösung: Rückerstattung für die zwei Wochen oder Kündigung.',
      ],
      minWoerter: 60,
      beispielLoesung: 'Sehr geehrte Damen und Herren, vor drei Monaten habe ich Ihren Streamingdienst abonniert. Seit zwei Wochen lässt sich die App auf meinem Fernseher jedoch nicht mehr öffnen, obwohl ich sie bereits zweimal neu heruntergeladen habe. Trotzdem wurde der volle Monatsbeitrag abgebucht. Außerdem erhalte ich seit Kurzem Werbung von anderen Firmen. Ich möchte daher wissen, ob Sie meine Daten weitergegeben haben — der Datenschutz ist mir sehr wichtig. Ich bitte Sie, mir den Betrag für die zwei Wochen zu erstatten. Sollte das Problem nicht bis Ende des Monats gelöst sein, werde ich mein Abonnement kündigen. Mit freundlichen Grüßen, Amira Haddad',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Nimm Stellung zu einer These. Sprich etwa 100 Sekunden frei und in ganzen Sätzen.',
      aufgabe: 'In einer Diskussionsrunde zum Thema Medien geht es um folgende These: „Soziale Netzwerke schaden uns mehr, als sie nützen.“ Formuliere deine mündliche Stellungnahme zu dieser These (etwa 100 Sekunden, frei gesprochen).',
      punkte: [
        'Sag klar, ob du der These zustimmst oder nicht.',
        'Begründe deine Position mit zwei Argumenten und einem Beispiel aus deinem Alltag.',
        'Geh auf ein Gegenargument ein und formuliere ein Fazit.',
      ],
      redemittel: ['Meiner Meinung nach …', 'Einerseits …, andererseits …', 'Aus meiner Erfahrung kann ich sagen, dass …', 'Mein Fazit: …'],
      maxSekunden: 100,
      beispielLoesung: 'Ich stimme der These nur teilweise zu. Meiner Meinung nach schaden soziale Netzwerke nicht automatisch, es kommt auf den Umgang damit an. Einerseits sehe ich natürlich die Probleme: Viele Leute schauen ständig aufs Handy, vergleichen sich mit anderen und geben viel zu viele persönliche Daten preis. Außerdem verbreiten sich falsche Nachrichten dort sehr schnell, weil kaum jemand die Quelle prüft. Andererseits bleibe ich über soziale Netzwerke mit meiner Familie in Kolumbien in Kontakt, und das wäre ohne sie viel schwieriger. Aus meiner Erfahrung kann ich sagen, dass feste Regeln helfen. Ich habe zum Beispiel meine Bildschirmzeit begrenzt und poste nur noch selten etwas. Seitdem kann ich mich besser konzentrieren. Manche sagen, man sollte die Netzwerke einfach löschen. Das halte ich aber für unrealistisch, denn sie gehören heute zum Alltag. Mein Fazit: Soziale Netzwerke sind weder gut noch schlecht. Entscheidend ist, dass wir lernen, bewusst damit umzugehen und abends auch mal abzuschalten.',
    },
  ],
}
