// Übungsheft B2 — Lektion 08: Konjunktiv II der Vergangenheit
export default {
  lektion: 8,
  titel: 'Übungsheft — Konjunktiv II der Vergangenheit',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Es ist zu spät, etwas zu ändern: Ergänze die irreale Vergangenheit. Achte auf das Hilfsverb (hätte oder wäre) und auf den Doppelinfinitiv.',
      items: [
        {
          typ: 'luecke',
          text: 'Wenn Lukas den Wecker gehört {1}, {2} er pünktlich ins Büro gekommen.',
          bank: ['hätte', 'wäre', 'würde', 'hat'],
          loesungen: { 1: 'hätte', 2: 'wäre' },
        },
        {
          typ: 'luecke',
          text: 'Wenn ihr rechtzeitig {1}, hättet ihr noch Karten für das Konzert bekommen. Ihr hättet sie gleich im Januar online {2}!',
          bank: ['gebucht hättet', 'gebucht wärt', 'kaufen sollen', 'gekauft sollen'],
          loesungen: { 1: 'gebucht hättet', 2: 'kaufen sollen' },
        },
        {
          typ: 'luecke',
          text: 'Auf der glatten Straße {1} Mira beinahe gestürzt, und wir {2} wegen des Schnees fast den letzten Bus verpasst.',
          bank: ['wäre', 'hätte', 'hätten', 'wären'],
          loesungen: { 1: 'wäre', 2: 'hätten' },
        },
        { typ: 'mc', frage: 'Ich ___ dir gern beim Umzug geholfen, aber du hast mich ja nicht gefragt.', optionen: ['wäre', 'hätte', 'würde'], loesung: 1 },
        { typ: 'mc', frage: 'Wenn der Flug nicht ausgefallen ___, wären wir schon gestern am Urlaubsort angekommen.', optionen: ['hätte', 'war', 'wäre'], loesung: 2 },
        { typ: 'mc', frage: 'Du hättest mich wirklich früher ___!', optionen: ['gewarnt sollen', 'sollen warnen', 'warnen sollen'], loesung: 2 },
        {
          typ: 'korrektur',
          optionen: ['Ich würde das gemacht haben, aber ich hatte keine Zeit.', 'Ich hätte das gemacht, aber ich hatte keine Zeit.'],
          loesung: 1,
          warum: '«Lo habría hecho» es **hätte gemacht**. El calco *würde … gemacht haben* no se usa para el pasado irreal.',
        },
        {
          typ: 'korrektur',
          optionen: ['Gestern wäre ich auf dem Eis fast gefallen.', 'Gestern falle ich auf dem Eis fast.'],
          loesung: 0,
          warum: 'En español «casi me caigo» va en presente; en alemán lo que no llegó a pasar exige Konjunktiv II de pasado: **wäre fast gefallen**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Wenn ich früher losgegangen hätte, hätte ich den Zug erwischt.', 'Wenn ich früher losgegangen wäre, hätte ich den Zug erwischt.'],
          loesung: 1,
          warum: 'El español usa siempre «haber», pero *losgehen* forma el Perfekt con *sein* → **wäre losgegangen**.',
        },
        {
          typ: 'satzbau',
          woerter: ['anrufen', 'Wir', 'sofort', 'den', 'müssen', 'hätten', 'Arzt'],
          loesung: 'Wir hätten den Arzt sofort anrufen müssen.',
          alt: ['Wir hätten sofort den Arzt anrufen müssen.', 'Den Arzt hätten wir sofort anrufen müssen.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Leserbrief. Entscheide, welche Aussage dem Text entspricht.',
      textTitel: 'Leserbrief: Die Stadt hätte uns fragen müssen',
      text: 'Zu Ihrem Artikel „Hallenbad endgültig geschlossen“ vom 12. März: Als langjährige Schwimmerin bin ich enttäuscht und auch ein wenig wütend. Seit Jahren war bekannt, dass das Dach undicht ist. Hätte die Stadt es rechtzeitig reparieren lassen, wäre die Sanierung heute nicht so teuer geworden. Außerdem hätte man die Bürgerinnen und Bürger früher informieren müssen. Viele von uns hätten gern geholfen, zum Beispiel mit einem Förderverein oder einer Spendenaktion. In unserer Nachbarstadt ist genau das passiert: Dort hätte der Gemeinderat das Bad vor fünf Jahren beinahe geschlossen, doch ein Verein sammelte in wenigen Monaten genug Geld, um es zu retten. Besonders leid tun mir die Schulkinder. Für den Schwimmunterricht müssen sie jetzt mit dem Bus ins Hallenbad der Nachbarstadt fahren — vierzig Minuten pro Strecke. Ich hoffe sehr, dass der Gemeinderat aus diesem Fehler lernt. Eine offene Diskussion wäre von Anfang an der richtige Weg gewesen. — Brigitte Albers, Neustadt',
      items: [
        { typ: 'rf', aussage: 'Das Problem mit dem Dach war schon lange bekannt.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was wäre nach Meinung der Autorin passiert, wenn man die Bürger früher informiert hätte?',
          optionen: ['Sie hätten vor dem Rathaus protestiert.', 'Sie hätten das Dach selbst repariert.', 'Viele hätten sich zum Beispiel mit Spenden engagiert.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Das Hallenbad in der Nachbarstadt wurde vor fünf Jahren geschlossen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Welche Folge der Schließung nennt die Autorin?',
          optionen: ['Die Schulkinder haben jetzt einen langen Weg zum Schwimmunterricht.', 'Viele Schwimmer sind aus dem Verein ausgetreten.', 'Die Eintrittspreise in der Nachbarstadt sind gestiegen.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst ein Gespräch zwischen zwei Freunden. Entscheide, welche Aussage dem Gehörten entspricht.',
      audio: {
        transcript: 'Frau: Hallo Timo! Na, wie war dein Vorstellungsgespräch gestern?\nMann: Ach, Carla, frag lieber nicht. Ich wäre beinahe zu spät gekommen. Die S-Bahn ist ausgefallen, und ich musste ein Taxi nehmen.\nFrau: Du hättest eben früher losfahren sollen. Hast du es denn noch pünktlich geschafft?\nMann: Ja, zwei Minuten vor zehn war ich da. Aber dann kam die nächste Überraschung: Ein Teil des Gesprächs war auf Englisch. Wenn ich das gewusst hätte, hätte ich mich ganz anders vorbereitet.\nFrau: Stand das denn nicht in der Einladung?\nMann: Doch, ganz unten. Ich hätte die E-Mail genauer lesen müssen. Bei den Fragen zur Software lief es dafür richtig gut.\nFrau: Und wann bekommst du Bescheid?\nMann: Eigentlich wollten sie sich erst nächste Woche melden. Aber die Chefin hat mich heute Morgen schon angerufen: Ich bin in der zweiten Runde. Die ist nicht am Donnerstag, wie zuerst geplant, sondern schon am Dienstag.\nFrau: Na siehst du! Dann wäre der ganze Stress gar nicht nötig gewesen.',
      },
      items: [
        { typ: 'rf', aussage: 'Timo ist zu spät zu seinem Vorstellungsgespräch gekommen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was hat Timo im Gespräch überrascht?',
          optionen: ['Es gab schwierige Fragen zur Software.', 'Die Chefin war nicht anwesend.', 'Er musste teilweise Englisch sprechen.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'In der Einladung stand, dass ein Teil des Gesprächs auf Englisch stattfindet.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wann findet die zweite Runde statt?',
          optionen: ['am Donnerstag', 'am Dienstag', 'am Freitag'],
          loesung: 1,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib eine Beschwerde mit mindestens 60 Wörtern. Denk an Betreff, Anrede und Gruß.',
      aufgabe: 'Du hast an einer Tagesreise mit dem Bus teilgenommen, die sehr schlecht organisiert war. Schreib dem Reiseveranstalter eine E-Mail.',
      punkte: [
        'Beschreibe, was schiefgelaufen ist.',
        'Erkläre, was der Veranstalter hätte besser machen sollen oder können.',
        'Fordere eine Entschädigung (Ich würde Sie bitten, … / Könnten Sie …?).',
      ],
      minWoerter: 60,
      beispielLoesung: 'Betreff: Beschwerde über die Tagesreise nach Lindenau am 14. Juni — Sehr geehrte Damen und Herren, am vergangenen Samstag habe ich an Ihrer Tagesreise nach Lindenau teilgenommen und war leider sehr enttäuscht. Der Bus kam mit einer Stunde Verspätung, und die Stadtführung fiel ganz aus, weil der Reiseleiter krank war. Wenn Sie uns vorher informiert hätten, hätte ich die Reise verschoben. Außerdem hätten Sie kurzfristig einen anderen Reiseleiter organisieren müssen. So haben wir den ganzen Nachmittag ohne Programm verbracht. Ich würde Sie daher bitten, mir mindestens die Hälfte des Reisepreises zu erstatten. Mit freundlichen Grüßen, Ahmet Yılmaz',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Berichte von einer eigenen Erfahrung. Du hast 100 Sekunden Zeit.',
      aufgabe: 'Erzähl von einer Entscheidung oder einer Situation in deinem Leben, in der du heute anders handeln würdest. Sprich etwa 100 Sekunden und verwende den Konjunktiv II der Vergangenheit (hätte / wäre + Partizip II, auch mit sollen oder können).',
      punkte: [
        'was damals passiert ist',
        'was du hättest anders machen sollen oder können',
        'was passiert wäre, wenn du dich anders entschieden hättest',
        'was du daraus gelernt hast',
      ],
      redemittel: ['Ich möchte von … erzählen.', 'Ich hätte damals … sollen.', 'Wenn ich … hätte, wäre / hätte ich …', 'Beinahe wäre / hätte ich …', 'Daraus habe ich gelernt, dass …'],
      maxSekunden: 100,
      beispielLoesung: 'Ich möchte von meinem ersten Jahr an der Universität erzählen. Ich habe damals Wirtschaft studiert, weil meine Eltern das für vernünftig hielten. Eigentlich habe ich mich viel mehr für Sprachen interessiert, aber das habe ich niemandem gesagt. Das erste Jahr war dann ziemlich schlimm: Ich hatte keine Lust zu lernen und wäre beinahe durch zwei Prüfungen gefallen. Heute weiß ich, dass ich früher mit meinen Eltern hätte sprechen sollen. Ich hätte auch zur Studienberatung gehen können, aber ich habe mich einfach nicht getraut. Wenn ich gleich am Anfang ehrlich gewesen wäre, hätte ich ein ganzes Jahr gespart, und wahrscheinlich hätte ich auch weniger Stress gehabt. Nach dem zweiten Semester habe ich dann doch gewechselt, und meine Eltern haben viel ruhiger reagiert, als ich gedacht hatte. Ganz umsonst war das Jahr aber nicht: Ohne die Wirtschaftskurse hätte ich meine jetzige Stelle vielleicht nicht bekommen. Gelernt habe ich daraus vor allem eines: Man sollte Probleme sofort ansprechen und nicht monatelang warten.',
    },
  ],
}
