// Übungsheft B2 — Lektion 31: Sprechen Teil 1 — Vortrag + Nachfragen
export default {
  lektion: 31,
  titel: 'Übungsheft — Vortrag + Nachfragen',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Signalwörter, feste Verbindungen und Satzbau im Vortrag: Wähle die passende Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Zum Schluss möchte ich ein kurzes Fazit {1}. Zusammenfassend kann man sagen, {2} beide Lösungen Vorteile haben.',
          bank: ['ziehen', 'machen', 'dass', 'ob'],
          loesungen: { 1: 'ziehen', 2: 'dass' },
        },
        {
          typ: 'luecke',
          text: 'Ich komme jetzt {1} nächsten Punkt. Danach gehe ich kurz {2} die Nachteile ein.',
          bank: ['zum', 'im', 'auf', 'über'],
          loesungen: { 1: 'zum', 2: 'auf' },
        },
        {
          typ: 'luecke',
          text: 'Gute Frage! Wenn ich dich richtig {1}, fragst du, {2} ich jeden Tag Sport mache.',
          bank: ['verstehe', 'kenne', 'ob', 'dass'],
          loesungen: { 1: 'verstehe', 2: 'ob' },
        },
        {
          typ: 'mc',
          frage: 'Darf ich Ihnen zu Ihrem Vortrag noch eine Frage ___?',
          optionen: ['machen', 'stellen', 'geben'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: '___ ist das Leben in der Stadt praktisch, andererseits ist es oft laut und teuer.',
          optionen: ['Einerseits', 'Sowohl', 'Entweder'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Mit welchem Satz leitest du am Ende des Vortrags zu den Nachfragen über?',
          optionen: ['Ich möchte heute über dieses Thema sprechen.', 'Ich komme jetzt zum nächsten Punkt.', 'Vielen Dank — gibt es noch Fragen?'],
          loesung: 2,
        },
        {
          typ: 'zuordnen',
          links: ['Ich möchte heute über … sprechen.', 'Ein Beispiel dafür ist …', 'Ich komme jetzt zum nächsten Punkt.', 'Zusammenfassend kann man sagen, …', 'Wie ist das eigentlich bei dir?'],
          rechts: ['Einleitung', 'eigene Erfahrung', 'Übergang', 'Fazit', 'Frage zurückgeben'],
          loesung: {
            'Ich möchte heute über … sprechen.': 'Einleitung',
            'Ein Beispiel dafür ist …': 'eigene Erfahrung',
            'Ich komme jetzt zum nächsten Punkt.': 'Übergang',
            'Zusammenfassend kann man sagen, …': 'Fazit',
            'Wie ist das eigentlich bei dir?': 'Frage zurückgeben',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Meiner Meinung nach das Einkaufen online ist bequemer.', 'Meiner Meinung nach ist das Einkaufen online bequemer.'],
          loesung: 1,
          warum: '*Meiner Meinung nach* ocupa la posición 1: el verbo conjugado va **justo después** (inversión).',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich habe damit letzten Monat eine gute Erfahrung gemacht.', 'Ich habe damit letzten Monat eine gute Erfahrung gehabt.'],
          loesung: 0,
          warum: '«Tener una experiencia» se dice **eine Erfahrung machen**, no *haben*.',
        },
        {
          typ: 'satzbau',
          woerter: ['davon', 'man', 'Es', 'Zeit', 'ab', 'hat', 'wie', 'hängt', 'viel'],
          loesung: 'Es hängt davon ab, wie viel Zeit man hat.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Forumsbeitrag und löse die Aufgaben.',
      textTitel: 'Forum „Deutsch lernen“: Mein Vortrag in der mündlichen Prüfung',
      text: 'Letzte Woche hatte ich meine mündliche B2-Prüfung, und ich möchte kurz von meinen Erfahrungen berichten. Mein Thema war „Homeoffice — Vor- und Nachteile“. In der Vorbereitung habe ich leider den Fehler gemacht, ganze Sätze auf meinen Zettel zu schreiben. Als ich angefangen habe, habe ich deshalb fast nur abgelesen und kaum Blickkontakt gehalten. Nach etwa einer Minute habe ich das gemerkt, den Zettel zur Seite gelegt und frei weitergesprochen. Das hat überraschend gut funktioniert, denn die Struktur hatte ich im Kopf: Einleitung, Vorteile, Nachteile, Fazit. Am meisten geholfen haben mir aber meine eigenen Beispiele. Ich arbeite seit zwei Jahren zweimal pro Woche zu Hause und konnte viel aus eigener Erfahrung erzählen. Bei den Nachfragen war ich zuerst nervös, doch mit einem ruhigen „Gute Frage!“ habe ich Zeit gewonnen. Mein Tipp für alle: Schreibt nur Stichwörter auf und übt den Vortrag mehrmals laut mit Timer. — Kemal',
      items: [
        {
          typ: 'mc',
          frage: 'Welchen Fehler hat Kemal bei der Vorbereitung gemacht?',
          optionen: ['Er hat zu wenige Beispiele gesammelt.', 'Er hat ganze Sätze auf den Zettel geschrieben.', 'Er hat das Thema falsch verstanden.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Kemal hat den ganzen Vortrag vom Zettel abgelesen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was hat Kemal laut Beitrag am meisten geholfen?',
          optionen: ['die Fragen seines Partners', 'ein Vortragskurs vor der Prüfung', 'seine eigenen Beispiele aus dem Arbeitsalltag'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Kemal empfiehlt, den Vortrag mehrmals laut zu üben.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Hör die Sprachnachricht und löse die Aufgaben.',
      audio: {
        transcript: 'Hallo Daniela, hier ist Karin, deine Kursleiterin. Ich wollte dir noch kurz eine Rückmeldung zu deinem Probevortrag von heute geben, weil wir im Unterricht keine Zeit mehr hatten. Dein Thema, das Leben auf dem Land, hast du wirklich gut gegliedert. Die Einleitung war klar, und den roten Faden hat man die ganze Zeit gehört. Besonders gefallen hat mir dein Beispiel mit dem Bus, der nur zweimal am Tag fährt. Zwei Dinge solltest du aber noch üben. Erstens warst du schon nach zweieinhalb Minuten fertig, vorgesehen sind ungefähr vier. Erzähl also bei jedem Punkt ein bisschen mehr aus eigener Erfahrung. Zweitens hat am Ende das Fazit gefehlt, du hast einfach aufgehört. Noch etwas Organisatorisches. Die Probeprüfung findet nicht am Donnerstag statt, sondern erst am Freitag, und zwar um Viertel nach neun in Raum zwölf. Bring bitte nur einen Zettel mit Stichwörtern mit. Bis dann, tschüss!',
      },
      items: [
        { typ: 'rf', aussage: 'Die Kursleiterin lobt den Aufbau von Danielas Vortrag.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was soll Daniela laut der Kursleiterin noch üben?',
          optionen: ['Sie soll langsamer und deutlicher sprechen.', 'Sie soll länger sprechen und mehr von sich selbst erzählen.', 'Sie soll eine kürzere Einleitung vorbereiten.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Daniela hat ihren Vortrag mit einem Fazit abgeschlossen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wann findet die Probeprüfung statt?',
          optionen: ['am Freitag um Viertel nach neun', 'am Donnerstag um Viertel nach neun', 'am Freitag um Viertel vor neun'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib einen Forumsbeitrag mit mindestens 60 Wörtern und geh auf alle drei Punkte ein.',
      aufgabe: 'In einem Forum für Deutschlernende schreibt Valentina: „Ich habe große Angst vor dem Vortrag in der mündlichen Prüfung. Wie bereitet ihr euch darauf vor?“ Antworte ihr.',
      punkte: [
        'Beschreibe, wie du deinen Vortrag aufbaust.',
        'Berichte von einer eigenen Erfahrung mit einer Präsentation.',
        'Gib Valentina einen konkreten Tipp für die Nachfragen.',
      ],
      minWoerter: 60,
      beispielLoesung: 'Hallo Valentina, ich kenne das Gefühl gut! Ich baue meinen Vortrag immer gleich auf: eine kurze Einleitung mit dem Plan, dann zwei Punkte mit je einem Beispiel und am Ende ein Fazit. Letztes Jahr habe ich im Sprachkurs eine Präsentation über das Wohnen in der Stadt gehalten. Zuerst war ich sehr nervös, aber weil ich nur Stichwörter auf dem Zettel hatte, konnte ich frei sprechen und Blickkontakt halten. Mein Tipp für die Nachfragen: Sag zuerst „Gute Frage!“, dann hast du ein paar Sekunden Zeit. Antworte kurz und stell am Ende eine Gegenfrage. Viel Erfolg! Liebe Grüße, Hamid',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen kurzen Vortrag und beantworte danach eine Nachfrage. Sprich insgesamt etwa zwei Minuten frei, nur mit Stichwörtern.',
      aufgabe: 'Halte in deinem Sprachkurs einen kurzen Vortrag (etwa anderthalb Minuten) zum Thema „Ein Haustier in der Stadtwohnung — Vor- und Nachteile“. Gliedere ihn in Einleitung, Hauptteil und Fazit. Danach stellt dir eine Kursteilnehmerin diese Nachfrage: „Und was passiert mit dem Tier, wenn man in den Urlaub fährt?“ Beantworte sie in zwei, drei Sätzen.',
      punkte: [
        'Nenne mindestens einen Vorteil und einen Nachteil.',
        'Berichte von einer eigenen Erfahrung oder gib ein Beispiel.',
        'Sag deine Meinung und zieh ein kurzes Fazit.',
        'Beantworte die Nachfrage: erst bestätigen, dann kurz antworten.',
      ],
      redemittel: [
        'Ich möchte heute über … sprechen.',
        'Ein großer Vorteil ist, dass …',
        'Ein Beispiel dafür ist …',
        'Ich komme jetzt zu den Nachteilen.',
        'Zusammenfassend kann man sagen, dass …',
        'Gute Frage! …',
      ],
      maxSekunden: 120,
      beispielLoesung: 'Ich möchte heute über die Frage sprechen, ob ein Haustier in eine Stadtwohnung gehört. Zuerst spreche ich über die Vorteile, danach über die Nachteile, und am Ende sage ich meine Meinung. Zuerst einmal zu den Vorteilen. Ein großer Vorteil ist, dass ein Tier vielen Menschen guttut, vor allem denen, die allein wohnen: Man kommt nach Hause, und jemand wartet auf einen. Außerdem bewegt man sich mehr, weil ein Hund bei jedem Wetter nach draußen muss. Ein Beispiel dafür ist meine Nachbarin: Seit sie einen Hund hat, kennt sie das halbe Viertel. Ich komme jetzt zu den Nachteilen. Ein Tier kostet Zeit und Geld, und in einer kleinen Wohnung ohne Garten fühlt sich nicht jedes Tier wohl. Dazu kommt, dass nicht jeder Vermieter Haustiere erlaubt. Meiner Meinung nach hängt es davon ab, wie viel Zeit man wirklich hat. Zusammenfassend kann man sagen, dass ein Haustier das Leben in der Stadt schöner machen kann, wenn man die Verantwortung ernst nimmt. Gibt es noch Fragen? — Gute Frage! Der Urlaub ist tatsächlich ein Problem. Bei uns passt dann eine Freundin auf die Katze auf, sonst müsste ich eine Tierpension bezahlen. Hättest du denn selbst gern ein Tier?',
    },
  ],
}
