// Übungsheft B2 — Lektion 40: Reisen & Mobilität
export default {
  lektion: 40,
  titel: 'Übungsheft — Reisen & Mobilität',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Kollokationen, Präpositionen und Satzbau rund ums Reisen: Wähle die passende Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Wegen einer Erkrankung musste ich die Buchung {1}. Zum Glück habe ich später eine neue {2} in der Altstadt gefunden.',
          bank: ['stornieren', 'Unterkunft', 'aufgeben', 'Strecke'],
          loesungen: { 1: 'stornieren', 2: 'Unterkunft' },
        },
        {
          typ: 'luecke',
          text: 'Der Regionalzug hatte zwanzig Minuten {1}, sodass wir in Fulda den {2} verpasst haben.',
          bank: ['Verspätung', 'Anschluss', 'Erstattung', 'Gepäck'],
          loesungen: { 1: 'Verspätung', 2: 'Anschluss' },
        },
        {
          typ: 'luecke',
          text: 'Am Flughafen haben wir zuerst unser Gepäck {1}. Kurz darauf erfuhren wir, dass unser Flug wegen eines Streiks {2}.',
          bank: ['aufgegeben', 'ausfiel', 'umstieg', 'storniert'],
          loesungen: { 1: 'aufgegeben', 2: 'ausfiel' },
        },
        {
          typ: 'mc',
          frage: 'Mit dem Nachtzug haben wir eine Strecke von über tausend Kilometern ___.',
          optionen: ['umgestiegen', 'zurückgelegt', 'aufgegeben'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Da mein Zug komplett ausgefallen ist, möchte ich eine Erstattung des Fahrpreises ___.',
          optionen: ['verpassen', 'zurücklegen', 'beantragen'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Wer im Urlaub nachhaltig reisen will, sollte vor Ort möglichst ___ Verkehrsmittel nutzen.',
          optionen: ['öffentliche', 'offene', 'allgemeine'],
          loesung: 0,
        },
        {
          typ: 'zuordnen',
          links: ['eine Buchung', 'in Frankfurt', 'eine Erstattung', 'das Gepäck', 'öffentliche Verkehrsmittel'],
          rechts: ['stornieren', 'umsteigen', 'beantragen', 'aufgeben', 'nutzen'],
          loesung: {
            'eine Buchung': 'stornieren',
            'in Frankfurt': 'umsteigen',
            'eine Erstattung': 'beantragen',
            'das Gepäck': 'aufgeben',
            'öffentliche Verkehrsmittel': 'nutzen',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Wir fahren am liebsten in Zug in den Urlaub.', 'Wir fahren am liebsten mit dem Zug in den Urlaub.'],
          loesung: 1,
          warum: 'El medio de transporte va con **mit + Dativ**: *mit dem Zug*, no «en tren» calcado como *in Zug*.',
        },
        {
          typ: 'korrektur',
          optionen: ['Der Zug ist wegen des Sturms ausgefallen.', 'Der Zug hat sich wegen des Sturms ausgefallen.'],
          loesung: 0,
          warum: '**ausfallen** no es reflexivo (no calques «se canceló») y forma el Perfekt con **sein**.',
        },
        {
          typ: 'satzbau',
          woerter: ['verpassten', 'Zug', 'den', 'Weil', 'ausfiel', 'wir', 'der', 'Anschluss'],
          loesung: 'Weil der Zug ausfiel, verpassten wir den Anschluss.',
          alt: ['Wir verpassten den Anschluss, weil der Zug ausfiel.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Forumsbeitrag und löse die Aufgaben.',
      textTitel: 'Forumsbeitrag: „Mit dem Nachtzug nach Rom — nie wieder?“',
      text: 'Im Mai wollte ich zum ersten Mal ohne Flugzeug nach Italien reisen, weil mir nachhaltiges Reisen immer wichtiger wird. Also habe ich einen Platz im Nachtzug von München nach Rom gebucht. Leider fing die Reise schlecht an: Mein Regionalzug nach München hatte eine Stunde Verspätung, und ich hätte den Nachtzug beinahe verpasst. Im Nachtzug selbst war es dann überraschend bequem. Ich habe gut geschlafen und bin morgens ausgeruht in Rom angekommen — viel entspannter als nach einem Flug mit Sicherheitskontrolle und langer Wartezeit am Gepäckband. Auf der Rückfahrt fiel der Zug allerdings wegen eines Streiks komplett aus. Ich musste spontan eine Unterkunft suchen und konnte erst zwei Tage später zurückfahren. Die Erstattung für das Ticket habe ich inzwischen beantragt, bisher aber keine Antwort bekommen. Trotzdem würde ich die Strecke jederzeit wieder mit der Bahn zurücklegen. Mein Tipp: Plant beim Umsteigen genug Zeit ein und rechnet für den Rückweg mit einem Puffer von einem Tag. — Jonas_unterwegs',
      items: [
        {
          typ: 'mc',
          frage: 'Warum hat Jonas sich für den Nachtzug entschieden?',
          optionen: ['Weil alle Flüge nach Rom ausgebucht waren.', 'Weil ihm nachhaltiges Reisen wichtig ist.', 'Weil der Nachtzug günstiger war als ein Flug.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Jonas hat den Nachtzug in München verpasst.', loesung: false },
        { typ: 'rf', aussage: 'Die Hinfahrt im Nachtzug empfand Jonas als angenehmer als eine Flugreise.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was schreibt Jonas über die Erstattung?',
          optionen: ['Er hat sie beantragt, aber noch keine Rückmeldung erhalten.', 'Er hat das Geld bereits zurückbekommen.', 'Er hat auf eine Erstattung verzichtet.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst eine Durchsage im Zug. Entscheide bei jeder Aufgabe, welche Lösung dem Gehörten entspricht.',
      audio: {
        transcript: 'Sehr geehrte Fahrgäste, hier spricht Ihre Zugbegleiterin. Wegen einer technischen Störung an der Strecke haben wir zurzeit etwa fünfunddreißig Minuten Verspätung. Wir erreichen Kassel deshalb nicht wie geplant um vierzehn Uhr zwölf, sondern voraussichtlich um vierzehn Uhr siebenundvierzig. Nun zu Ihren Anschlüssen. Der Regionalzug nach Göttingen wartet auf Sie. Er fährt heute ausnahmsweise nicht von Gleis vier, sondern von Gleis sieben. Den Anschluss nach Frankfurt um vierzehn Uhr dreißig werden Sie leider verpassen. Reisende nach Frankfurt nehmen bitte den nächsten Zug um fünfzehn Uhr dreißig vom selben Gleis, Ihre Fahrkarten bleiben gültig. Der Bus nach Bad Wildungen fällt heute aus, bitte wenden Sie sich an die Information in der Bahnhofshalle. Wer sein Ziel mit mehr als sechzig Minuten Verspätung erreicht, kann eine Erstattung beantragen. Die Formulare dafür bekommen Sie bei mir in Wagen fünf oder später im Reisezentrum. Bewahren Sie dafür bitte Ihre Fahrkarte auf. Wir bitten um Ihr Verständnis und wünschen Ihnen trotzdem eine gute Weiterreise.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Wann kommt der Zug voraussichtlich in Kassel an?',
          optionen: ['um 14:12 Uhr', 'um 14:35 Uhr', 'um 14:47 Uhr'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Der Regionalzug nach Göttingen fährt heute von Gleis vier ab.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was sollen Reisende nach Frankfurt tun?',
          optionen: ['Sie nehmen den Zug, der eine Stunde später fährt.', 'Sie kaufen eine neue Fahrkarte.', 'Sie steigen in den Bus um.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Das Formular für die Erstattung können die Fahrgäste schon im Zug bekommen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Schreib eine Beschwerde mit mindestens 60 Wörtern und geh auf alle drei Punkte ein.',
      aufgabe: 'Dein Zug von Köln nach Hamburg hatte über zwei Stunden Verspätung. Deshalb hast du den letzten Anschluss nach Kiel verpasst und musstest in Hamburg übernachten. Schreib an den Kundenservice des Bahnunternehmens.',
      punkte: [
        'Beschreib genau, was auf der Reise passiert ist.',
        'Erklär, welche Folgen die Verspätung für dich hatte.',
        'Fordere eine Erstattung für das Ticket und die Übernachtung.',
      ],
      minWoerter: 60,
      beispielLoesung: 'Sehr geehrte Damen und Herren, am 14. März bin ich mit dem Zug von Köln nach Hamburg gefahren. Der Zug hatte über zwei Stunden Verspätung, sodass ich in Hamburg den letzten Anschluss nach Kiel verpasst habe. Da an diesem Abend kein Zug mehr fuhr, musste ich kurzfristig eine Unterkunft suchen und 95 Euro für ein Hotelzimmer bezahlen. Außerdem kam ich am nächsten Morgen zu spät zu einem wichtigen Termin. Ich bitte Sie daher, mir die Hälfte des Fahrpreises sowie die Hotelkosten zu erstatten. Eine Kopie des Tickets und die Hotelrechnung finden Sie im Anhang. Mit freundlichen Grüßen, Lucía Fernández',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen kurzen Vortrag wie in Teil 1 der mündlichen Prüfung. Sprich etwa zwei Minuten frei und in ganzen Sätzen.',
      aufgabe: 'Dein Vortragsthema lautet: „Viele Touristen — Chance oder Belastung für beliebte Reiseziele?“ Halte einen kurzen, klar gegliederten Vortrag (etwa zwei Minuten), in dem du Vor- und Nachteile abwägst.',
      punkte: [
        'Führe in das Thema ein und kündige deine Gliederung an.',
        'Nenne Vorteile und Nachteile des Tourismus für die Menschen, die an solchen Orten leben.',
        'Gib ein Beispiel aus deiner eigenen Erfahrung.',
        'Formuliere zum Schluss ein Fazit.',
      ],
      redemittel: ['Ich möchte heute über das Thema … sprechen.', 'Zunächst nenne ich …, danach gehe ich auf … ein.', 'Ein Beispiel aus meiner Erfahrung: …', 'Zusammenfassend lässt sich sagen, dass …'],
      maxSekunden: 120,
      beispielLoesung: 'Ich möchte heute über das Thema Tourismus sprechen, genauer gesagt über die Frage, ob viele Touristen für ein beliebtes Reiseziel eine Chance oder eine Belastung sind. Zunächst nenne ich einige Vorteile, danach gehe ich auf die Nachteile ein, und am Ende ziehe ich ein kurzes Fazit. Zu den Vorteilen: Der Tourismus schafft Arbeitsplätze, nicht nur in Hotels und Restaurants, sondern auch im Handel. Außerdem wird in Orte investiert, die viele Gäste anziehen: Bahnstrecken werden ausgebaut und alte Gebäude renoviert. Davon profitieren auch die Einheimischen. Es gibt aber auch Nachteile. Wo immer mehr Wohnungen als Unterkunft für Urlauber vermietet werden, steigen die Mieten, und viele Einheimische können sich das Zentrum nicht mehr leisten. Dazu kommen Lärm, Müll und überfüllte Verkehrsmittel in der Hauptsaison. Ein Beispiel aus meiner Erfahrung: Ich komme aus Valencia. Früher kannte man in meinem Viertel alle Nachbarn, heute gibt es in manchen Häusern fast nur noch Ferienwohnungen. Gleichzeitig arbeitet mein Bruder als Kellner und lebt von genau diesen Gästen. Zusammenfassend lässt sich sagen, dass der Tourismus weder nur gut noch nur schlecht ist. Meiner Meinung nach sollten Städte die Zahl der Ferienwohnungen begrenzen, damit sie auch für ihre Bewohner lebenswert bleiben.',
    },
  ],
}
