// Real-exam guardrails. Simulacros (mode='simulation') go through the
// legacy path in index.js untouched. Real exams (mode='real') go through
// here and hit every wall we can put up so the result can be trusted for
// a level certificate:
//
//   • Level match: the student may only take a real exam matching their
//     own users.level.
//   • Cooldown: at most 1 real attempt per (userId, level, module) in
//     any rolling 24h window.
//   • Lifetime cap: at most 3 finished real attempts per module.
//   • Duration: rejected if the elapsed time is more than the exam's
//     durationMinutes + 5min grace.
//   • Server-side scoring for Lesen/Hören: the client-supplied score is
//     ignored; we recompute from the responses using the answer manifest
//     built by scripts/build-pruefungen-answers.mjs.
//   • Freezing: once an attempt is used as the basis for a certificate
//     (schule_certificates), it's frozen — no more re-grading.
//
// Schreiben/Sprechen keep the AI-graded score because those numbers
// come from our own Anthropic-graded endpoints, not the client. If
// someone wanted to spoof them they'd have to also fake the Anthropic
// response, which is beyond the browser.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Loaded once at boot. Regenerated by `npm run sync-pruefungen`.
let ANSWERS = {}
try {
  ANSWERS = JSON.parse(fs.readFileSync(path.join(__dirname, 'pruefungen-answers.json'), 'utf8'))
} catch (e) {
  console.warn('[realExam] pruefungen-answers.json missing — run `npm run sync-pruefungen`. Server-side scoring will fail closed.')
}

export const REAL_ATTEMPT_COOLDOWN_HOURS = 24
export const REAL_ATTEMPT_LIFETIME_CAP = 3
export const REAL_DURATION_GRACE_SECONDS = 5 * 60
export const PRUEFUNG_PASS_PCT = 60

// Aprobado de NIVEL (garantía). Desde B1, como el examen oficial, cada módulo
// por separado (≥60 %). En A1/A2 el examen oficial es una prueba global: los
// módulos compensan — media ≥60 % sin ningún módulo por debajo del mínimo.
export const COMPENSATION_LEVELS = ['A1', 'A2']
export const COMPENSATION_MIN_MODULE_PCT = 40
const LEVEL_MODULES = ['lesen', 'hoeren', 'schreiben', 'sprechen']

// modules: { lesen: { bestPct, passed } | null, … } — mejores intentos reales.
export function levelPassStatus(level, modules) {
  const passedCount = LEVEL_MODULES.filter(m => modules?.[m]?.passed).length
  const pcts = LEVEL_MODULES.map(m => modules?.[m]?.bestPct)
  const allAttempted = pcts.every(p => p != null)
  const avgPct = allAttempted ? Math.round(pcts.reduce((s, p) => s + Number(p), 0) / pcts.length) : null
  const compensated = passedCount < LEVEL_MODULES.length
    && COMPENSATION_LEVELS.includes(String(level).toUpperCase())
    && allAttempted
    && pcts.every(p => Number(p) >= COMPENSATION_MIN_MODULE_PCT)
    && avgPct >= PRUEFUNG_PASS_PCT
  return {
    passedCount,
    allPassed: passedCount === LEVEL_MODULES.length || compensated,
    compensated,
    avgPct,
    compensation: COMPENSATION_LEVELS.includes(String(level).toUpperCase())
      ? { minModulePct: COMPENSATION_MIN_MODULE_PCT, avgPct: PRUEFUNG_PASS_PCT }
      : null,
  }
}

// Mismo texto de consigna que construye el cliente (PruefungPlayer) — tiene
// que coincidir byte a byte para reutilizar la corrección ya cacheada.
export function productiveTaskPrompt(part) {
  return part.taskPrompt + (part.bullets ? '\n\nPunkte:\n' + part.bullets.map(b => `- ${b}`).join('\n') : '')
}

// Grace + duration limit lookup
export function examSpec(examId) {
  return ANSWERS[examId] || null
}

/**
 * Recompute the objective (Lesen / Hören) score server-side from the
 * responses the client sent. Mirrors src/data/pruefungen/index.js →
 * gradeObjectiveExam so the result matches what the frontend rendered.
 */
export function gradeObjective(examId, responses) {
  const spec = ANSWERS[examId]
  if (!spec) return null

  let score = 0
  let maxScore = 0
  for (const part of spec.parts || []) {
    if (Array.isArray(part.questions)) {
      for (const q of part.questions) {
        const userAnswer = responses?.[q.id]
        if (q.type === 'matching') {
          const total = Object.keys(q.correct || {}).length
          const pp = q.pointsPerItem || 1
          maxScore += total * pp
          for (const itemId of Object.keys(q.correct || {})) {
            if (userAnswer && userAnswer[itemId] === q.correct[itemId]) score += pp
          }
        } else {
          const pts = q.points || 1
          maxScore += pts
          if (userAnswer === q.correct) score += pts
        }
      }
    }
    if (Array.isArray(part.fields)) {
      // Formular (A1 Schreiben). `expected` es una LISTA de variantes; mismo
      // criterio que PruefungPlayer: exacto o contención con ≥4 caracteres.
      const normF = s => String(s ?? '').trim().toLowerCase().replace(/\s+/g, ' ')
      for (const f of part.fields) {
        const pts = f.points || 1
        maxScore += pts
        const v = normF(responses?.[part.id]?.[f.id])
        const variants = Array.isArray(f.expected) ? f.expected : [f.expected]
        const ok = v && variants.some(exp => {
          const e = normF(exp)
          return v === e || (v.length >= 4 && (e.includes(v) || v.includes(e)))
        })
        if (ok) score += pts
      }
    }
  }
  return { score, maxScore }
}

/**
 * Gatekeeper called before inserting a new attempt with mode='real'.
 * Returns null if allowed, or { status, error } to send back verbatim.
 */
export async function assertCanStartRealAttempt({ pool, userId, level, module, userLevel }) {
  const declaredLevel = String(level || '').toUpperCase()
  const currentLevel = String(userLevel || 'A1').toUpperCase()
  if (declaredLevel !== currentLevel) {
    return {
      status: 403,
      error: `Solo puedes rendir el examen real de tu nivel actual (${currentLevel}). Cambia de nivel antes de intentar ${declaredLevel}.`,
    }
  }

  // Cooldown: 24h from the most recent real attempt (started or finished)
  const [recent] = await pool.query(
    `SELECT id, startedAt
       FROM schule_pruefungen_attempts
      WHERE userId = ? AND level = ? AND module = ? AND mode = 'real'
        AND startedAt > DATE_SUB(NOW(), INTERVAL ? HOUR)
      ORDER BY startedAt DESC
      LIMIT 1`,
    [userId, declaredLevel, module, REAL_ATTEMPT_COOLDOWN_HOURS]
  )
  if (recent.length > 0) {
    return {
      status: 429,
      error: `Debes esperar 24 h entre intentos reales del mismo módulo. Podés hacer un simulacro mientras tanto.`,
      code: 'cooldown_active',
    }
  }

  // Lifetime cap: max 3 finished real attempts per module
  const [finished] = await pool.query(
    `SELECT COUNT(*) AS n
       FROM schule_pruefungen_attempts
      WHERE userId = ? AND level = ? AND module = ?
        AND mode = 'real' AND finishedAt IS NOT NULL`,
    [userId, declaredLevel, module]
  )
  if ((finished[0]?.n || 0) >= REAL_ATTEMPT_LIFETIME_CAP) {
    return {
      status: 403,
      error: `Alcanzaste el máximo de ${REAL_ATTEMPT_LIFETIME_CAP} intentos reales para este módulo. Contactá con la academia si necesitás una excepción.`,
      code: 'lifetime_cap_reached',
    }
  }

  return null
}

/**
 * Called from POST /api/pruefungen/attempts/:id/finish for mode='real'.
 * Given the raw attempt row + the payload the client sent, returns the
 * canonical {score, maxScore} we should persist for Lesen/Hören. Never
 * trusts the client's `score`. Schreiben/Sprechen → gradeProductiveReal.
 */
export function canonicalRealScore(attemptRow, payload) {
  const spec = ANSWERS[attemptRow.examId]
  if (!spec) return null

  if (spec.module === 'lesen' || spec.module === 'hoeren') {
    // Full server-side recompute. Client `score` is ignored.
    const graded = gradeObjective(attemptRow.examId, payload.responses || {})
    if (!graded) return null
    return graded
  }

  // Schreiben / Sprechen: se corrigen con gradeProductiveReal (asíncrono).
  return null
}

/**
 * Schreiben / Sprechen en modo real: el servidor puntúa él mismo a partir
 * de los textos/transcripciones enviados — nunca acepta la nota del cliente.
 * `grade(kind, { level, taskType, taskPrompt, text, minWords, durationSeconds })`
 * devuelve la corrección IA ({ total 0-100 }); el cliente ya pidió la misma
 * corrección durante el examen, así que normalmente sale de la caché.
 */
export async function gradeProductiveReal(attemptRow, responses, grade) {
  const spec = ANSWERS[attemptRow.examId]
  if (!spec) return null
  const objective = gradeObjective(attemptRow.examId, responses || {}) || { score: 0, maxScore: 0 }
  let score = objective.score
  let maxScore = objective.maxScore
  for (const part of spec.parts || []) {
    if (part.kind !== 'writing-task' && part.kind !== 'speaking-task') continue
    const possible = part.maxScore || 25
    maxScore += possible
    const r = responses?.[part.id]
    const text = part.kind === 'writing-task'
      ? String(r || '').trim()
      : String(r?.transcript || '').trim()
    if (!text) continue
    const ai = await grade(part.kind, {
      level: spec.level,
      taskType: part.taskType,
      taskPrompt: productiveTaskPrompt(part),
      text,
      minWords: part.minWords,
      durationSeconds: r?.durationSeconds || 0,
    })
    const total = Math.max(0, Math.min(100, Number(ai?.total) || 0))
    score += Math.round((total / 100) * possible)
  }
  return { score, maxScore }
}

/**
 * Enforce the duration limit. Returns true if the attempt is within the
 * allowed time (durationMinutes + grace); false otherwise.
 */
export function withinTimeLimit(attemptRow, spec) {
  const started = new Date(attemptRow.startedAt).getTime()
  const elapsed = Math.max(0, (Date.now() - started) / 1000)
  const limit = ((spec?.durationMinutes || 999) * 60) + REAL_DURATION_GRACE_SECONDS
  return elapsed <= limit
}
