// Übungsheft C1 — Lektion 24: Schreiben Teil 1 — Der Diskussionsbeitrag
export default {
  lektion: 24,
  titel: 'Übungsheft — Der Diskussionsbeitrag',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Bearbeite die Aufgaben zur Sprache der Argumentation. Achte auf feste Verbindungen, die Rektion der Verben und die Redemittel des Abwägens.',
      items: [
        {
          typ: 'luecke',
          text: 'Die {1} der Reform verweisen darauf, dass die Verwaltungskosten sinken würden; {2} hingegen wenden ein, dass die Qualität der Beratung darunter leide.',
          bank: ['Befürworter', 'Kritiker', 'Standpunkte', 'Maßnahmen'],
          loesungen: { 1: 'Befürworter', 2: 'Kritiker' },
        },
        {
          typ: 'luecke',
          text: 'Dieses Argument lässt sich leicht {1}, denn die zugrunde liegenden Zahlen sind veraltet. Ich {2} daher für einen Mittelweg.',
          bank: ['entkräften', 'plädiere', 'überwiege', 'abwägen'],
          loesungen: { 1: 'entkräften', 2: 'plädiere' },
        },
        {
          typ: 'zuordnen',
          links: ['eine These', 'wirksame Maßnahmen', 'einen Mittelweg', 'Vor- und Nachteile gegeneinander', 'sich kritisch mit einem Thema'],
          rechts: ['aufstellen', 'ergreifen', 'wählen', 'abwägen', 'auseinandersetzen'],
          loesung: { 'eine These': 'aufstellen', 'wirksame Maßnahmen': 'ergreifen', 'einen Mittelweg': 'wählen', 'Vor- und Nachteile gegeneinander': 'abwägen', 'sich kritisch mit einem Thema': 'auseinandersetzen' },
        },
        {
          typ: 'mc',
          frage: 'Zwar trifft es zu, dass die Umstellung anfangs teuer ist, ___ rechnet sie sich langfristig.',
          optionen: ['obwohl', 'dennoch', 'trotz'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Dieses Argument ___ an Gewicht, wenn man bedenkt, dass die Erhebung nur zwei Monate umfasste.',
          optionen: ['büßt', 'verliert', 'nimmt'],
          loesung: 1,
        },
        {
          typ: 'luecke',
          text: 'Ein pauschales Verbot wäre verfehlt, {1} digitale Kompetenzen im Berufsleben zunehmend unverzichtbar werden. Es {2} der Schule die Chance, einen verantwortungsvollen Umgang überhaupt zu vermitteln.',
          bank: ['zumal', 'nähme', 'obwohl', 'entkräftete'],
          loesungen: { 1: 'zumal', 2: 'nähme' },
        },
        {
          typ: 'korrektur',
          optionen: ['Nach meiner Meinung nach ist ein generelles Verbot unverhältnismäßig.', 'Meiner Meinung nach ist ein generelles Verbot unverhältnismäßig.'],
          loesung: 1,
          warum: '*nach* aparece **una sola vez**: pospuesto (*Meiner Meinung nach*) o antepuesto (*Nach meiner Meinung*). La doble preposición es un calco de «según mi opinión».',
        },
        {
          typ: 'korrektur',
          optionen: ['Befürworter verweisen zu Recht auf die sinkenden Unfallzahlen.', 'Befürworter verweisen zu Recht an die sinkenden Unfallzahlen.'],
          loesung: 0,
          warum: '*verweisen* («aducir, remitir a») rige **auf** + acusativo.',
        },
        {
          typ: 'korrektur',
          optionen: ['Der Beitrag setzt sich gründlich über die Einwände auseinander.', 'Der Beitrag setzt sich gründlich mit den Einwänden auseinander.'],
          loesung: 1,
          warum: '*sich auseinandersetzen* va siempre con **mit** + dativo. *über* es interferencia de «discutir sobre».',
        },
        {
          typ: 'satzbau',
          woerter: ['überwiegen', 'Sicht', 'Alles', 'die', 'in', 'meiner', 'allem', 'aus', 'Vorteile'],
          loesung: 'Alles in allem überwiegen aus meiner Sicht die Vorteile.',
          alt: ['Alles in allem überwiegen die Vorteile aus meiner Sicht.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies das Essayfragment. Entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist.',
      textTitel: 'Essayfragment: Wählen mit sechzehn?',
      text: 'Kaum eine demokratiepolitische Streitfrage wird so zuverlässig wiederbelebt wie die nach dem Wahlalter. Die Befürworter einer Absenkung auf sechzehn Jahre verweisen darauf, dass Jugendliche von politischen Entscheidungen — man denke an Rente oder Klimaschutz — am längsten betroffen seien. Wer die Folgen trage, müsse auch mitbestimmen dürfen. Kritiker wenden ein, Sechzehnjährigen fehle die nötige Reife; zudem seien sie leichter zu beeinflussen.\nZwar ist der zweite Einwand nicht völlig aus der Luft gegriffen. Er verliert jedoch an Gewicht, wenn man bedenkt, dass sich auch Erwachsene keineswegs immun gegen Stimmungsmache zeigen. Stichhaltiger erscheint mir ein Argument, das in der Debatte selten fällt: Wer mit sechzehn zum ersten Mal wählt, lebt meist noch im Elternhaus und geht zur Schule — dort kann politische Bildung unmittelbar ansetzen. Erfahrungen aus Ländern, in denen bereits ab sechzehn gewählt wird, deuten darauf hin, dass junge Erstwähler nicht seltener, sondern eher häufiger zur Wahl gehen.\nIch plädiere daher für die Absenkung — allerdings nicht als isolierte Maßnahme. Ohne einen Politikunterricht, der diesen Namen verdient, bliebe sie eine symbolische Geste.',
      items: [
        { typ: 'rf', aussage: 'Die Befürworter argumentieren, Jugendliche seien von politischen Entscheidungen besonders lange betroffen.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wie geht der Verfasser mit dem Einwand um, Sechzehnjährige seien leicht zu beeinflussen?',
          optionen: ['Er weist ihn als völlig haltlos zurück.', 'Er gesteht ihm einen wahren Kern zu, relativiert ihn aber durch den Vergleich mit Erwachsenen.', 'Er macht ihn sich zu eigen und spricht sich deshalb gegen die Absenkung aus.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Welches Argument hält der Verfasser für besonders überzeugend?',
          optionen: ['Bei sechzehnjährigen Erstwählern kann die politische Bildung in der Schule unmittelbar ansetzen.', 'Jugendliche tragen die Folgen politischer Entscheidungen am längsten.', 'Sechzehnjährige interessieren sich stärker für Politik als Erwachsene.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Der Verfasser hält die Absenkung des Wahlalters für sich genommen für ausreichend.', loesung: false },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst eine Nachricht auf deiner Mailbox. Entscheide beim Hören, welche Antwort zutrifft bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Guten Tag, hier spricht Sabine Reuter von der Forumsredaktion der Wochenzeitung. Ich rufe wegen Ihres Diskussionsbeitrags zu der Streitfrage an, ob Kurzstreckenflüge verboten werden sollten. Wir würden Ihren Text gern abdrucken, allerdings nicht in der Ausgabe am Donnerstag, wie ich Ihnen geschrieben hatte, sondern erst in der Wochenendausgabe am Samstag. Dafür müssten wir ihn etwas kürzen. Zurzeit hat er rund dreihundertfünfzig Wörter, Platz haben wir für zweihundertfünfzig. Ich schlage vor, das zweite Beispiel zu streichen, das mit der Bahnfahrt nach Wien. Ihr stichhaltigstes Argument, der Vergleich der Reisezeiten, bleibt selbstverständlich stehen. Noch etwas zum Inhalt. Sie wägen sehr sorgfältig ab, aber Ihr eigener Standpunkt wird erst im letzten Satz deutlich. Unsere Leserinnen und Leser sollten früher erfahren, wofür Sie plädieren. Könnten Sie den Text entsprechend ergänzen? Die überarbeitete Fassung bräuchte ich bis Mittwoch, zwölf Uhr, und zwar per E-Mail, bitte nicht über das Formular auf unserer Website, denn das ist derzeit gestört. Falls Sie Fragen haben, erreichen Sie mich heute bis halb fünf und morgen ab neun Uhr unter der Durchwahl vier, sieben, null. Vielen Dank und auf Wiederhören.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Wann soll der Beitrag nach dem jetzigen Stand erscheinen?',
          optionen: ['am Mittwoch', 'am Samstag', 'am Donnerstag'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Welche Passage soll nach dem Vorschlag von Frau Reuter entfallen?',
          optionen: ['das Beispiel mit der Bahnfahrt nach Wien', 'der Vergleich der Reisezeiten', 'der Schlusssatz'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Frau Reuter bemängelt, dass der Beitrag die Gegenseite zu wenig berücksichtigt.', loesung: false },
        { typ: 'rf', aussage: 'Heute ist Frau Reuter bis 16:30 Uhr telefonisch erreichbar.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse einen Diskussionsbeitrag mit mindestens 80 Wörtern. Wäge sichtbar ab, entkräfte mindestens ein Gegenargument mit einer Konzession und setze pro Absatz höchstens ein Redemittel aus der Lektion ein.',
      aufgabe: 'Im Forum einer überregionalen Zeitung wird die Frage diskutiert: „Sollten große Supermärkte gesetzlich verpflichtet werden, unverkaufte Lebensmittel zu spenden?“ Schreibe einen Beitrag.',
      punkte: [
        'Führe in die Streitfrage ein und erläutere, warum sie derzeit an Bedeutung gewinnt.',
        'Nenne ein Argument für die Spendenpflicht und ein Gegenargument und wäge beide gegeneinander ab.',
        'Beziehe begründet Position, gern in Form eines Mittelwegs.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Kaum ein Thema wird derzeit so kontrovers diskutiert wie die Frage, ob große Supermärkte verpflichtet werden sollten, unverkaufte Lebensmittel zu spenden. Angesichts der Mengen, die täglich im Müll landen, ist diese Debatte längst überfällig.\nEin gewichtiges Argument für eine solche Pflicht ist die Verschwendung selbst: Einwandfreie Lebensmittel wegzuwerfen, während andere Menschen auf Unterstützung angewiesen sind, lässt sich ethisch kaum rechtfertigen. Kritiker wenden ein, dass gemeinnützige Ausgabestellen schon heute an ihre logistischen Grenzen stoßen. Zwar trifft dieser Einwand zu, dennoch spricht er nicht gegen die Pflicht, sondern für eine bessere Ausstattung der Abnehmer.\nIch plädiere daher für einen Mittelweg: eine Spendenpflicht für große Märkte, verbunden mit staatlicher Förderung für Transport und Kühlung. Nur so wird aus einer guten Absicht eine wirksame Maßnahme.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen strukturierten Vortrag von etwa zweieinhalb Minuten. Mach den Aufbau für deine Zuhörer hörbar: Gliederung ankündigen, Übergänge markieren, Fazit ziehen.',
      aufgabe: 'Halte auf einer Tagung zum Thema „Zusammenleben in der Stadt“ einen strukturierten Vortrag von etwa zweieinhalb Minuten über Einsamkeit in der Großstadt. Kündige zu Beginn deine Gliederung an, markiere die Übergänge hörbar und schließe mit einem Fazit, in dem du Position beziehst.',
      punkte: [
        'Umreiße das Problem und seine Bedeutung.',
        'Nenne zwei Ursachen.',
        'Wäge zwei mögliche Maßnahmen gegeneinander ab.',
        'Ziehe ein Fazit und sag, wofür du plädierst.',
      ],
      redemittel: ['Ich möchte zunächst …, anschließend … und abschließend …', 'Damit komme ich zu …', 'Ein gewichtiges Argument dafür ist, dass …', 'Zusammenfassend lässt sich festhalten: …'],
      maxSekunden: 150,
      beispielLoesung: 'Meine Damen und Herren, in einer Stadt mit einer Million Einwohnern allein zu sein, das klingt paradox, und doch ist es für viele Alltag. Ich möchte zunächst skizzieren, wie groß das Problem ist, anschließend nach den Ursachen fragen und abschließend zwei Maßnahmen gegeneinander abwägen. Zur Ausgangslage. In Umfragen gibt etwa jeder Vierte an, sich häufig einsam zu fühlen, und zwar nicht nur ältere Menschen, sondern zunehmend auch junge Erwachsene. Das ist mehr als ein unangenehmes Gefühl, denn Einsamkeit macht auf Dauer krank. Damit komme ich zu den Ursachen. Erstens leben in Großstädten immer mehr Menschen allein, oft weit entfernt von ihrer Familie. Zweitens verschwinden die Orte, an denen man sich begegnet, ohne etwas kaufen zu müssen. Was lässt sich dagegen tun? Das führt mich zu meinem letzten Punkt. Manche Städte setzen auf Beratungstelefone und Besuchsdienste. Ein gewichtiges Argument dafür ist, dass man so auch Menschen erreicht, die ihre Wohnung kaum noch verlassen. Kritiker wenden jedoch ein, dass dadurch keine dauerhaften Kontakte entstehen. Stichhaltiger erscheint mir deshalb die zweite Maßnahme, nämlich offene Nachbarschaftstreffs. Zwar kosten sie Miete und Personal, dennoch wirken sie nachhaltiger, weil dort aus Besuchern Bekannte werden. Zusammenfassend lässt sich festhalten: Einsamkeit ist kein privates Versagen, sondern eine Folge davon, wie wir unsere Städte gestalten. Ich plädiere daher dafür, Begegnung genauso selbstverständlich zu planen wie Straßen und Parkplätze. Vielen Dank.',
    },
  ],
}
