// Übungsheft C1 — Lektion 06: Konjunktiv II — irreale Sätze
export default {
  lektion: 6,
  titel: 'Übungsheft — Konjunktiv II & irreale Sätze',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Bearbeite die Aufgaben zum Konjunktiv II. Entscheide jeweils, ob Gegenwart oder Vergangenheit gemeint ist und ob die eigene Form oder die würde-Umschreibung angemessen ist.',
      items: [
        {
          typ: 'luecke',
          text: 'Wenn es in der Innenstadt mehr Grünflächen {1}, {2} sich die Hitze im Hochsommer deutlich besser ertragen.',
          bank: ['gäbe', 'ließe', 'würde', 'wäre'],
          loesungen: { 1: 'gäbe', 2: 'ließe' },
        },
        {
          typ: 'luecke',
          text: 'Hätte der Verein die Antragsfrist nicht {1}, {2} er die Förderung ohne Weiteres erhalten.',
          bank: ['versäumt', 'hätte', 'wäre', 'gescheitert'],
          loesungen: { 1: 'versäumt', 2: 'hätte' },
        },
        {
          typ: 'luecke',
          text: 'Die Verhandlungen {1} beinahe an einer bloßen Formalie gescheitert. Im Rückblick {2} man die Verträge wohl sorgfältiger prüfen müssen.',
          bank: ['wären', 'hätte', 'würden'],
          loesungen: { 1: 'wären', 2: 'hätte' },
        },
        {
          typ: 'mc',
          frage: 'An deiner Stelle ___ ich das Angebot nicht ohne Rücksprache annehmen.',
          optionen: ['werde', 'würde', 'hätte'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Er spricht über die Reform, ___ er sie ganz allein ausgearbeitet.',
          optionen: ['als ob', 'wie wenn', 'als hätte'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Ohne zusätzliche Fördermittel ___ die Umsetzung des Projekts schwierig werden.',
          optionen: ['dürfte', 'durfte', 'darf'],
          loesung: 0,
        },
        {
          typ: 'korrektur',
          optionen: ['Wenn ich mehr Zeit haben würde, würde ich öfter ins Theater gehen.', 'Wenn ich mehr Zeit hätte, würde ich öfter ins Theater gehen.'],
          loesung: 1,
          warum: 'En la oración con *wenn*, *haben* va siempre en su forma propia (**hätte**); *haben würde* equivale al error español «si tendría».',
        },
        {
          typ: 'korrektur',
          optionen: ['Fast hätte ich gestern den letzten Zug verpasst.', 'Fast verpasse ich gestern den letzten Zug.'],
          loesung: 0,
          warum: '«Casi pierdo el tren» va en presente en español, pero *fast/beinahe* exige **Konjunktiv II de pasado** (*hätte verpasst*): el hecho no llegó a ocurrir.',
        },
        {
          typ: 'korrektur',
          optionen: ['Viele meinen, dass man die Anwohner früher informieren müssen hätte.', 'Viele meinen, dass man die Anwohner früher hätte informieren müssen.'],
          loesung: 1,
          warum: 'Con doble infinitivo en la subordinada, el verbo conjugado se adelanta: **hätte informieren müssen**, nunca al final.',
        },
        {
          typ: 'zuordnen',
          links: ['eine Antragsfrist', 'an der Finanzierung', 'von einer falschen Annahme', 'gegebenenfalls Rücksprache', 'eine Entscheidung zutiefst'],
          rechts: ['versäumen', 'scheitern', 'ausgehen', 'halten', 'bedauern'],
          loesung: {
            'eine Antragsfrist': 'versäumen',
            'an der Finanzierung': 'scheitern',
            'von einer falschen Annahme': 'ausgehen',
            'gegebenenfalls Rücksprache': 'halten',
            'eine Entscheidung zutiefst': 'bedauern',
          },
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies das Essayfragment. Entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist.',
      textTitel: 'Essayfragment: Das Leben, das wir nicht gelebt haben',
      text: 'Kaum ein Gedanke beschäftigt uns so hartnäckig wie der an das, was hätte sein können. Hätte ich damals das Stipendium in Wien angenommen, wäre ich heute vielleicht ein anderer Mensch. Wäre ich doch nur ein wenig mutiger gewesen! Solche Sätze kennen die meisten von uns, und sie haben etwas Tröstliches und Quälendes zugleich. Die Psychologie unterscheidet dabei zwei Richtungen des Rückblicks. Wer sich ausmalt, wie alles hätte besser laufen können, bereut meist das, was er versäumt hat, und nicht das, was er getan hat. Wer dagegen überlegt, wie alles noch schlimmer hätte kommen können, empfindet eher Erleichterung: Beinahe wäre ich an jenem Morgen mit dem Auto gefahren.\nBemerkenswert ist, dass die Reue über verpasste Gelegenheiten mit den Jahren eher zunimmt, während die über Fehlentscheidungen verblasst. Ein falscher Schritt lässt sich erklären, oft sogar korrigieren; eine nie ergriffene Chance dagegen bleibt offen, gleichsam unendlich. Man könnte daraus schließen, wir sollten öfter Ja sagen. Doch das wäre zu einfach. Denn jeder Rückblick beruht auf einer Annahme, die selten zutrifft: dass wir damals gewusst hätten, was wir heute wissen. Gerecht wäre es, dem jüngeren Ich jene Nachsicht zu gewähren, die wir jedem Fremden selbstverständlich zugestehen würden.',
      items: [
        { typ: 'rf', aussage: 'Dem Text zufolge bereuen Menschen häufiger, was sie unterlassen haben, als das, was sie getan haben.', loesung: true },
        {
          typ: 'mc',
          frage: 'Welche Wirkung hat die Vorstellung, wie alles noch schlimmer hätte kommen können?',
          optionen: ['Sie macht mutiger bei künftigen Entscheidungen.', 'Sie löst eher Erleichterung aus.', 'Sie verstärkt die Reue über frühere Fehlentscheidungen.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Warum wiegt eine verpasste Chance laut Text mit der Zeit schwerer als ein Fehler?',
          optionen: ['Weil verpasste Chancen meist wichtigere Lebensbereiche betreffen.', 'Weil andere Menschen uns verpasste Chancen häufiger vorhalten.', 'Weil sich ein Fehler erklären lässt, eine nicht genutzte Chance aber offen bleibt.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Der Autor empfiehlt, grundsätzlich jede sich bietende Gelegenheit zu ergreifen.', loesung: false },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst einen Ausschnitt aus einer Podiumsdiskussion. Entscheide, welche Lösung dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Moderatorin: Angenommen, die Vier-Tage-Woche würde morgen überall eingeführt. Was wäre die Folge? Herr Lehmann, Sie leiten einen Handwerksbetrieb mit vierzig Beschäftigten.\nUnternehmer: Für uns wäre das kaum zu schaffen. Wir finden schon heute nicht genug Fachkräfte. Wenn alle einen Tag weniger arbeiten würden, müssten wir Aufträge ablehnen.\nModeratorin: Frau Seidel, Sie forschen seit Jahren zur Arbeitszeit. Teilen Sie diese Sorge?\nForscherin: Nur zum Teil. In unserem Versuch mit sechzehn Betrieben ist die Produktivität nicht gesunken, sondern in den meisten Fällen sogar leicht gestiegen. Vor allem aber haben sich die Krankheitstage fast halbiert.\nUnternehmer: Das mag im Büro funktionieren. Ein Dach lässt sich aber nicht schneller decken, nur weil die Leute ausgeruht sind.\nForscherin: Da gebe ich Ihnen recht. Deshalb würde ich auch nie ein Gesetz für alle Branchen fordern. Sinnvoller wäre es, wenn jeder Betrieb selbst entscheiden dürfte.\nModeratorin: Herr Lehmann, haben Sie es denn je ausprobiert?\nUnternehmer: Beinahe. Vor zwei Jahren hätten wir fast ein Modell mit vier längeren Tagen eingeführt. Gescheitert ist es nicht an mir, sondern an der Belegschaft. Die Älteren wollten keine Zehn-Stunden-Tage.\nForscherin: Hätten Sie die Arbeitszeit insgesamt verkürzt, statt sie nur anders zu verteilen, wäre die Abstimmung vermutlich anders ausgegangen.\nUnternehmer: Mag sein. Aber das hätte ich mir damals schlicht nicht leisten können.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Was hat der Versuch von Frau Seidel in Bezug auf die Produktivität ergeben?',
          optionen: ['Sie ist in den meisten Betrieben leicht gestiegen.', 'Sie ist spürbar gesunken.', 'Sie hat sich nahezu halbiert.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Frau Seidel spricht sich für eine gesetzliche Vier-Tage-Woche in allen Branchen aus.', loesung: false },
        {
          typ: 'mc',
          frage: 'Woran ist das Vier-Tage-Modell im Betrieb von Herrn Lehmann gescheitert?',
          optionen: ['an fehlenden Fachkräften', 'an der Ablehnung durch Herrn Lehmann selbst', 'am Widerstand älterer Beschäftigter gegen sehr lange Arbeitstage'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Herrn Lehmann zufolge wäre eine Verkürzung der gesamten Arbeitszeit für seinen Betrieb damals finanziell nicht tragbar gewesen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine Stellungnahme mit mindestens 80 Wörtern. Setze den Konjunktiv II gezielt ein — für Hypothesen, für den Rückblick und für vorsichtige Einschätzungen.',
      aufgabe: 'In einem Online-Magazin wird das Essayfragment unter der Frage „Lieber etwas wagen als später etwas bereuen?“ diskutiert. Schreib einen Beitrag, in dem du Stellung nimmst.',
      punkte: [
        'Gib die zentrale These des Essayfragments knapp mit eigenen Worten wieder.',
        'Bezieh Stellung und stütze deine Position mit einem Beispiel, das eine irreale Bedingung in der Vergangenheit enthält.',
        'Formuliere eine vorsichtige Einschränkung deiner Position, etwa mit „dürfte“ oder „Man könnte einwenden, dass …“.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Das Essayfragment vertritt die These, dass wir verpasste Gelegenheiten langfristig stärker bereuen als Fehlentscheidungen, warnt aber davor, daraus eine simple Lebensregel abzuleiten.\nIch teile diese Einschätzung weitgehend. Hätte ich mich mit zwanzig nicht getraut, für ein Jahr nach Leipzig zu gehen, würde ich heute kaum fließend Deutsch sprechen — und vermutlich würde ich mein Zögern bis heute bereuen. Wer nie etwas wagt, geht zwar kein Risiko ein, versäumt aber womöglich die wichtigsten Erfahrungen seines Lebens.\nMan könnte allerdings einwenden, dass sich nicht jeder Risiken leisten kann: Für jemanden mit Familie und wenig Rücklagen dürfte ein Neuanfang weit schwerer wiegen. Mut ist also wichtig — allerdings unter der Voraussetzung, dass man die möglichen Folgen realistisch abgewogen hat.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen strukturierten Vortrag von etwa zweieinhalb Minuten. Bleib konsequent im Gedankenexperiment und verwende dafür den Konjunktiv II der Gegenwart und der Vergangenheit.',
      aufgabe: 'Halte in deinem Sprachkurs einen strukturierten Vortrag von etwa zweieinhalb Minuten zu dem Gedankenexperiment „Was wäre, wenn von morgen an alle Menschen dieselbe Sprache sprächen?“. Bleib konsequent im Gedankenexperiment: Verwende den Konjunktiv II der Gegenwart und, wenn du von deinem Erlebnis erzählst, den Konjunktiv II der Vergangenheit.',
      punkte: [
        'Beschreibe, wie sich der Alltag und das Zusammenleben verändern würden.',
        'Erläutere, was dadurch gewonnen wäre und was verloren ginge.',
        'Erzähle von einer Situation, die mit einer gemeinsamen Sprache anders verlaufen wäre.',
        'Schließe mit einer vorsichtig formulierten eigenen Einschätzung.',
      ],
      redemittel: ['Angenommen, alle sprächen …', 'Gewonnen wäre dadurch vor allem …', 'Hätten wir damals …, wäre …', 'Unter der Voraussetzung, dass …, könnte ich mir vorstellen, …'],
      maxSekunden: 150,
      beispielLoesung: 'Angenommen, alle Menschen sprächen von morgen an dieselbe Sprache: Wie sähe unsere Welt dann aus? Auf dieses Gedankenexperiment möchte ich mich heute einlassen. Zunächst zum Alltag. Wir könnten uns überall mühelos verständigen, im Urlaub genauso wie auf dem Amt. Niemand müsste mehr Formulare übersetzen lassen, und wer in ein anderes Land zöge, fände sich dort vom ersten Tag an zurecht. Sprachkurse wie dieser wären überflüssig, und ich säße jetzt vermutlich nicht hier. Was wäre damit gewonnen? Sicher würden Handel und Wissenschaft profitieren, denn Missverständnisse ließen sich viel leichter vermeiden. Auch Zugewanderte hätten es leichter, weil ihnen keine Stelle mehr wegen fehlender Sprachkenntnisse verwehrt bliebe. Verloren ginge allerdings etwas Entscheidendes. Mit jeder Sprache verschwände eine eigene Art, die Welt zu sehen: Redewendungen, Witze und Gedichte, die sich nicht übertragen lassen. Die Welt wäre bequemer, aber auch ärmer. Ich denke dabei an meine erste Woche in Deutschland. Meine Vermieterin erklärte mir damals die Mülltrennung, und ich verstand kaum ein Wort. Hätten wir eine gemeinsame Sprache gehabt, wäre mir manche peinliche Situation erspart geblieben. Andererseits hätte ich meine Vermieterin dann nie um Hilfe bitten müssen, und wir wären wohl gar nicht ins Gespräch gekommen. Gerade aus dieser Unbeholfenheit ist eine Freundschaft entstanden. Mein Fazit fällt deshalb vorsichtig aus. Unter der Voraussetzung, dass sie nur zusätzlich neben den Muttersprachen bestünde, könnte ich mir eine gemeinsame Sprache durchaus vorstellen. Müssten wir dafür alle anderen aufgeben, wäre der Preis meines Erachtens zu hoch.',
    },
  ],
}
