// Übungsheft C1 — Lektion 12: Relativsätze komplex
export default {
  lektion: 12,
  titel: 'Übungsheft — Relativsätze komplex',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Bearbeite die Aufgaben zu den komplexen Relativsätzen. Bestimme jeweils zuerst das Bezugswort — ein Nomen, ein unbestimmtes Pronomen oder den ganzen vorangehenden Satz — und prüfe, welche Präposition das Verb verlangt.',
      items: [
        {
          typ: 'luecke',
          text: 'Die Architektin, {1} Entwürfe mehrfach ausgezeichnet wurden, übernimmt nun die Leitung des Projekts. Der Verein, {2} Mitglieder überwiegend im Ruhestand sind, sucht dringend Nachwuchs.',
          bank: ['deren', 'dessen', 'denen', 'die'],
          loesungen: { 1: 'deren', 2: 'dessen' },
        },
        {
          typ: 'luecke',
          text: 'Es gibt noch vieles, {1} wir vor der Abstimmung sprechen müssen. Die Kollegin, {2} ich mich jederzeit verlassen konnte, wechselt in eine andere Abteilung.',
          bank: ['worüber', 'auf die', 'worauf', 'über die'],
          loesungen: { 1: 'worüber', 2: 'auf die' },
        },
        {
          typ: 'luecke',
          text: 'Der Prüfbericht wurde am Montag veröffentlicht, {1} die Ministerin noch am selben Abend vor die Presse trat. Die Behörde senkte zudem die Gebühren, {2} bei den Antragstellern auf breite Zustimmung stieß.',
          bank: ['woraufhin', 'was', 'wobei', 'wodurch'],
          loesungen: { 1: 'woraufhin', 2: 'was' },
        },
        {
          typ: 'mc',
          frage: 'Eine Methode, ___ Hilfe sich Fehler frühzeitig erkennen lassen, spart erhebliche Kosten.',
          optionen: ['mit dessen', 'mit der', 'mit deren'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Wem die Entscheidung nicht zusagt, ___ kann innerhalb eines Monats Widerspruch einlegen.',
          optionen: ['der', 'dem', 'wer'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Der Referent erläuterte das Konzept ausführlich, ___ er die Kostenfrage allerdings aussparte.',
          optionen: ['woraufhin', 'wobei', 'wodurch'],
          loesung: 1,
        },
        {
          typ: 'korrektur',
          optionen: ['Die Stiftung, dessen Vorsitz seit Jahren vakant ist, sucht eine neue Leitung.', 'Die Stiftung, deren Vorsitz seit Jahren vakant ist, sucht eine neue Leitung.'],
          loesung: 1,
          warum: 'A diferencia de «cuyo», **dessen/deren** concuerda con el antecedente (*die Stiftung* → deren), no con el sustantivo que sigue (*der Vorsitz*).',
        },
        {
          typ: 'korrektur',
          optionen: ['Der Forscher, dessen Thesen umstritten sind, hält den Eröffnungsvortrag.', 'Der Forscher, dessen die Thesen umstritten sind, hält den Eröffnungsvortrag.'],
          loesung: 0,
          warum: 'Tras *dessen/deren* el sustantivo va **sin artículo**: *dessen Thesen*, igual que «cuyas tesis».',
        },
        {
          typ: 'korrektur',
          optionen: ['Die Mittel, die die Stadt verfügt, reichen bei Weitem nicht aus.', 'Die Mittel, über die die Stadt verfügt, reichen bei Weitem nicht aus.'],
          loesung: 1,
          warum: '*Verfügen* rige **über** + acusativo; la preposición se antepone al relativo: *über die*. Es el mismo caso que «de los que dispone».',
        },
        {
          typ: 'zuordnen',
          links: ['eine Maßnahme', 'einen Sachverhalt', 'eine Voraussetzung', 'zu der Erkenntnis', 'auf einem Missverständnis'],
          rechts: ['ergreifen', 'schildern', 'erfüllen', 'gelangen', 'beruhen'],
          loesung: {
            'eine Maßnahme': 'ergreifen',
            'einen Sachverhalt': 'schildern',
            'eine Voraussetzung': 'erfüllen',
            'zu der Erkenntnis': 'gelangen',
            'auf einem Missverständnis': 'beruhen',
          },
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Bericht. Entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist.',
      textTitel: 'Bericht: Ein Jahr Reparaturtreff im Stadtteilzentrum',
      text: 'Vor einem Jahr eröffnete im Kasseler Stadtteil Wehlheiden ein Reparaturtreff, dessen Idee auf eine Gruppe pensionierter Handwerker zurückgeht. Jeden zweiten Samstag bringen Anwohnerinnen und Anwohner defekte Geräte mit, deren Reparatur sich in einem Fachbetrieb kaum lohnen würde: Toaster, Lampen, Fahrräder, gelegentlich auch Laptops. Wer etwas reparieren lassen möchte, muss allerdings selbst mit anpacken — eine Regel, auf deren Einhaltung die Organisatoren großen Wert legen. Denn der Treff versteht sich nicht als kostenloser Dienstleister, sondern als Ort, an dem Wissen weitergegeben wird.\nDie Bilanz, die der Trägerverein nun vorgelegt hat, fällt positiv aus. Von rund 900 Gegenständen konnten fast zwei Drittel wieder instand gesetzt werden, wodurch nach Schätzung des Vereins mehrere Tonnen Elektroschrott vermieden wurden. Bemerkenswert ist ein Umstand, mit dem anfangs niemand gerechnet hatte: Ein Großteil der Besucher kommt inzwischen weniger wegen der Geräte als wegen der Gespräche. Ein Problem bleibt jedoch der Nachwuchs. Die meisten Ehrenamtlichen sind über siebzig, und junge Menschen, die über das nötige Fachwissen verfügen, fehlen bislang. Der Verein will deshalb im Herbst Kurse anbieten, in denen Jugendliche die Grundlagen der Elektronik erlernen können.',
      items: [
        { typ: 'rf', aussage: 'Die Idee zum Reparaturtreff stammt von einer Gruppe Studierender.', loesung: false },
        {
          typ: 'mc',
          frage: 'Welche Regel gilt für alle, die ein Gerät reparieren lassen möchten?',
          optionen: ['Sie entrichten einen geringen Unkostenbeitrag.', 'Sie helfen bei der Reparatur selbst mit.', 'Sie bringen höchstens ein Gerät pro Termin mit.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Womit hatte beim Start des Projekts niemand gerechnet?',
          optionen: ['dass viele Besucher inzwischen vor allem wegen des Austauschs kommen', 'dass sich nahezu alle mitgebrachten Geräte reparieren lassen', 'dass besonders häufig Laptops zur Reparatur gebracht werden'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Der Verein plant, Jugendlichen Grundkenntnisse der Elektronik zu vermitteln.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst eine Nachricht auf dem Anrufbeantworter. Entscheide, welche Antwort dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Guten Tag, Herr Winkler, hier spricht Sabine Kraus von der Bürgerstiftung. Ich rufe wegen Ihres Förderantrags an, dessen Unterlagen uns seit letzter Woche vorliegen. Zunächst die gute Nachricht. Das Projekt, für das Sie Mittel beantragt haben, hat die erste Auswahlrunde bestanden. Allerdings fehlt uns noch der Kostenplan, ohne den der Ausschuss keine endgültige Entscheidung treffen kann. Bitte reichen Sie ihn bis Dienstag nach, und zwar nicht per Post, sondern über das Formular auf unserer Internetseite. Außerdem haben Sie eine Summe von fünfzehntausend Euro angegeben. Die Höchstgrenze, bis zu der wir fördern, liegt jedoch bei zwölftausend Euro, was Sie bei Ihrer Planung berücksichtigen sollten. Wer mehr benötigt, kann zusätzlich Mittel bei der Stadt beantragen, wobei dort andere Fristen gelten. Der Ausschuss, dessen Vorsitzende Sie gern persönlich kennenlernen möchte, tagt am Donnerstag, dem zwanzigsten März, um vierzehn Uhr dreißig. Sie hätten zehn Minuten Zeit, um Ihr Vorhaben vorzustellen, woraufhin noch Fragen gestellt werden. Alles, was Sie dafür brauchen, ist ein kurzer Überblick. Eine Präsentation ist nicht nötig. Sie erreichen mich vormittags unter der Durchwahl zwei neun fünf. Vielen Dank und auf Wiederhören.',
      },
      items: [
        { typ: 'rf', aussage: 'Der Förderantrag von Herrn Winkler ist bereits endgültig bewilligt.', loesung: false },
        {
          typ: 'mc',
          frage: 'Auf welchem Weg soll Herr Winkler den Kostenplan nachreichen?',
          optionen: ['mit der Post', 'über ein Formular im Internet', 'persönlich in der Sitzung des Ausschusses'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Welchen Betrag fördert die Stiftung höchstens?',
          optionen: ['zwölftausend Euro', 'fünfzehntausend Euro', 'zwanzigtausend Euro'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Nach der Vorstellung seines Vorhabens muss Herr Winkler im Ausschuss mit Rückfragen rechnen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine formelle E-Mail mit mindestens 80 Wörtern. Verwende mindestens einen Genitiv-Relativsatz mit dessen oder deren und einen Relativanschluss mit Präposition oder wo(r)-Form.',
      aufgabe: 'Du engagierst dich im Reparaturtreff aus dem Bericht. Schreib im Namen des Trägervereins an das Kulturamt der Stadt und bitte um finanzielle Unterstützung für die geplanten Elektronikkurse für Jugendliche.',
      punkte: [
        'Stelle den Reparaturtreff und seine bisherige Bilanz knapp vor.',
        'Erläutere, wofür die Mittel verwendet werden sollen und welche Voraussetzungen bereits erfüllt sind.',
        'Bitte um einen Gesprächstermin und schließe die E-Mail angemessen ab.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Sehr geehrte Damen und Herren,\nich wende mich im Namen des Trägervereins des Reparaturtreffs Wehlheiden an Sie, dessen Arbeit Sie vielleicht aus der Lokalpresse kennen. Im ersten Jahr haben unsere Ehrenamtlichen rund 600 Geräte instand gesetzt, wodurch mehrere Tonnen Elektroschrott vermieden wurden.\nDa die meisten unserer Helfer über siebzig sind, möchten wir im Herbst Kurse anbieten, in denen Jugendliche die Grundlagen der Elektronik erlernen. Die wichtigsten Voraussetzungen sind bereits erfüllt: Räume und erfahrene Kursleiter stehen zur Verfügung. Was uns fehlt, sind Mittel für Werkzeug und Material, über die ein kleiner Verein wie unserer nicht verfügt.\nÜber die Gelegenheit, Ihnen unser Vorhaben in einem persönlichen Gespräch vorzustellen, würden wir uns sehr freuen.\nMit freundlichen Grüßen\nTobias Engel',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen Kurzvortrag von etwa zwei Minuten. Sprich frei und zusammenhängend und verknüpfe deine Gedanken mit Relativsätzen.',
      aufgabe: 'Halte vor einer Seminargruppe einen frei gesprochenen Kurzvortrag von etwa zwei Minuten über eine Erfindung, deren Bedeutung für unseren Alltag deiner Meinung nach unterschätzt wird. Verknüpfe deine Gedanken mit mindestens drei komplexen Relativanschlüssen.',
      punkte: [
        'Stelle die Erfindung vor und erkläre, wozu sie dient.',
        'Zeige an Beispielen, was sich durch sie verändert hat.',
        'Begründe, warum ihre Bedeutung oft übersehen wird.',
        'Verwende mindestens drei komplexe Relativanschlüsse, etwa mit „deren“, „wodurch“ oder „was“.',
      ],
      redemittel: [
        'Ich möchte über eine Erfindung sprechen, deren Bedeutung …',
        '…, wodurch …',
        'Alles, was wir dafür brauchen, …',
        'Wer heute …, kann …',
        'Das ist ein Umstand, über den wir selten nachdenken.',
      ],
      maxSekunden: 150,
      beispielLoesung: 'Ich möchte heute über eine Erfindung sprechen, deren Bedeutung wir meistens übersehen: den Kühlschrank. Er steht in jeder Küche, und genau deshalb denkt kaum jemand über ihn nach.\nWozu dient er? Ganz einfach: Er hält Lebensmittel frisch, wodurch wir sie viel länger aufbewahren können. Das klingt banal, hat aber unseren Alltag grundlegend verändert. Früher musste man fast täglich einkaufen, was einen enormen Zeitaufwand bedeutete. Heute reicht ein Einkauf pro Woche. Wer berufstätig ist, kann abends in zehn Minuten etwas kochen, weil alles, was er braucht, schon im Haus ist.\nDazu kommt die Gesundheit. Milch, Fleisch und Fisch, deren Haltbarkeit früher nur wenige Tage betrug, lassen sich heute sicher lagern. Krankheiten, an denen früher viele Menschen litten, weil sie verdorbenes Essen gegessen hatten, sind selten geworden. Auch viele Medikamente müssen gekühlt werden. Ohne Kühlung wäre die moderne Medizin kaum denkbar.\nWarum wird das alles unterschätzt? Ich glaube, weil der Kühlschrank einfach funktioniert. Er ist leise und unauffällig, und das ist ein Umstand, der ihn fast unsichtbar macht. Erst wenn er kaputtgeht, merken wir, wie abhängig wir von ihm sind.\nFür mich ist er deshalb eine der wichtigsten Erfindungen überhaupt, auch wenn kaum jemand von ihm schwärmt. Vielen Dank.',
    },
  ],
}
