// Übungsheft C1 — Lektion 32: Arbeitswelt & Work-Life-Balance
export default {
  lektion: 32,
  titel: 'Übungsheft — Arbeitswelt & Work-Life-Balance',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Ergänze die festen Verbindungen des Themenfelds Arbeitswelt bzw. wähle die Form, die Kollokation, Rektion und Kontext verlangen. Achte besonders auf Lehnübersetzungen aus dem Spanischen.',
      items: [
        {
          typ: 'luecke',
          text: 'Um dem Fachkräftemangel {1}, bieten viele Betriebe inzwischen flexible Arbeitszeitmodelle an; wer dauerhaft einer hohen Belastung {2} ist, erhält zudem kostenlose Beratung.',
          bank: ['entgegenzuwirken', 'ausgesetzt', 'entgegenzusetzen', 'ausgestellt'],
          loesungen: { 1: 'entgegenzuwirken', 2: 'ausgesetzt' },
        },
        {
          typ: 'luecke',
          text: 'Im Homeoffice {1} sich die Grenze zwischen Arbeit und Privatleben leicht; umso wichtiger ist es, die ständige {2} klar zu begrenzen.',
          bank: ['verwischt', 'verwirklicht', 'Erreichbarkeit', 'Erreichung'],
          loesungen: { 1: 'verwischt', 2: 'Erreichbarkeit' },
        },
        {
          typ: 'luecke',
          text: 'Die {1} der Arbeitszeiten hat die {2} von Familie und Beruf in vielen Betrieben spürbar verbessert.',
          bank: ['Flexibilisierung', 'Vereinbarkeit', 'Verfügbarkeit', 'Befristung'],
          loesungen: { 1: 'Flexibilisierung', 2: 'Vereinbarkeit' },
        },
        {
          typ: 'mc',
          frage: 'Nach der Geburt ihrer Tochter hat Leonie ein Jahr Elternzeit ___.',
          optionen: ['genommen', 'erteilt', 'getroffen'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Die Betriebsärztin stellte fest, dass Herr Kaya an einem Burnout ___ war.',
          optionen: ['befallen', 'gelitten', 'erkrankt'],
          loesung: 2,
        },
        {
          typ: 'korrektur',
          optionen: ['Seit dem Umzug arbeitet Samira überwiegend vom Homeoffice.', 'Seit dem Umzug arbeitet Samira überwiegend im Homeoffice.'],
          loesung: 1,
          warum: 'Se dice **im Homeoffice arbeiten**; *vom Homeoffice* calca «trabajar desde casa».',
        },
        {
          typ: 'korrektur',
          optionen: ['Nach dem Abitur hat Julián in Leipzig Informatik studiert.', 'Nach dem Abitur hat Julián in Leipzig Karriere in Informatik gemacht.'],
          loesung: 0,
          warum: '«Hacer la carrera» es **studieren**; *Karriere machen* significa ascender profesionalmente.',
        },
        {
          typ: 'korrektur',
          optionen: ['Viele Eltern können Familie und Beruf nur mit großer Mühe miteinander versöhnen.', 'Viele Eltern können Familie und Beruf nur mit großer Mühe miteinander vereinbaren.'],
          loesung: 1,
          warum: '«Conciliar» trabajo y familia es **vereinbaren** (→ *die Vereinbarkeit*); *versöhnen* se dice ante todo de personas enemistadas y no es la colocación establecida con *Familie und Beruf*.',
        },
        {
          typ: 'zuordnen',
          links: ['dem Fachkräftemangel', 'die Vier-Tage-Woche', 'die Kündigung', 'in Teilzeit', 'die Produktivität konstant'],
          rechts: ['entgegenwirken', 'erproben', 'einreichen', 'wechseln', 'halten'],
          loesung: {
            'dem Fachkräftemangel': 'entgegenwirken',
            'die Vier-Tage-Woche': 'erproben',
            'die Kündigung': 'einreichen',
            'in Teilzeit': 'wechseln',
            'die Produktivität konstant': 'halten',
          },
        },
        {
          typ: 'satzbau',
          woerter: ['bestreitet', 'Erreichbarkeit', 'dass', 'Kaum', 'belastet', 'ständige', 'jemand'],
          loesung: 'Kaum jemand bestreitet, dass ständige Erreichbarkeit belastet.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Bericht und entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist.',
      textTitel: 'Bericht: Ein Jahr Vier-Tage-Woche — die Bilanz eines Maschinenbauers',
      text: 'Weniger arbeiten, gleich viel leisten? Ein Jahr lang hat ein mittelständischer Maschinenbauer aus Bielefeld die Vier-Tage-Woche erprobt — nach der Formel 100-80-100. Die Bilanz, die Geschäftsführerin Katrin Wiegand jetzt vorgelegt hat, fällt überwiegend positiv aus: In Verwaltung und Konstruktion blieb die Produktivität konstant, der Krankenstand sank um knapp ein Drittel, und auf ausgeschriebene Stellen bewarben sich deutlich mehr Fachkräfte als zuvor. „Im Wettbewerb um qualifizierte Leute sind gute Arbeitsbedingungen unser stärkstes Argument“, so Wiegand.\nGanz reibungslos verlief der Versuch allerdings nicht. In der Fertigung, wo die Maschinen im Schichtbetrieb laufen, ließ sich die Arbeit nicht einfach auf vier Tage verdichten; dort musste der Betrieb zusätzliche Kräfte einstellen, was die Kosten spürbar erhöhte. Zudem gaben einige Beschäftigte an, die Belastung an den verbleibenden vier Tagen als höher zu empfinden. Der Betriebsrat fordert deshalb, die Arbeitsdichte regelmäßig zu überprüfen.\nTrotz dieser Einwände will das Unternehmen am Modell festhalten — allerdings nicht einheitlich: Künftig sollen die Abteilungen selbst entscheiden, ob sie die verkürzte Woche übernehmen oder bei fünf Tagen mit flexibleren Arbeitszeiten bleiben. Wiegand spricht von einem „Baukasten statt Einheitslösung“.',
      items: [
        { typ: 'rf', aussage: 'In der Fertigung ließ sich die Vier-Tage-Woche ohne zusätzliches Personal umsetzen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Welche Bedeutung misst die Geschäftsführerin guten Arbeitsbedingungen bei?',
          optionen: ['Sie senkten langfristig vor allem die Kosten in der Fertigung.', 'Sie seien der wichtigste Trumpf im Wettbewerb um Fachkräfte.', 'Sie seien eine Bedingung, die der Betriebsrat durchgesetzt habe.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Wie will das Unternehmen künftig verfahren?',
          optionen: ['Es kehrt in allen Abteilungen zur Fünf-Tage-Woche zurück.', 'Es führt die Vier-Tage-Woche verbindlich für alle Beschäftigten ein.', 'Es überlässt den Abteilungen die Wahl zwischen verschiedenen Arbeitszeitmodellen.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Ein Teil der Beschäftigten empfand die Arbeit an den vier verbleibenden Tagen als belastender.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst einen Ausschnitt aus einer Podiumsdiskussion. Entscheide, welche Antwort dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Moderator: Willkommen zu unserer Podiumsdiskussion. Frau Brandt, Sie leiten das Personalwesen einer Versicherung und haben Ihre Beschäftigten an drei festen Tagen ins Büro zurückgeholt. Warum?\nFrau: Weil wir gemerkt haben, dass vor allem neue Kolleginnen und Kollegen im Homeoffice kaum Anschluss finden. Die Produktivität war übrigens nie das Problem, die blieb konstant. Was gelitten hat, war die Bindung ans Team.\nModerator: Herr Demir, Sie vertreten den Betriebsrat. Teilen Sie diese Einschätzung?\nMann: Nur zum Teil. In unserer Befragung haben nicht dreißig, sondern dreizehn Prozent angegeben, dass ihnen der Austausch fehlt. Die große Mehrheit schätzt den Wegfall des Pendelns. Was die Leute wirklich belastet, ist die ständige Erreichbarkeit am Abend.\nFrau: Da widerspreche ich gar nicht. Deshalb gilt bei uns seit Januar, dass nach achtzehn Uhr keine Mails mehr beantwortet werden müssen.\nMann: Auf dem Papier, Frau Brandt. Solange Vorgesetzte abends selbst schreiben, bleibt der Feierabend bloße Theorie.\nModerator: Was wäre denn Ihr Vorschlag?\nMann: Dass die Teams selbst festlegen, an welchen Tagen sie sich im Betrieb treffen. Feste Tage von oben treiben gerade Eltern in die Teilzeit oder zur Kündigung.\nFrau: Darüber können wir reden, sofern wenigstens ein gemeinsamer Tag pro Woche bleibt.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Weshalb hat Frau Brandt feste Bürotage eingeführt?',
          optionen: ['Weil die Produktivität im Homeoffice nachgelassen hatte.', 'Weil neue Beschäftigte im Homeoffice kaum Anschluss ans Team fanden.', 'Weil der Betriebsrat auf mehr Präsenz gedrängt hatte.'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Laut der Befragung des Betriebsrats vermisst knapp ein Drittel der Beschäftigten den Austausch im Büro.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wie beurteilt Herr Demir die Regelung, nach achtzehn Uhr keine Mails mehr beantworten zu müssen?',
          optionen: ['Er hält sie für wirkungslos, solange Vorgesetzte abends selbst Mails verschicken.', 'Er hält sie für überflüssig, weil abends ohnehin kaum jemand arbeitet.', 'Er verlangt, sie auch auf das Wochenende auszudehnen.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Frau Brandt ist bereit, über frei wählbare Bürotage zu verhandeln, wenn ein gemeinsamer Tag pro Woche erhalten bleibt.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine Stellungnahme (mindestens 80 Wörter). Verwende mindestens vier Begriffe aus dem Kernwortschatz, etwa Erreichbarkeit, Belastung, Vereinbarkeit oder Arbeitsbedingungen, und mindestens ein Redemittel, mit dem du differenzierst.',
      aufgabe: 'In einem Onlineforum wird darüber diskutiert, ob Beschäftigte ein gesetzlich verankertes Recht haben sollten, nach Feierabend nicht erreichbar zu sein. Nimm Stellung.',
      punkte: [
        'Beschreibe, wie sich die Erwartung ständiger Erreichbarkeit auf Beschäftigte auswirkt.',
        'Wäge je ein Argument für und gegen eine gesetzliche Regelung ab.',
        'Formuliere eine begründete eigene Position.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Seit sich das Homeoffice in vielen Büroberufen etabliert hat, verwischt die Grenze zwischen Arbeit und Privatleben zusehends. Wer auch abends noch Mails beantworten soll, ist einer dauerhaften Belastung ausgesetzt, die das Risiko eines Burnouts erhöht.\nFür ein Recht auf Nichterreichbarkeit spricht vor allem, dass es Beschäftigte schützt, die sich allein kaum gegen die Erwartungen ihrer Vorgesetzten wehren können. Man sollte allerdings nicht übersehen, dass starre Regeln gerade jenen schaden könnten, die ihre Arbeitszeit bewusst flexibel gestalten, um Familie und Beruf zu vereinbaren.\nIch halte ein solches Recht dennoch für sinnvoll — vorausgesetzt, es lässt Raum für individuelle Absprachen. Wer Fachkräfte halten will, muss ohnehin Arbeitsbedingungen bieten, die den Feierabend respektieren.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen Kurzvortrag. Sprich zusammenhängend etwa zwei Minuten (höchstens 150 Sekunden).',
      aufgabe: 'Halte einen strukturierten Kurzvortrag zum Thema „Vereinbarkeit von Familie und Beruf — wer ist in der Pflicht?“. Gliedere ihn in die vier Bausteine Einstieg, Situation in deinem Heimatland, Abwägung und Fazit und verwende mindestens vier Begriffe aus dem Kernwortschatz der Lektion.',
      punkte: [
        'Einstieg: Führe zum Thema hin und erkläre, warum es so viele Beschäftigte betrifft.',
        'Heimatland: Beschreibe kurz, wie Eltern dort Familie und Beruf vereinbaren.',
        'Abwägung: Stelle gegenüber, was Betriebe und was der Staat beitragen können — und wo die Grenzen liegen.',
        'Fazit: Formuliere eine begründete eigene Position.',
      ],
      redemittel: ['In meinem Vortrag geht es um die Frage, …', 'In meinem Heimatland …', 'Auf der einen Seite …, auf der anderen Seite …', 'Man sollte allerdings nicht übersehen, dass …', 'Alles in allem halte ich … für …'],
      maxSekunden: 150,
      beispielLoesung: 'In meinem Vortrag geht es um die Frage, wer eigentlich dafür verantwortlich ist, dass sich Familie und Beruf vereinbaren lassen. Das Thema betrifft Millionen von Beschäftigten — spätestens dann, wenn das erste Kind da ist und zwei volle Stellen plötzlich nicht mehr in einen Tag passen.\nIn meinem Heimatland lösen viele Familien das Problem privat: Die Großeltern springen ein, weil Betreuungsplätze knapp sind und die Arbeitstage oft bis in den Abend dauern. Elternzeit nehmen fast nur die Mütter, und zwar meist kurz.\nAuf der einen Seite können die Betriebe viel tun. Flexible Arbeitszeiten und Tage im Homeoffice ersparen das Pendeln und verschaffen Eltern Luft. Im Wettbewerb um Fachkräfte sind solche Arbeitsbedingungen ohnehin ein starkes Argument. Man sollte allerdings nicht übersehen, dass Flexibilität auch Entgrenzung bedeuten kann: Wer abends am Küchentisch weiterarbeitet, ist einer doppelten Belastung ausgesetzt.\nAuf der anderen Seite steht der Staat. Ohne verlässliche Ganztagsbetreuung nützt das schönste Arbeitszeitmodell wenig. Und solange vor allem Mütter in Teilzeit wechseln, bleibt die gerechte Aufteilung der Sorgearbeit ein Versprechen.\nAlles in allem halte ich die Vereinbarkeit für eine gemeinsame Aufgabe. Der Staat muss die Betreuung sichern, die Betriebe müssen Spielräume bieten — aber entscheidend ist am Ende, dass sich Väter und Mütter die Arbeit zu Hause wirklich teilen. Sonst bleibt Vereinbarkeit ein Frauenthema, und genau das sollte sie nicht sein. Vielen Dank.',
    },
  ],
}
