// Übungsheft C1 — Lektion 17: Lesen: Der Lückentext (Teil 2)
export default {
  lektion: 17,
  titel: 'Übungsheft — Der Lückentext',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Arbeite wie im Lückentext der Prüfung: Bestimme zuerst Wortart, Kasus und Verbstellung, prüfe dann Logik und Kollokation und entscheide dich für die einzige normgerechte Lösung.',
      items: [
        {
          typ: 'luecke',
          text: '{1} die Wortliste zwölf Wörter enthält, kommen für eine einzelne Lücke meist nur zwei oder drei infrage. {2} lohnt es sich, vor jeder inhaltlichen Überlegung die Wortart zu bestimmen.',
          bank: ['Obwohl', 'Deshalb', 'Denn', 'Trotzdem', 'Weil'],
          loesungen: { 1: 'Obwohl', 2: 'Deshalb' },
        },
        {
          typ: 'luecke',
          text: '{1} des knappen Zeitbudgets solltest du an keiner Lücke hängen bleiben. {2} gezieltes Filtern lassen sich die meisten Kandidaten rasch ausschließen.',
          bank: ['Angesichts', 'Durch', 'Trotz', 'Mit'],
          loesungen: { 1: 'Angesichts', 2: 'Durch' },
        },
        {
          typ: 'luecke',
          text: 'Wer die {1} eines Verbs kennt, weiß sofort, welche Präposition folgen muss. Steht nach der Lücke ein Nomen, verrät sein {2}, welche Präpositionen überhaupt infrage kommen.',
          bank: ['Rektion', 'Kasus', 'Wortart', 'Verbstellung'],
          loesungen: { 1: 'Rektion', 2: 'Kasus' },
        },
        {
          typ: 'mc',
          frage: 'Weil die Nachfrage deutlich zurückgegangen ist, wurde das Angebot gekürzt. → Aufgrund des deutlichen ___ der Nachfrage wurde das Angebot gekürzt.',
          optionen: ['Rückgangs', 'Rückgang', 'Rückgehen'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Beide Kandidaten klingen ähnlich; ___ passt nur einer von ihnen grammatisch in die Lücke.',
          optionen: ['obgleich', 'gleichwohl', 'wohingegen'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Mehrere Fachleute haben erhebliche Bedenken gegen das Vorhaben ___.',
          optionen: ['gesagt', 'gemacht', 'geäußert'],
          loesung: 2,
        },
        {
          typ: 'korrektur',
          optionen: ['Die Maßnahme hat erheblich für die Senkung der Kosten beigetragen.', 'Die Maßnahme hat erheblich zur Senkung der Kosten beigetragen.'],
          loesung: 1,
          warum: 'La rección es **zu etwas beitragen** (*zur Senkung*); *für* es calco de «contribuir para».',
        },
        {
          typ: 'korrektur',
          optionen: ['Obwohl die Studie klein ist, liefert sie wertvolle Hinweise.', 'Trotzdem die Studie klein ist, liefert sie wertvolle Hinweise.'],
          loesung: 0,
          warum: 'En la norma escrita **trotzdem** es un adverbio (el verbo va justo detrás: *Trotzdem liefert sie …*); como subjunción solo aparece en registro coloquial. Para una subordinada con verbo final se necesita **obwohl**.',
        },
        {
          typ: 'zuordnen',
          links: ['Kritik', 'Maßnahmen', 'Konsequenzen', 'eine Rolle', 'zur Verfügung', 'eine Studie'],
          rechts: ['üben', 'ergreifen', 'ziehen', 'spielen', 'stehen', 'durchführen'],
          loesung: {
            'Kritik': 'üben',
            'Maßnahmen': 'ergreifen',
            'Konsequenzen': 'ziehen',
            'eine Rolle': 'spielen',
            'zur Verfügung': 'stehen',
            'eine Studie': 'durchführen',
          },
        },
        {
          typ: 'satzbau',
          woerter: ['kommen', 'Welche', 'für', 'Wörter', 'diese', 'Lücke', 'infrage'],
          loesung: 'Welche Wörter kommen für diese Lücke infrage?',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die Rezension. Entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist. Unterscheide dabei zwischen der Position der Buchautorin und der Einschätzung der Rezension.',
      textTitel: 'Rezension: „Zwischen den Zeilen“ — ein Ratgeber zum Lückentext',
      text: 'Wer sich auf eine Sprachprüfung vorbereitet, stößt auf eine Flut von Ratgebern. Henrike Aldags schmaler Band „Zwischen den Zeilen“ hebt sich wohltuend davon ab, weil er sich auf eine einzige Aufgabe konzentriert: den Lückentext. Aldag, die viele Jahre als Prüferin tätig war, vertritt eine klare These: Der Lückentext sei weniger ein Lese- als ein Grammatiktest. Wer vor jeder inhaltlichen Überlegung Wortart, Kasus und Verbstellung bestimme, könne die meisten Kandidaten der Wortliste in Sekunden ausschließen. Überzeugend sind vor allem die Kapitel zu Konnektoren und Präpositionen, in denen die Autorin zahlreiche Beispiele Schritt für Schritt auflöst.\nWeniger gelungen ist der Abschnitt über Kollokationen. Hier beschränkt sich Aldag auf lange Listen, ohne zu zeigen, wie man feste Verbindungen im Zusammenhang erkennt — gerade dort, wo die grammatische Analyse an ihre Grenzen stößt, hätte man sich mehr Anleitung gewünscht. Auch der Anspruch, jeder Lückentext lasse sich in acht Minuten lösen, dürfte manche Leser eher entmutigen als anspornen. Dennoch: Wer das Buch gründlich durcharbeitet, wird dem Lückentext in der Prüfung mit deutlich mehr Gelassenheit begegnen.',
      items: [
        { typ: 'rf', aussage: 'Die Buchautorin hält den Lückentext in erster Linie für eine Prüfung des Leseverstehens.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was bemängelt die Rezension am Abschnitt über Kollokationen?',
          optionen: ['Er enthält zu wenige Beispiele für feste Verbindungen.', 'Er zeigt nicht, wie man Kollokationen im Kontext erkennt.', 'Er widerspricht den Kapiteln über Präpositionen.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Wie beurteilt die Rezension die Zeitvorgabe von acht Minuten?',
          optionen: ['Sie sei für geübte Leser zu großzügig bemessen.', 'Sie entspreche genau den Vorgaben der Prüfung.', 'Sie könne auf manche Leser eher demotivierend wirken.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Henrike Aldag verfügt über langjährige Erfahrung als Prüferin.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst einen Ausschnitt aus einem wissenschaftlichen Vortrag. Entscheide, welche Antwort dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Meine Damen und Herren, im zweiten Teil meines Vortrags möchte ich Ihnen zeigen, warum der Lückentext als Prüfungsform so beliebt ist. Die Idee ist älter, als viele annehmen. Sie stammt nicht aus dem Sprachunterricht, sondern aus der Zeitungsforschung. Ursprünglich wollte man damit messen, wie verständlich ein Artikel für seine Leser ist. Erst später entdeckten Sprachlehrer das Verfahren für sich.\nWas geschieht nun beim Ausfüllen im Kopf? Unsere Arbeitsgruppe hat dazu sechzig Studierende untersucht, die Deutsch als Fremdsprache lernen. Die eine Hälfte durfte den gesamten Text vorab lesen, die andere musste sofort mit der ersten Lücke beginnen. Das Ergebnis war eindeutig. Die erste Gruppe löste im Durchschnitt siebzehn von zwanzig Lücken richtig, die zweite lediglich zwölf. Bemerkenswert ist, dass beide Gruppen fast gleich viel Zeit benötigten. Das vorherige Lesen kostet also keine Zeit, es spart sie an anderer Stelle wieder ein.\nBesonders aufschlussreich waren die Fehler. Die meisten betrafen nicht etwa seltene Fachwörter, sondern unscheinbare Präpositionen und Konnektoren. Offenbar verlassen sich viele Lernende hier auf ihr Gefühl, statt den Satzbau zu prüfen. Im nächsten Abschnitt werde ich darauf eingehen, welche Folgen das für den Unterricht haben sollte.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Wozu diente der Lückentext dem Vortrag zufolge ursprünglich?',
          optionen: ['zur Messung der Verständlichkeit von Zeitungsartikeln', 'zur Einstufung von Sprachlernenden in Kursniveaus', 'zur Überprüfung von Grammatikkenntnissen im Unterricht'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Welches Ergebnis erzielte die Gruppe, die sofort mit der ersten Lücke beginnen musste?',
          optionen: ['durchschnittlich siebzehn richtige Lösungen', 'durchschnittlich zwölf richtige Lösungen', 'durchschnittlich zwanzig richtige Lösungen'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Die Gruppe, die den Text vorab lesen durfte, brauchte für die Aufgabe insgesamt deutlich länger als die andere.', loesung: false },
        { typ: 'rf', aussage: 'Die häufigsten Fehler werden im Vortrag darauf zurückgeführt, dass viele Lernende nach Gefühl entscheiden, statt den Satzbau zu prüfen.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine formelle E-Mail (mindestens 80 Wörter). Achte auf eine angemessene Anrede und Grußformel, einen sachlichen Ton und eine klare Gliederung deines Anliegens.',
      aufgabe: 'Du besuchst an deiner Sprachschule einen Vorbereitungskurs für das Zertifikat C1. Schreibe an die Kursleiterin, Frau Dr. Okonkwo, und regst an, den Lückentext im Kurs gezielter zu trainieren.',
      punkte: [
        'Schildere, welche Schwierigkeiten du und andere Teilnehmende beim Lückentext haben.',
        'Unterbreite einen konkreten Vorschlag, wie dieser Prüfungsteil im Unterricht geübt werden könnte.',
        'Bitte um eine Rückmeldung und schließe mit einer angemessenen Grußformel.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Sehr geehrte Frau Dr. Okonkwo,\nzunächst möchte ich mich für Ihren abwechslungsreichen Unterricht bedanken. Mit Blick auf die Prüfung erlaube ich mir jedoch eine Anregung. Wie mehreren anderen Teilnehmenden bereitet mir der Lückentext nach wie vor große Schwierigkeiten: Wir verlieren zu viel Zeit, weil wir die Lücken intuitiv statt systematisch füllen, und scheitern häufig an der Rektion von Verben und an festen Kollokationen.\nDaher würde ich vorschlagen, jede Woche einen Lückentext unter Prüfungsbedingungen zu bearbeiten und anschließend gemeinsam zu besprechen, welche Indizien — Kasus, Verbstellung, Bezugswort — zur Lösung geführt haben. Ergänzend könnten wir eine Liste der wichtigsten Kollokationen anlegen.\nÜber eine kurze Rückmeldung, ob sich dieser Vorschlag umsetzen ließe, würde ich mich sehr freuen.\nMit freundlichen Grüßen\nLucía Fernández',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Halte einen kurzen Erklärvortrag (gut zwei Minuten). Sprich frei, gliedere deine Schritte hörbar (zunächst, anschließend, erst dann, zum Schluss) und verwende die Fachbegriffe der Lektion.',
      aufgabe: 'In deinem Vorbereitungskurs auf das Zertifikat C1 stellt jede Woche jemand eine Arbeitstechnik vor. Diesmal bist du an der Reihe: Erkläre den anderen Teilnehmenden in einem frei gesprochenen, zusammenhängenden Kurzvortrag von gut zwei Minuten, wie man den Lückentext systematisch löst. Gliedere deine Schritte hörbar (zunächst, anschließend, erst dann, zum Schluss) und verwende die einschlägigen Fachbegriffe, etwa Wortart, Kasus, Verbstellung, Konnektor und Kollokation.',
      punkte: [
        'Erkläre, was dieser Prüfungsteil eigentlich testet.',
        'Beschreibe dein Vorgehen Schritt für Schritt, von der ersten Lektüre bis zur Schlusskontrolle.',
        'Warne vor einer typischen Falle und veranschauliche sie an einem Beispiel.',
      ],
      redemittel: ['Zunächst einmal sollte man wissen, dass …', 'Bevor ich an die Bedeutung denke, …', 'Auf diese Weise bleiben nur noch … übrig.', 'Eine typische Falle besteht darin, dass …', 'Zum Schluss empfiehlt es sich, …'],
      maxSekunden: 135,
      beispielLoesung: 'Ich möchte euch heute zeigen, wie ich beim Lückentext vorgehe. Zunächst einmal sollte man wissen, was dieser Teil überhaupt testet. Es geht weniger um Leseverstehen als um Grammatik: um Konnektoren, Präpositionen und feste Kollokationen.\nDeshalb gehe ich in vier Schritten vor. Zuerst lese ich den ganzen Text einmal durch, ohne etwas einzusetzen. Das dauert höchstens anderthalb Minuten, und danach weiß ich, worum es geht. Anschließend bestimme ich bei jeder Lücke die Wortart: Fehlt ein Verb, eine Präposition, ein Konnektor? Ich achte auf den Kasus des folgenden Nomens und auf die Verbstellung. Erst dann schaue ich in die Wortliste und streiche alles, was grammatisch nicht infrage kommt. Auf diese Weise bleiben meistens nur zwei oder drei Wörter übrig, und zwischen denen entscheide ich nach dem Zusammenhang. Die sicheren Lücken fülle ich zuerst, denn mit jedem eingesetzten Wort wird die Liste kürzer.\nEine typische Falle besteht darin, dass zwei Wörter fast dasselbe bedeuten, zum Beispiel „obwohl“ und „trotzdem“. Inhaltlich passen oft beide. Steht das Verb aber am Satzende, kommt nur „obwohl“ infrage. Wer hier nach Gefühl entscheidet, verliert den Punkt.\nZum Schluss empfiehlt es sich, den vollständigen Text noch einmal flüssig zu lesen. Wenn ein Satz holpert, stimmt meistens etwas nicht. Mit dieser Methode komme ich gut mit zehn Minuten aus.',
    },
  ],
}
