// Übungsheft C1 — Lektion 39: Prüfungssimulation 1 + Korrektur
export default {
  lektion: 39,
  titel: 'Übungsheft — Generalprobe 1: Gesamtwiederholung',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Gesamtwiederholung des C1-Kurses: Nominalstil, Präpositionen mit Genitiv, Konnektoren, indirekte Rede, subjektive Modalverben, Partizipialattribute, Passiversatzformen, Relativsätze und Funktionsverbgefüge. Wähle jeweils die Lösung, die grammatisch korrekt ist und dem Kontext entspricht.',
      items: [
        {
          typ: 'luecke',
          text: 'Nach dem erfolgreichen {1} der Verhandlungen und eingehender {2} aller Einwände wurde der Vertrag schließlich unterzeichnet.',
          bank: ['Abschluss', 'Prüfung', 'Schließung'],
          loesungen: { 1: 'Abschluss', 2: 'Prüfung' },
        },
        {
          typ: 'luecke',
          text: '{1} aller Bedenken hält die Stadt an ihren Plänen fest: {2} eines Neubaus soll die alte Brücke nun saniert werden.',
          bank: ['Ungeachtet', 'Anstelle', 'Infolge', 'Mittels'],
          loesungen: { 1: 'Ungeachtet', 2: 'Anstelle' },
        },
        {
          typ: 'luecke',
          text: 'Die geplante Reform ist {1} kostspielig, {2} auch sozial unausgewogen.',
          bank: ['nicht nur', 'sondern', 'weder', 'doch'],
          loesungen: { 1: 'nicht nur', 2: 'sondern' },
        },
        {
          typ: 'mc',
          frage: 'In welchem Satz ist die Ersatzform mit Konjunktiv II in der indirekten Rede normgerecht erforderlich?',
          optionen: ['Der Autor behauptet, er hätte neue Daten.', 'Die Autorin behauptet, sie hätte neue Daten.', 'Die Forschenden behaupten, sie hätten neue Daten.'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Der Minister ___ von den Zahlungen gewusst haben — so berichten jedenfalls mehrere Zeitungen übereinstimmend.',
          optionen: ['soll', 'will', 'muss'],
          loesung: 0,
        },
        {
          typ: 'luecke',
          text: 'Die von der Regierung im vergangenen Jahr {1} Maßnahmen haben die {2} Erwartungen bei Weitem nicht erfüllt.',
          bank: ['beschlossenen', 'beschließenden', 'hochgesteckten', 'hochsteckenden'],
          loesungen: { 1: 'beschlossenen', 2: 'hochgesteckten' },
        },
        {
          typ: 'korrektur',
          optionen: ['Die Frage lässt sich nicht ohne Weiteres beantwortet werden.', 'Die Frage lässt sich nicht ohne Weiteres beantworten.'],
          loesung: 1,
          warum: '*sich lassen* + infinitivo activo ya tiene valor pasivo-modal (= *kann beantwortet werden*); no se combina con *werden*.',
        },
        {
          typ: 'luecke',
          text: 'Die Autorin, {1} jüngster Roman in mehrere Sprachen übersetzt wurde, liest morgen im Literaturhaus, {2} Programm diesmal besonders vielfältig ist.',
          bank: ['deren', 'dessen', 'derer', 'die'],
          loesungen: { 1: 'deren', 2: 'dessen' },
        },
        {
          typ: 'zuordnen',
          links: ['in Frage stellen', 'zur Verfügung stellen', 'in Kauf nehmen', 'zum Ausdruck bringen', 'in Erwägung ziehen'],
          rechts: ['bezweifeln', 'bereitstellen', 'hinnehmen', 'ausdrücken', 'erwägen'],
          loesung: {
            'in Frage stellen': 'bezweifeln',
            'zur Verfügung stellen': 'bereitstellen',
            'in Kauf nehmen': 'hinnehmen',
            'zum Ausdruck bringen': 'ausdrücken',
            'in Erwägung ziehen': 'erwägen',
          },
        },
        {
          typ: 'satzbau',
          woerter: ['lohnt', 'teuer', 'Zwar', 'sich', 'er', 'doch', 'Plan', 'ist', 'der'],
          loesung: 'Zwar ist der Plan teuer, doch er lohnt sich.',
          alt: ['Zwar ist der Plan teuer, doch lohnt er sich.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Artikelauszug und entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist.',
      textTitel: 'Artikelauszug: Weniger Stunden, gleiche Leistung?',
      text: 'Seit einem Jahr erprobt die Verwaltung einer mittelgroßen Stadt in Nordhessen die Viertagewoche: Bei vollem Lohn arbeiten rund 150 Beschäftigte 36 statt 40 Stunden, verteilt auf vier Tage. Die nun vorgelegte Zwischenbilanz fällt überwiegend positiv aus. Die Zahl der Krankheitstage sei deutlich zurückgegangen, heißt es im Bericht, und offene Stellen ließen sich schneller besetzen als zuvor. Die Bürgerinnen und Bürger hätten von den verlängerten Öffnungszeiten an den verbleibenden Tagen sogar profitiert.\nGanz so eindeutig, wie die Stadtspitze es darstellt, ist das Ergebnis allerdings nicht. Da die Teilnahme freiwillig war, dürften sich vor allem besonders motivierte Beschäftigte gemeldet haben — ein Umstand, der die Aussagekraft der Zahlen erheblich schmälert. Zudem räumt der Bericht ein, dass in zwei Abteilungen Überstunden angefallen sind, die in der Bilanz nicht auftauchen.\nDie Personalvertretung fordert dennoch, das Modell auf die gesamte Verwaltung auszuweiten. Der Kämmerer mahnt hingegen zur Vorsicht: Bevor man eine solche Entscheidung treffe, müsse eine unabhängige Auswertung vorliegen, die auch die Kosten für zusätzliches Personal berücksichtige.',
      items: [
        { typ: 'rf', aussage: 'Die Beschäftigten im Modellversuch verdienen weniger als vor dessen Beginn.', loesung: false },
        {
          typ: 'mc',
          frage: 'Warum ist die Aussagekraft der Zwischenbilanz dem Artikel zufolge eingeschränkt?',
          optionen: ['Weil der Versuch zu kurz gelaufen ist, um verlässliche Aussagen über Krankheitstage zu treffen.', 'Weil die Bilanz nicht von der Stadtspitze, sondern von der Personalvertretung erstellt wurde.', 'Weil sich vermutlich vor allem überdurchschnittlich motivierte Beschäftigte freiwillig gemeldet haben.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Laut Bericht sind in einigen Abteilungen Überstunden angefallen, die in der Bilanz nicht berücksichtigt wurden.', loesung: true },
        {
          typ: 'mc',
          frage: 'Welche Haltung nimmt der Kämmerer ein?',
          optionen: ['Er lehnt die Viertagewoche grundsätzlich ab, weil sie zu teuer sei.', 'Er will vor einer Ausweitung eine unabhängige Auswertung abwarten, die auch Personalkosten einbezieht.', 'Er befürwortet eine sofortige Ausweitung, sofern die Beschäftigten zustimmen.'],
          loesung: 1,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Prüfungssimulation: Du hörst einen Ausschnitt aus einem wissenschaftlichen Vortrag. Lies zuerst die Aufgaben, höre dann den Vortrag und entscheide, welche Antwort dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Meine Damen und Herren, mein Name ist Katharina Wolf. Ich stelle Ihnen heute eine Untersuchung vor, die unser Institut für Stadtklimaforschung in den vergangenen drei Sommern in Mannheim durchgeführt hat. Wir wollten wissen, wie stark Straßenbäume ihre Umgebung abkühlen.\nZunächst zum Vorgehen. Gemessen haben wir in sechzehn Straßen, von denen die Hälfte dicht mit Bäumen bestanden ist, während die übrigen nahezu kahl sind. Erfasst wurde nicht nur die Temperatur der Luft, sondern auch die der Oberflächen.\nDas Ergebnis hat uns selbst überrascht. An heißen Nachmittagen war die Luft unter den Bäumen lediglich um anderthalb Grad kühler, also weit weniger, als gemeinhin behauptet wird. Der Asphalt hingegen heizte sich im Schatten um bis zu achtzehn Grad weniger auf. Wie Passanten die Hitze empfinden, hängt demnach weniger von der Luft ab als von der Strahlung, vor der das Blätterdach sie schützt. Nachts kehrte sich das Bild allerdings teilweise um, denn unter dichten Kronen entweicht die Wärme langsamer, sodass es in engen Straßen sogar geringfügig wärmer blieb.\nWas folgt daraus? Unsere Daten legen nahe, dass Bäume vor allem tagsüber entlasten. Dass sie ein überhitztes Viertel insgesamt abkühlen, ist damit keineswegs belegt. Zudem spendet ein junger Baum erst nach etwa fünfzehn Jahren nennenswert Schatten. Ich plädiere deshalb dafür, alte Bestände zu erhalten, statt sich allein auf Neupflanzungen zu verlassen.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Was ergaben die Messungen an heißen Nachmittagen?',
          optionen: [
            'Die Luft war unter den Bäumen um bis zu achtzehn Grad kühler als in den kahlen Straßen.',
            'Weder bei der Luft noch beim Asphalt zeigte sich ein nennenswerter Unterschied.',
            'Die Luft war unter den Bäumen nur wenig kühler, der Asphalt heizte sich dort jedoch erheblich weniger auf.',
          ],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Nach Darstellung der Referentin hängt es in erster Linie von der Lufttemperatur ab, wie stark Passanten die Hitze empfinden.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was zeigte sich bei den nächtlichen Messungen?',
          optionen: [
            'Die baumbestandenen Straßen kühlten nachts besonders rasch ab.',
            'In engen Straßen mit dichten Baumkronen blieb es etwas wärmer.',
            'Zwischen den Straßen ließ sich nachts kein Unterschied mehr messen.',
          ],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Die Referentin begründet ihr Plädoyer für den Erhalt alter Bäume unter anderem damit, dass neu gepflanzte Bäume erst nach vielen Jahren ausreichend Schatten spenden.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine Textzusammenfassung mit Kommentar (mindestens 80 Wörter). Gib die Positionen des Artikels in indirekter Rede wieder und trenne Zusammenfassung und eigene Meinung deutlich voneinander.',
      aufgabe: 'Fasse den Artikelauszug „Weniger Stunden, gleiche Leistung?“ aus Teil 2 zusammen und nimm anschließend Stellung zur Frage, ob die Viertagewoche auf die gesamte Verwaltung ausgeweitet werden sollte.',
      punkte: [
        'Gib die wichtigsten Ergebnisse der Zwischenbilanz sachlich wieder.',
        'Stelle die Einwände und die Positionen von Personalvertretung und Kämmerer dar.',
        'Beziehe begründet Stellung und formuliere eine Empfehlung.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Der Artikel berichtet über einen einjährigen Modellversuch zur Viertagewoche in einer Stadtverwaltung in Nordhessen. Laut Zwischenbilanz sei die Zahl der Krankheitstage deutlich gesunken, offene Stellen ließen sich schneller besetzen, und auch die Bürger hätten von längeren Öffnungszeiten profitiert. Der Autor gibt jedoch zu bedenken, dass sich vermutlich vor allem motivierte Beschäftigte freiwillig gemeldet hätten; zudem seien Überstunden in der Bilanz nicht erfasst. Während die Personalvertretung eine Ausweitung fordere, verlange der Kämmerer zunächst eine unabhängige Auswertung.\nMeines Erachtens ist die Position des Kämmerers überzeugender. Die Ergebnisse sind zwar ermutigend, doch solange die Stichprobe verzerrt ist, lässt sich kaum abschätzen, wie das Modell in allen Abteilungen wirken würde. Ich plädiere daher für eine zweite, wissenschaftlich begleitete Testphase, bevor eine endgültige Entscheidung getroffen wird.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Prüfungssimulation: Halte einen strukturierten Vortrag von etwa zweieinhalb Minuten. Notiere dir vorher höchstens fünf Minuten lang Stichpunkte und sprich dann frei und am Stück, ohne abzulesen.',
      aufgabe: 'Thema: „Sollten junge Menschen nach der Schule ein soziales Pflichtjahr leisten?“ Halte dazu einen Vortrag mit Einleitung, Hauptteil und Schluss: Führe zum Thema hin und nenne deine These, begründe sie mit zwei Argumenten, setze dich mit einem Gegenargument auseinander und schließe mit einem Fazit.',
      punkte: [
        'Hinführung zum Thema und deine These',
        'zwei Argumente, jeweils mit Beispiel oder Begründung',
        'ein Gegenargument und deine Entgegnung',
        'Fazit mit Ausblick',
      ],
      redemittel: [
        'In meinem Vortrag möchte ich zeigen, warum …',
        'Dafür spricht zunächst …',
        'Hinzu kommt …',
        'Kritiker wenden ein, … Dieser Einwand ist berechtigt, er spricht jedoch eher für … als gegen …',
        'Abschließend lässt sich festhalten: …',
      ],
      maxSekunden: 150,
      beispielLoesung: 'In Pflegeheimen, Kitas und Rettungsdiensten fehlt überall Personal. Vor diesem Hintergrund wird immer wieder gefordert, alle jungen Menschen sollten nach der Schule ein soziales Pflichtjahr leisten. In meinem Vortrag möchte ich zeigen, warum ich diese Idee im Kern für richtig halte — allerdings nur unter bestimmten Bedingungen.\nDafür spricht zunächst der gesellschaftliche Zusammenhalt. Wer ein Jahr lang in einem Pflegeheim oder in einer Werkstatt für Menschen mit Behinderung mitarbeitet, begegnet Menschen, mit denen er sonst nie in Berührung käme. Solche Erfahrungen bauen Vorurteile ab, und zwar nachhaltiger als jeder Unterricht.\nHinzu kommt der persönliche Gewinn. Viele wissen mit achtzehn noch nicht, was sie beruflich machen wollen. Ein Jahr in der Praxis verschafft Orientierung, und nicht wenige entdecken dabei einen Beruf, den sie vorher nie in Betracht gezogen hätten.\nKritiker wenden ein, ein Pflichtjahr sei ein massiver Eingriff in die persönliche Freiheit, und unmotivierte Helfer seien für die Einrichtungen eher eine Last als eine Hilfe. Dieser Einwand ist berechtigt. Er spricht meines Erachtens jedoch weniger gegen den Dienst selbst als für eine kluge Ausgestaltung: Die jungen Leute müssten ihren Einsatzbereich frei wählen können, vom Umweltschutz bis zum Sportverein, und sie müssten angemessen bezahlt und betreut werden.\nAbschließend lässt sich festhalten: Ein Pflichtjahr löst den Personalmangel sicher nicht, und das sollte auch nicht sein Zweck sein. Es kann aber dazu beitragen, dass sich Menschen unterschiedlicher Herkunft und verschiedener Generationen wieder begegnen, und deshalb halte ich es, klug ausgestaltet, für einen Gewinn. Entscheidend wird sein, ob die Politik bereit ist, die nötigen Mittel dafür bereitzustellen.',
    },
  ],
}
