// Übungsheft C1 — Lektion 16: Modul Lesen — Überblick
export default {
  lektion: 16,
  titel: 'Übungsheft — Modul Lesen im Überblick',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Bearbeite die Aufgaben rund um die Sprache der Aufgabenstellungen. Achte auf Rektion, feste Verbindungen und Konnektoren und entscheide dich jeweils für die einzige normgerechte Lösung.',
      items: [
        {
          typ: 'luecke',
          text: 'Jede Antwort muss sich mit einer Textstelle {1} lassen. Wer eine Information nicht dem Text {2}, sondern seinem Weltwissen, fällt leicht auf einen Distraktor {3}.',
          bank: ['belegen', 'entnimmt', 'herein', 'zutrifft', 'an'],
          loesungen: { 1: 'belegen', 2: 'entnimmt', 3: 'herein' },
        },
        {
          typ: 'luecke',
          text: '{1} der knappen Bearbeitungszeit empfiehlt es sich, schwierige Aufgaben zunächst nur zu markieren. {2} gezielten Scannings lassen sich Zahlen und Namen dagegen in Sekunden auffinden.',
          bank: ['Angesichts', 'Mittels', 'Trotz'],
          loesungen: { 1: 'Angesichts', 2: 'Mittels' },
        },
        {
          typ: 'luecke',
          text: 'Die Option wiederholt {1} Wörter aus dem Text, {2} verdreht sie deren Aussage. Da es keine Minuspunkte gibt, lohnt es sich, am Ende jede offene Aufgabe {3}.',
          bank: ['zwar', 'doch', 'anzukreuzen', 'ankreuzen', 'weder'],
          loesungen: { 1: 'zwar', 2: 'doch', 3: 'anzukreuzen' },
        },
        {
          typ: 'mc',
          frage: 'Markiere die Textstelle, ___ sich deine Antwort stützt.',
          optionen: ['auf die', 'auf der', 'an die'],
          loesung: 0,
        },
        {
          typ: 'mc',
          frage: 'Welche der folgenden Aussagen ___ auf die Autorin zu?',
          optionen: ['stimmt', 'passt', 'trifft'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Im Text heißt es: „Die Kritik ist nicht unberechtigt.“ Welche Aussage gibt diese Stelle sinngemäß wieder?',
          optionen: ['Die Kritik ist völlig unbegründet.', 'Die Kritik hat durchaus ihre Berechtigung.', 'Die Kritik ist rechtlich nicht zulässig.'],
          loesung: 1,
        },
        {
          typ: 'korrektur',
          optionen: ['Die gewählte Antwort entspricht zum Text.', 'Die gewählte Antwort entspricht dem Text.'],
          loesung: 1,
          warum: '**entsprechen** rige dativo directo, sin preposición: *etwas entspricht dem Text*. El *zum* es calco de «corresponder a».',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich weiß nicht, welche Option zutrifft.', 'Ich weiß nicht, welche Option trifft zu.'],
          loesung: 0,
          warum: 'En la subordinada interrogativa indirecta el verbo va al final y el prefijo separable se une a él: *welche Option **zutrifft***.',
        },
        {
          typ: 'zuordnen',
          links: ['Zahlen und Namen gezielt suchen', 'Thema und Aufbau eines Textes erfassen', 'eine Belegstelle Wort für Wort prüfen', 'eine Aussage mit eigenen Worten wiedergeben', 'die Lösungen auf den Antwortbogen schreiben'],
          rechts: ['scannen', 'überfliegen', 'detailliert lesen', 'paraphrasieren', 'übertragen'],
          loesung: {
            'Zahlen und Namen gezielt suchen': 'scannen',
            'Thema und Aufbau eines Textes erfassen': 'überfliegen',
            'eine Belegstelle Wort für Wort prüfen': 'detailliert lesen',
            'eine Aussage mit eigenen Worten wiedergeben': 'paraphrasieren',
            'die Lösungen auf den Antwortbogen schreiben': 'übertragen',
          },
        },
        {
          typ: 'satzbau',
          woerter: ['folgen', 'fast', 'Die', 'dem', 'immer', 'Aufgaben', 'Textverlauf'],
          loesung: 'Die Aufgaben folgen fast immer dem Textverlauf.',
          alt: ['Die Aufgaben folgen dem Textverlauf fast immer.'],
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Bericht. Entscheide, welche Antwort dem Text entspricht bzw. ob die Aussage richtig oder falsch ist. Stütze dich ausschließlich auf den Text.',
      textTitel: 'Bericht: Wer zuerst die Aufgaben liest, gewinnt Zeit',
      text: 'Ein Forscherteam aus Leipzig hat untersucht, wie Erwachsene in Sprachprüfungen mit längeren Sachtexten umgehen. Mithilfe von Blickbewegungsmessungen wurde erfasst, welche Abschnitte die 120 Teilnehmenden wie lange betrachteten. Das Ergebnis überrascht nur auf den ersten Blick: Wer den Text von Anfang an Wort für Wort las, erzielte im Durchschnitt deutlich weniger Punkte als jene, die zunächst die Aufgaben überflogen und anschließend gezielt nach den entscheidenden Textstellen suchten. Die gründlichen Leser scheiterten dabei meist nicht an der Sprache, sondern an der Zeit: Fast die Hälfte von ihnen konnte die letzten Aufgaben gar nicht mehr bearbeiten.\nStudienleiterin Małgorzata Weiß warnt allerdings davor, daraus ein Patentrezept abzuleiten. Wer nur noch nach Schlüsselwörtern suche, falle umso leichter auf Distraktoren herein, die genau diese Wörter aufgriffen, deren Aussage aber verdrehten. Entscheidend sei der Wechsel der Techniken: erst ein rascher Überblick, dann das genaue Lesen der Belegstelle. Auffällig war zudem, dass Teilnehmende mit geringerem Wortschatz vom strategischen Vorgehen stärker profitierten als sprachlich fortgeschrittene. Strategie, so Weiß, könne fehlende Sprachkenntnisse zwar nicht ersetzen, wohl aber verhindern, dass vorhandene verschenkt würden.',
      items: [
        { typ: 'rf', aussage: 'Die Teilnehmenden, die von Anfang an Wort für Wort lasen, scheiterten vor allem an sprachlichen Schwierigkeiten.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wovor warnt Małgorzata Weiß?',
          optionen: ['davor, Texte in der Prüfung überhaupt noch vollständig zu lesen', 'vor einem Vorgehen, das sich allein auf die Suche nach Schlüsselwörtern stützt', 'vor Aufgaben, die nicht der Reihenfolge des Textes folgen'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Was trifft laut Bericht auf Teilnehmende mit geringerem Wortschatz zu?',
          optionen: ['Sie profitierten vom strategischen Vorgehen stärker als sprachlich Fortgeschrittene.', 'Sie konnten fehlende Sprachkenntnisse durch Strategie vollständig ausgleichen.', 'Sie lasen die Texte häufiger Wort für Wort als die übrigen Teilnehmenden.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Fast die Hälfte der gründlichen Leser kam nicht mehr bis zu den letzten Aufgaben.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst einen Ausschnitt aus einem Podcast zur Prüfungsvorbereitung. Entscheide, welche Antwort dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist. Stütze dich ausschließlich auf das, was die Gesprächspartnerin sagt.',
      audio: {
        transcript: 'Moderator: Willkommen zu unserem Prüfungspodcast. Heute ist Sabine Keller zu Gast, die seit zwölf Jahren Kandidaten auf das Zertifikat C1 vorbereitet. Frau Keller, woran scheitern Ihre Teilnehmenden im Modul Lesen am häufigsten?\nExpertin: Nicht am Wortschatz, wie viele vermuten, sondern an der Uhr. In meinem letzten Kurs habe ich einen Probetest schreiben lassen. Von achtzehn Teilnehmenden haben nur sieben alle vier Teile geschafft.\nModerator: Was raten Sie also?\nExpertin: Einen festen Zeitplan, und zwar schriftlich. Früher habe ich empfohlen, immer mit dem langen ersten Text zu beginnen. Davon bin ich abgekommen. Heute lasse ich jeden zwei Reihenfolgen ausprobieren und dann selbst entscheiden.\nModerator: Und wie gehen Ihre Teilnehmenden mit unbekannten Wörtern um?\nExpertin: Oft zu ängstlich. Eine Teilnehmerin hat mir einmal erzählt, sie habe in der Prüfung fünf Minuten über einem einzigen Fachbegriff gebrütet. Die Aufgabe ließ sich aber ganz ohne dieses Wort lösen. Das hat sie erst zu Hause gemerkt.\nModerator: Wie oft sollte man vor der Prüfung einen kompletten Test üben?\nExpertin: Mindestens dreimal, und immer mit laufender Uhr. Ohne Zeitdruck zu üben, bringt wenig. Viele meiner Teilnehmenden üben lieber einzelne Teile, weil das bequemer ist. Das Zeitgefühl für fünfundsechzig Minuten entsteht so allerdings nicht.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Was ergab der Probetest in Frau Kellers letztem Kurs?',
          optionen: ['Sieben von achtzehn Teilnehmenden bearbeiteten alle vier Teile.', 'Sieben von achtzehn Teilnehmenden wurden nicht rechtzeitig fertig.', 'Die Mehrheit scheiterte an Lücken im Wortschatz.'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Frau Keller rät ihren Teilnehmenden bis heute, grundsätzlich mit dem langen ersten Text zu beginnen.', loesung: false },
        { typ: 'rf', aussage: 'Die Teilnehmerin, von der Frau Keller erzählt, hätte die Aufgabe auch ohne den unbekannten Fachbegriff lösen können.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wie beurteilt Frau Keller das Üben einzelner Prüfungsteile?',
          optionen: ['Es sei sinnvoll, sofern man dabei die Uhr mitlaufen lasse.', 'Es sei bequemer, vermittle aber kein Gefühl für die gesamte Prüfungszeit.', 'Es eigne sich vor allem für Teilnehmende, die noch wenig Übung haben.'],
          loesung: 1,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine Stellungnahme (mindestens 80 Wörter). Gib fremde Positionen sinngemäß wieder, statt sie wörtlich zu übernehmen, und verknüpfe deine Argumente mit passenden Konnektoren.',
      aufgabe: 'In einem Onlineforum zur Prüfungsvorbereitung wird die These diskutiert: „Im Modul Lesen entscheidet die Strategie, nicht der Wortschatz.“ Schreibe einen Forumsbeitrag, in dem du Stellung nimmst.',
      punkte: [
        'Gib die These und ihren Hintergrund kurz mit eigenen Worten wieder.',
        'Wäge Argumente für beide Seiten ab und beziehe dich dabei auf die Ergebnisse des Berichts.',
        'Formuliere eine begründete eigene Position und einen konkreten Rat für Prüfungskandidaten.',
      ],
      minWoerter: 80,
      beispielLoesung: 'In diesem Forum wird behauptet, im Modul Lesen komme es vor allem auf die richtige Strategie an, während der Wortschatz eine untergeordnete Rolle spiele. Für diese These spricht eine Studie aus Leipzig: Teilnehmende, die zunächst die Aufgaben überflogen und dann gezielt nach Belegstellen suchten, schnitten deutlich besser ab als diejenigen, die den Text Wort für Wort lasen. Dennoch halte ich die These in ihrer Zuspitzung für problematisch. Wer eine Belegstelle zwar findet, sie aber sprachlich nicht versteht, fällt trotz aller Technik auf Distraktoren herein. Meiner Ansicht nach ergänzen sich beide Faktoren: Strategie verhindert, dass vorhandene Kenntnisse verschenkt werden, ersetzt sie aber nicht. Prüfungskandidaten würde ich daher raten, ihren Wortschatz kontinuierlich auszubauen und zugleich jeden Übungstest mit laufender Uhr zu bearbeiten.',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Sprich einen Diskussionsbeitrag (etwa zweieinhalb Minuten). Beziehe klar Position, stütze sie mit Argumenten und setze dich mit mindestens einem Gegenargument auseinander.',
      aufgabe: 'In einer Diskussionsrunde wird die These vertreten: „Am Bildschirm wird nur noch überflogen — wer gründlich lesen will, braucht Papier.“ Nimm dazu in einem zusammenhängenden Diskussionsbeitrag von etwa zweieinhalb Minuten Stellung: Gib die These sinngemäß wieder, beziehe klar Position, stütze sie mit Argumenten, setze dich mit mindestens einem Gegenargument auseinander und schließe mit einem Fazit.',
      punkte: [
        'Gib die These sinngemäß wieder und nenne deine Position.',
        'Begründe deine Position mit zwei Argumenten oder Beispielen.',
        'Greife ein Gegenargument auf und entkräfte es.',
        'Schließe mit einem knappen Fazit.',
      ],
      redemittel: ['Die These lautet sinngemäß, dass …', 'Dem kann ich nur teilweise zustimmen.', 'Entscheidend ist meines Erachtens nicht …, sondern …', 'Nun könnte man einwenden, dass …', 'Unterm Strich …'],
      maxSekunden: 150,
      beispielLoesung: 'Die These lautet sinngemäß, dass man am Bildschirm Texte nur noch überfliegt und gründliches Lesen allein auf Papier möglich ist. Dem kann ich nur teilweise zustimmen.\nRichtig ist, dass der Bildschirm zum schnellen Lesen verführt. Wer im Netz unterwegs ist, sucht meist gezielt nach einer Information, findet sie und klickt weiter. Dazu kommen Nachrichten und Werbung, die ständig ablenken. Das kenne ich von mir selbst: Einen langen Artikel lese ich am Handy selten bis zum Ende.\nEntscheidend ist meines Erachtens aber nicht das Medium, sondern die Art, wie wir damit umgehen. Zum einen kommt es auf den Zweck an. Wenn ich nur wissen will, wann ein Zug fährt, wäre gründliches Lesen schlicht Zeitverschwendung. Überfliegen ist also kein Mangel, sondern eine Technik, die man beherrschen muss. Zum anderen lässt sich auch am Bildschirm konzentriert lesen, wenn man die Bedingungen dafür schafft: Benachrichtigungen ausschalten, den Text vergrößern, wichtige Stellen markieren.\nNun könnte man einwenden, dass man sich an Gedrucktes besser erinnert. Das mag stimmen, betrifft aber vor allem Menschen, die das Lesen auf Papier gelernt haben. Wer von klein auf digital liest und es geübt hat, dürfte diesen Nachteil kaum haben.\nUnterm Strich brauchen wir also nicht unbedingt Papier, sondern die Fähigkeit, bewusst zwischen schnellem und genauem Lesen zu wechseln. Und die lässt sich auf jedem Medium trainieren.',
    },
  ],
}
