// Übungsheft C1 — Lektion 01: Das Zertifikat C1 im Überblick
export default {
  lektion: 1,
  titel: 'Übungsheft — Das Zertifikat C1 im Überblick',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Wähle jeweils die Lösung, die grammatisch korrekt ist und dem Register der Prüfungssprache entspricht. Achte besonders auf feste Verbindungen und Präpositionen.',
      items: [
        {
          typ: 'luecke',
          text: 'Selin hat im Mai alle vier Module {1} und drei davon auf Anhieb {2}.',
          bank: ['abgelegt', 'bestanden', 'präsentiert', 'aufgenommen'],
          loesungen: { 1: 'abgelegt', 2: 'bestanden' },
        },
        {
          typ: 'mc',
          frage: 'Bei Fragen zur Zulassung wendest du dich am besten direkt ___ ein Prüfungszentrum.',
          optionen: ['bei', 'an', 'zu'],
          loesung: 1,
        },
        {
          typ: 'zuordnen',
          links: ['einen Vortrag', 'zu einer These Stellung', 'eine Prüfung', 'eine Frist', 'Punkte'],
          rechts: ['halten', 'nehmen', 'ablegen', 'einhalten', 'erzielen'],
          loesung: {
            'einen Vortrag': 'halten',
            'zu einer These Stellung': 'nehmen',
            'eine Prüfung': 'ablegen',
            'eine Frist': 'einhalten',
            'Punkte': 'erzielen',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Ich möchte mich im Juni zur Prüfung präsentieren.', 'Ich möchte im Juni die Prüfung ablegen.'],
          loesung: 1,
          warum: '«Presentarse a un examen» es **eine Prüfung ablegen**; *sich präsentieren* significa exhibirse o darse a conocer ante un público.',
        },
        {
          typ: 'luecke',
          text: 'Die Bestehensgrenze {1} bei 60 Punkten; wer sie verfehlt, kann das Modul zu einem späteren Prüfungstermin {2}.',
          bank: ['liegt', 'wiederholen', 'beträgt', 'bewerten'],
          loesungen: { 1: 'liegt', 2: 'wiederholen' },
        },
        {
          typ: 'mc',
          frage: 'Wer die Bestehensgrenze knapp ___, kann das Modul beim nächsten Prüfungstermin wiederholen.',
          optionen: ['versäumt', 'verfehlt', 'vermisst'],
          loesung: 1,
          warum: '**die Bestehensgrenze verfehlen** = no alcanzar el mínimo. *Versäumen* es dejar pasar (una fecha, una clase); *vermissen*, echar de menos.',
        },
        {
          typ: 'korrektur',
          optionen: ['Gehen Sie in Ihrem Beitrag auf alle drei Punkte ein.', 'Gehen Sie in Ihrem Beitrag in alle drei Punkte ein.'],
          loesung: 0,
          warum: '**eingehen auf** + acusativo = tratar, abordar un punto. No es «entrar en»: la preposición es siempre *auf*.',
        },
        {
          typ: 'luecke',
          text: 'Die vier Module werden {1} bewertet; {2} gibt es keine Gesamtnote.',
          bank: ['getrennt', 'folglich', 'obwohl', 'dennoch'],
          loesungen: { 1: 'getrennt', 2: 'folglich' },
        },
        {
          typ: 'mc',
          frage: 'Wer drei Module besteht, ___ nur das vierte zu wiederholen.',
          optionen: ['braucht', 'muss', 'soll'],
          loesung: 0,
        },
        {
          typ: 'korrektur',
          optionen: ['Morgen gebe ich im Kurs einen Vortrag über erneuerbare Energien.', 'Morgen halte ich im Kurs einen Vortrag über erneuerbare Energien.'],
          loesung: 1,
          warum: '«Dar una charla» es **einen Vortrag halten** (igual: *eine Rede halten*). *Einen Vortrag geben* es un calco del español.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies den Bericht und entscheide, welche Lösung dem Text entspricht.',
      textTitel: 'Bericht: Zwei Anläufe zum Zertifikat',
      text: 'Als Tomás Reyes vor zwei Jahren beschloss, das Zertifikat C1 abzulegen, hatte er ein klares Ziel: Die Anerkennung seines Ingenieurabschlusses in Deutschland setzte qualifizierte Sprachkenntnisse voraus. Nach mehrmonatiger Vorbereitung meldete er sich bei einem Prüfungszentrum in Stuttgart an und legte alle vier Module an einem einzigen Wochenende ab. Das Ergebnis fiel gemischt aus: Lesen, Hören und Sprechen bestand er deutlich, im Modul Schreiben verfehlte er die Bestehensgrenze jedoch um vier Punkte. „Ich hatte die Aufgabenstellung der formellen Nachricht zu schnell gelesen und einen Inhaltspunkt schlicht übersehen“, erzählt er. Entmutigen ließ er sich davon nicht. Da die bestandenen Ergebnisse gültig blieben, konzentrierte er sich in den folgenden Wochen ausschließlich auf das Schreiben: Zweimal pro Woche verfasste er einen Text und ließ ihn von einer Kollegin korrigieren. Beim nächsten Prüfungstermin wiederholte er nur dieses eine Modul und erzielte 78 Punkte. Rückblickend hält er den ersten Misserfolg sogar für lehrreich: „Ohne ihn hätte ich nie begriffen, wie wichtig es ist, jede Anweisung zweimal zu lesen.“ Anderen rät er, die Modularität bewusst zu nutzen, statt die Anmeldung aus Angst vor dem Scheitern immer weiter hinauszuschieben.',
      items: [
        { typ: 'rf', aussage: 'Beim ersten Versuch legte Tomás zunächst nur einen Teil der Module ab.', loesung: false },
        {
          typ: 'mc',
          frage: 'Warum verfehlte Tomás zunächst die Bestehensgrenze im Modul Schreiben?',
          optionen: ['Sein Text war deutlich zu kurz.', 'Er hatte einen Punkt der Aufgabe nicht behandelt.', 'Er hatte das Register der Nachricht verfehlt.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Wie bereitete er sich auf die Wiederholung vor?',
          optionen: ['Er besuchte einen Intensivkurs am Prüfungszentrum.', 'Er wiederholte zur Sicherheit alle vier Module.', 'Er übte gezielt das Schreiben und ließ seine Texte korrigieren.'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Im Nachhinein bewertet Tomás sein anfängliches Scheitern auch positiv.', loesung: true },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du hörst eine Nachricht auf deiner Mailbox. Entscheide, welche Lösung dem Gehörten entspricht bzw. ob die Aussage richtig oder falsch ist.',
      audio: {
        transcript: 'Guten Tag, Frau Morales, hier spricht Tobias Brandt vom Prüfungszentrum in Leipzig. Ich rufe wegen Ihrer Anmeldung zum Zertifikat C1 an. Leider muss ich Ihnen mitteilen, dass der Prüfungstermin am vierzehnten Juni bereits ausgebucht ist. Wir können Ihnen stattdessen den achtundzwanzigsten Juni anbieten. An diesem Tag würden Sie vormittags die Module Lesen, Hören und Schreiben ablegen. Das Modul Sprechen findet allerdings nicht am selben Tag statt, sondern erst am Montag darauf, und zwar um fünfzehn Uhr dreißig. Bitte kommen Sie am achtundzwanzigsten spätestens um Viertel nach acht; die Prüfung selbst beginnt um neun Uhr. Noch ein Hinweis zu Ihren Unterlagen: Die Kopie Ihres Ausweises liegt uns vor, es fehlt jedoch noch die unterschriebene Einverständniserklärung. Die können Sie uns einfach per E-Mail schicken, ein Brief ist nicht nötig. Falls Ihnen der neue Termin nicht passt, geben Sie uns bitte bis Freitag Bescheid; sonst reservieren wir den Platz verbindlich für Sie. Die Prüfungsgebühr überweisen Sie bitte erst, wenn Sie unsere schriftliche Bestätigung erhalten haben. Sie erreichen mich werktags zwischen zehn und sechzehn Uhr unter der Durchwahl vier, sieben, null. Vielen Dank und auf Wiederhören.',
      },
      items: [
        { typ: 'rf', aussage: 'Meldet sich Frau Morales bis Freitag nicht, wird ihr Platz am neuen Termin anderweitig vergeben.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wann findet das Modul Sprechen statt?',
          optionen: ['am Nachmittag desselben Tages', 'am Montag nach den schriftlichen Modulen', 'eine Woche vor den übrigen Modulen'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Was soll Frau Morales dem Prüfungszentrum noch zukommen lassen?',
          optionen: ['eine Kopie ihres Ausweises', 'einen Beleg über die bezahlte Prüfungsgebühr', 'eine unterschriebene Einverständniserklärung'],
          loesung: 2,
        },
        { typ: 'rf', aussage: 'Die Prüfungsgebühr soll erst überwiesen werden, nachdem die schriftliche Bestätigung eingetroffen ist.', loesung: true },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Schreiben',
      anweisung: 'Verfasse eine formelle Nachricht von mindestens 80 Wörtern. Achte auf Anrede, Register und Grußformel.',
      aufgabe: 'Du möchtest das Zertifikat C1 ablegen, bist dir aber bei einigen organisatorischen Fragen unsicher. Schreib eine formelle Nachricht an das Prüfungszentrum deiner Stadt.',
      punkte: [
        'Stell dich kurz vor und nenne den Anlass deiner Nachricht.',
        'Erkundige dich nach Anmeldefristen und freien Prüfungsterminen.',
        'Frag, unter welchen Bedingungen sich ein einzelnes Modul wiederholen lässt.',
      ],
      minWoerter: 80,
      beispielLoesung: 'Sehr geehrte Damen und Herren, mein Name ist Lucía Ferrer; ich arbeite seit einem Jahr als Pflegefachkraft in Nürnberg und benötige für die Anerkennung meines Abschlusses das Zertifikat C1. Daher möchte ich mich bei Ihnen über die Anmeldung informieren. Könnten Sie mir bitte mitteilen, bis wann die Anmeldung für die Prüfungstermine im Herbst erfolgen muss und ob noch Plätze frei sind? Darüber hinaus wüsste ich gern, ob sich ein nicht bestandenes Modul einzeln wiederholen lässt und ob dafür eine bestimmte Frist gilt. Für Ihre Auskunft bedanke ich mich im Voraus. Mit freundlichen Grüßen Lucía Ferrer',
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Nimm mündlich Stellung. Sprich etwa zwei Minuten frei und zusammenhängend.',
      aufgabe: 'In deinem Sprachkurs wird diskutiert, ob man die vier Module des Zertifikats C1 besser an einem einzigen Prüfungstermin oder verteilt auf mehrere Termine ablegen sollte. Nimm dazu vor der Gruppe in einer zusammenhängenden Stellungnahme von etwa zwei Minuten Position: Wäge beide Vorgehensweisen ab, begründe deine eigene Entscheidung und schließe mit einem Rat.',
      punkte: [
        'Nenne je ein Argument für beide Vorgehensweisen.',
        'Leg dar, wofür du dich selbst entscheiden würdest, und begründe das mit deiner persönlichen Situation.',
        'Schließe mit einem Rat an andere Lernende.',
      ],
      redemittel: ['Für … spricht vor allem, dass …', 'Dagegen lässt sich einwenden, dass …', 'In meinem Fall …', 'Alles in allem würde ich dazu raten, …'],
      maxSekunden: 120,
      beispielLoesung: 'Die Frage, ob man alle vier Module auf einmal ablegen sollte, lässt sich meiner Meinung nach nicht pauschal beantworten. Für einen einzigen Prüfungstermin spricht vor allem, dass man die Sache schnell hinter sich hat: Man bereitet sich einmal intensiv vor, reist nur einmal an und hält am Ende das komplette Zeugnis in der Hand. Dagegen lässt sich einwenden, dass so ein Prüfungstag enorm anstrengend ist. Wer morgens schon drei Module geschrieben hat, ist beim Sprechen vielleicht nicht mehr in Bestform. Verteilt man die Module auf zwei Termine, sinkt der Druck deutlich, und man kann sich gezielt auf die schwächere Fertigkeit konzentrieren. In meinem Fall würde ich mich trotzdem für einen einzigen Termin entscheiden. Ich brauche das Zertifikat nämlich bis zum Herbst für meine Bewerbung, und ich weiß, dass ich mich unter Zeitdruck besser konzentriere. Außerdem beruhigt mich der Gedanke, dass ich ein einzelnes Modul wiederholen kann, falls ich die Bestehensgrenze irgendwo verfehle; die bestandenen Ergebnisse bleiben ja gültig. Alles in allem würde ich anderen Lernenden raten, ehrlich zu überlegen, wie belastbar sie an einem langen Prüfungstag sind. Wer bei Stress schnell Fehler macht, sollte die Modularität ruhig nutzen. Wer dagegen unter Druck aufblüht, kann alles an einem Wochenende schaffen.',
    },
  ],
}
