// Übungsheft B1 — Lektion 26: Modul Schreiben — Überblick & Bewertung
export default {
  lektion: 26,
  titel: 'Übungsheft — Modul Schreiben: Überblick',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Hier übst du die Punkte der Checkliste. Wähle die richtige Form oder ergänze.',
      items: [
        { typ: 'mc', frage: 'Ich glaube, dass ich am Samstag ___.', optionen: ['kann kommen', 'kommen kann', 'komme kann'], loesung: 1 },
        { typ: 'mc', frage: 'Am Ende ___ meinen Text noch einmal.', optionen: ['kontrolliere ich', 'ich kontrolliere', 'kontrolliert ich'], loesung: 0 },
        { typ: 'mc', frage: 'Welches Zeichen steht nach der Anrede? „Liebe Anna___ ich danke dir …“', optionen: [':', '.', ','], loesung: 2 },
        {
          typ: 'luecke',
          text: 'In der Aufgabe stehen drei {1}. Du musst alle behandeln. Denk auch an den {2}: Schreibst du einem Freund oder deinem Chef?',
          bank: ['Punkte', 'Punkten', 'Empfänger', 'Empfängern'],
          loesungen: { 1: 'Punkte', 2: 'Empfänger' },
        },
        {
          typ: 'luecke',
          text: 'Eine E-Mail beginnt mit der {1} und endet mit einer {2}. Vor „weil“ steht ein {3}.',
          bank: ['Anrede', 'Grußformel', 'Komma', 'Punkt', 'Bewertung'],
          loesungen: { 1: 'Anrede', 2: 'Grußformel', 3: 'Komma' },
        },
        {
          typ: 'zuordnen',
          links: ['Erfüllung', 'Kohärenz', 'Wortschatz', 'Strukturen'],
          rechts: [
            'Sind alle Punkte der Aufgabe im Text?',
            'Ist der Text logisch verbunden?',
            'Gibt es Abwechslung bei den Wörtern?',
            'Sind Verbposition und Endungen korrekt?',
          ],
          loesung: {
            'Erfüllung': 'Sind alle Punkte der Aufgabe im Text?',
            'Kohärenz': 'Ist der Text logisch verbunden?',
            'Wortschatz': 'Gibt es Abwechslung bei den Wörtern?',
            'Strukturen': 'Sind Verbposition und Endungen korrekt?',
          },
        },
        { typ: 'satzbau', woerter: ['du', 'weil', 'Ich', 'kommst', 'mich', 'freue'], loesung: 'Ich freue mich, weil du kommst.' },
        { typ: 'satzbau', woerter: ['keine', 'habe', 'Morgen', 'leider', 'Zeit', 'ich'], loesung: 'Morgen habe ich leider keine Zeit.' },
        {
          typ: 'korrektur',
          optionen: ['Ich schreibe eine E-Mail an meine Lehrerin.', 'Ich schreibe eine e-mail an meine lehrerin.'],
          loesung: 0,
          warum: 'Todos los sustantivos van con **mayúscula**: *die E-Mail, die Lehrerin*. Es el error n.º 1 del hispanohablante.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich komme nicht, weil ich bin krank.', 'Ich komme nicht, weil ich krank bin.'],
          loesung: 1,
          warum: 'Tras *weil* el verbo conjugado va **al final**: *…, weil ich krank **bin**.* En español el orden no cambia; en alemán sí.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die E-Mail der Kursleiterin. Löse dann die vier Aufgaben.',
      textTitel: 'E-Mail: Probetest Schreiben',
      text: 'Liebe Kursteilnehmerinnen und Kursteilnehmer,\nam Samstag, dem 14. März, schreiben wir den Probetest im Modul Schreiben. Wir beginnen um 9:30 Uhr in Raum 12. Sie haben 60 Minuten für drei Texte, die Reihenfolge wählen Sie selbst. Bitte bringen Sie einen Kuli mit. Wörterbücher sind nicht erlaubt. Ich korrigiere Ihre Texte mit den vier Kriterien der Prüfung und schicke Ihnen die Bewertung eine Woche später per E-Mail. Am Dienstag danach besprechen wir die typischen Fehler gemeinsam im Kurs. Wer am Samstag nicht kommen kann, sagt mir bitte bis Donnerstag Bescheid. Dann bekommen Sie die Aufgaben per Post und können die Texte zu Hause schreiben.\nMit freundlichen Grüßen\nKatrin Vogel',
      items: [
        { typ: 'rf', aussage: 'Die Teilnehmer müssen die Texte in einer festen Reihenfolge schreiben.', loesung: false },
        { typ: 'rf', aussage: 'Im Probetest darf man kein Wörterbuch benutzen.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wann bekommen die Teilnehmer ihre Bewertung?',
          optionen: ['direkt nach dem Test', 'eine Woche nach dem Test', 'am Donnerstag vor dem Test'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Was passiert, wenn jemand am Samstag keine Zeit hat?',
          optionen: ['Er schreibt den Test am Dienstag im Kurs.', 'Er kann den Test nicht machen.', 'Er schreibt die Texte zu Hause.'],
          loesung: 2,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Hör das Gespräch nach dem Probetest. Löse dann die vier Aufgaben.',
      audio: {
        transcript: 'Frau: Hallo Deniz! Na, wie war dein Probetest im Schreiben?\nMann: Hallo Mila! Na ja, nicht so gut. Ich habe mir die Zeit schlecht eingeteilt.\nFrau: Wieso? Wir hatten doch sechzig Minuten.\nMann: Ja, aber für die erste E-Mail habe ich nicht zwanzig, sondern fast vierzig Minuten gebraucht. Für den Forumsbeitrag hatte ich dann nur noch zehn Minuten.\nFrau: Oh nein! Und die formelle E-Mail?\nMann: Die habe ich geschafft, aber ich habe die Grußformel vergessen. Und bei dir?\nFrau: Bei mir hat die Zeit gereicht. Ich habe am Ende sogar alle drei Texte kontrolliert und noch zwei Fehler gefunden: Ein Komma hat gefehlt, und ein Nomen war kleingeschrieben.\nMann: Super! Nächstes Mal nehme ich eine Uhr mit.',
      },
      items: [
        { typ: 'rf', aussage: 'Deniz hat für die erste E-Mail zwanzig Minuten gebraucht.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was hat in der formellen E-Mail von Deniz gefehlt?',
          optionen: ['die Anrede', 'die Grußformel', 'ein Komma'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Mila hat ihre Texte am Ende noch einmal gelesen und dabei Fehler gefunden.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was will Deniz beim nächsten Mal machen?',
          optionen: ['mit dem Forumsbeitrag anfangen', 'ein Wörterbuch mitbringen', 'eine Uhr mitnehmen'],
          loesung: 2,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'formular',
      titel: 'Schreiben',
      anweisung: 'Lies die E-Mail von Rashid. Ergänze dann das Anmeldeformular für die Schreibwerkstatt.',
      quelle: 'Liebe Frau Vogel, mein Name ist Rashid Karimi. Ich möchte gern an der Schreibwerkstatt teilnehmen. Am schwierigsten ist für mich Teil 2, der Forumsbeitrag. Meine häufigsten Fehler sind Kommas und die Verbposition. Am besten passt mir der Termin am Mittwochabend. Viele Grüße, Rashid Karimi',
      felder: [
        { id: 'name', label: 'Name', erwartet: ['Rashid Karimi', 'Karimi'] },
        { id: 'empfaenger', label: 'Empfängerin der E-Mail', erwartet: ['Frau Vogel', 'Vogel', 'Katrin Vogel'] },
        { id: 'teil', label: 'Schwierigster Teil', erwartet: ['Teil 2', 'Teil 2, der Forumsbeitrag', 'Teil 2 (Forumsbeitrag)', 'der Forumsbeitrag', 'Forumsbeitrag'] },
        { id: 'fehler', label: 'Häufige Fehler', erwartet: ['Kommas und die Verbposition', 'Kommas und Verbposition', 'Kommas, Verbposition', 'Komma und Verbposition'] },
        { id: 'termin', label: 'Wunschtermin', erwartet: ['Mittwochabend', 'am Mittwochabend', 'Mittwoch', 'Mittwoch abend'] },
      ],
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Berichte im Kurs von deinen Erfahrungen. Sprich ungefähr eine Minute.',
      aufgabe: 'Wie schreibst du Texte auf Deutsch? Berichte von deinen Erfahrungen.',
      punkte: [
        'Welche Texte schreibst du auf Deutsch?',
        'Was ist für dich beim Schreiben schwierig?',
        'Welche Fehler machst du oft?',
        'Wie kontrollierst du deinen Text am Ende?',
      ],
      redemittel: ['Ich schreibe auf Deutsch vor allem …', 'Am schwierigsten ist für mich …', 'Ich vergesse oft, dass …', 'Am Ende kontrolliere ich …'],
      maxSekunden: 75,
      beispielLoesung: 'Also, ich schreibe auf Deutsch vor allem E-Mails an meine Kollegen und manchmal kurze Nachrichten an Freunde. Im Kurs schreiben wir auch Forumsbeiträge. Am schwierigsten ist für mich die Zeit. Ich denke zu lange nach, und dann werde ich nicht fertig. Meine typischen Fehler sind die Artikel und das Verb im Nebensatz. Nach „weil“ vergesse ich oft, dass das Verb am Ende steht. Deshalb kontrolliere ich jetzt jeden Text mit einer Checkliste. Zuerst suche ich alle Nomen und schaue, ob sie großgeschrieben sind. Dann kontrolliere ich die Verben und die Kommas. Das dauert nur drei Minuten, aber ich finde fast immer einen Fehler.',
    },
  ],
}
