// Übungsheft B1 — Lektion 18: Modul Lesen — Überblick
export default {
  lektion: 18,
  titel: 'Übungsheft — Modul Lesen: Überblick',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Hier übst du die Wörter aus den Anweisungen. Wähle die richtige Form oder ergänze.',
      items: [
        { typ: 'mc', frage: 'Hast du die richtige Lösung schon ___?', optionen: ['angekreuzt', 'geankreuzt', 'ankreuzt'], loesung: 0 },
        { typ: 'mc', frage: 'Ich habe den Text zuerst nur schnell ___.', optionen: ['übergeflogen', 'überflogen', 'überfliegt'], loesung: 1 },
        { typ: 'mc', frage: 'Welche Anzeige passt zu ___ Person?', optionen: ['welche', 'welchem', 'welcher'], loesung: 2 },
        {
          typ: 'luecke',
          text: 'Lies zuerst die {1}. Dann {2} du den Text und suchst die Paraphrase.',
          bank: ['Aufgaben', 'Antwortbogen', 'überfliegst', 'überfliegen'],
          loesungen: { 1: 'Aufgaben', 2: 'überfliegst' },
        },
        {
          typ: 'luecke',
          text: 'Es ist wichtig, jede Aufgabe {1}. Am Ende {2} die Lösungen auf den {3} übertragen.',
          bank: ['anzukreuzen', 'zu ankreuzen', 'werden', 'wird', 'Antwortbogen'],
          loesungen: { 1: 'anzukreuzen', 2: 'werden', 3: 'Antwortbogen' },
        },
        {
          typ: 'zuordnen',
          links: ['überfliegen', 'unterstreichen', 'ankreuzen', 'zuordnen', 'die Aussage'],
          rechts: [
            'schnell lesen, nicht Wort für Wort',
            'eine Linie unter ein Wort machen',
            'ein X in das richtige Feld machen',
            'zwei passende Teile verbinden',
            'ein Satz, der richtig oder falsch ist',
          ],
          loesung: {
            'überfliegen': 'schnell lesen, nicht Wort für Wort',
            'unterstreichen': 'eine Linie unter ein Wort machen',
            'ankreuzen': 'ein X in das richtige Feld machen',
            'zuordnen': 'zwei passende Teile verbinden',
            'die Aussage': 'ein Satz, der richtig oder falsch ist',
          },
        },
        { typ: 'satzbau', woerter: ['Person', 'passt', 'Welcher', 'welcher', 'zu', 'Text'], loesung: 'Welcher Text passt zu welcher Person?' },
        {
          typ: 'satzbau',
          woerter: ['den', 'die', 'Ich', 'dann', 'Aufgaben', 'zuerst', 'und', 'lese', 'Text'],
          loesung: 'Ich lese zuerst die Aufgaben und dann den Text.',
          alt: ['Ich lese die Aufgaben zuerst und dann den Text.'],
        },
        {
          typ: 'korrektur',
          optionen: ['Lies nicht Wort für Wort, um Zeit zu sparen.', 'Lies nicht Wort für Wort, für Zeit zu sparen.'],
          loesung: 0,
          warum: '«Para ahorrar tiempo» = **um** Zeit **zu** sparen. *Für* no introduce un infinitivo.',
        },
        {
          typ: 'korrektur',
          optionen: ['Diese Anzeige passt zu dich.', 'Diese Anzeige passt zu dir.'],
          loesung: 1,
          warum: '*Zu* pide siempre **dativo**: *passen zu **dir** / zu **welcher** Person*.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die Zeitungsnotiz. Die Lösung steht oft mit anderen Wörtern im Text.',
      textTitel: 'Stadtbibliothek Neustadt: Mehr Zeit zum Lesen',
      text: 'Ab dem 1. November hat die Stadtbibliothek länger geöffnet: Von Dienstag bis Freitag können Besucher jetzt bis 20 Uhr Bücher ausleihen. Montags bleibt die Bibliothek wie bisher geschlossen. Neu ist auch das Lesecafé im Erdgeschoss. Dort gibt es Zeitungen aus zwölf Ländern, Kaffee und Kuchen. Der Eintritt ins Café ist frei, auch ohne Bibliotheksausweis. Jeden Mittwoch trifft sich dort außerdem ein Leseclub für Deutschlernende. Die Teilnehmer lesen gemeinsam kurze Texte und sprechen darüber. Die Leiterin, Frau Demir, erklärt schwierige Wörter. Für den Leseclub muss man sich vorher per E-Mail anmelden, denn es gibt nur fünfzehn Plätze. Kinder unter zwölf Jahren können leider nicht teilnehmen.',
      items: [
        { typ: 'rf', aussage: 'Am Montag kann man in der Bibliothek keine Bücher ausleihen.', loesung: true },
        { typ: 'rf', aussage: 'Für das Lesecafé braucht man einen Bibliotheksausweis.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was macht man im Leseclub?',
          optionen: ['Man kauft Zeitungen aus zwölf Ländern.', 'Man hilft Kindern bei den Hausaufgaben.', 'Man liest zusammen Texte und diskutiert sie.'],
          loesung: 2,
        },
        {
          typ: 'mc',
          frage: 'Warum muss man sich für den Leseclub anmelden?',
          optionen: ['Weil die Zahl der Plätze begrenzt ist.', 'Weil der Club Geld kostet.', 'Weil er nur für Kinder ist.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Hör die Informationen der Kursleiterin. Achte auf Paraphrasen in den Aufgaben.',
      audio: {
        transcript: 'So, zum Schluss noch ein paar Informationen zum Übungstest. Wir schreiben den Lesetest nicht am Donnerstag, sondern erst am Freitag, und zwar um halb zehn in Raum zwölf. Seid bitte schon um Viertel nach neun da. Ihr habt fünfundsechzig Minuten Zeit für fünf Teile. Lest zuerst die Aufgaben und überfliegt dann den Text. Ihr dürft Schlüsselwörter unterstreichen, aber ein Wörterbuch ist nicht erlaubt. Kreuzt am Ende jede Aufgabe an, denn für falsche Lösungen gibt es keine Minuspunkte. Vergesst nicht, eure Lösungen auf den Antwortbogen zu übertragen. Nach dem Test machen wir keinen Unterricht mehr, ihr könnt dann gleich nach Hause gehen. Wer am Freitag keine Zeit hat, schreibt den Test am Dienstag nach dem Kurs. Die Ergebnisse bekommt ihr am Montag per E-Mail.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Wann beginnt der Lesetest?',
          optionen: ['am Donnerstag um halb zehn', 'am Freitag um halb zehn', 'am Freitag um Viertel nach neun'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Nach dem Lesetest geht der Unterricht normal weiter.', loesung: false },
        { typ: 'rf', aussage: 'Wer am Freitag nicht kommen kann, darf den Test an einem anderen Tag schreiben.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wie bekommen die Teilnehmer ihre Ergebnisse?',
          optionen: ['am Montag im Kurs', 'mit der Post', 'in einer E-Mail'],
          loesung: 2,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'formular',
      titel: 'Schreiben',
      anweisung: 'Lies die E-Mail von Yuki. Ergänze dann die Anmeldung für den Leseclub.',
      quelle: 'Liebe Frau Demir, ich heiße Yuki Tanaka und möchte mich für den Leseclub anmelden. Ich lerne seit zwei Jahren Deutsch und lese am liebsten Krimis. Ich möchte ab November jeden Mittwoch kommen. Sie erreichen mich unter der Nummer 0176 5523 4410. Viele Grüße, Yuki Tanaka',
      felder: [
        { id: 'name', label: 'Name', erwartet: ['Yuki Tanaka', 'Tanaka'] },
        { id: 'seit', label: 'Deutsch seit', erwartet: ['zwei Jahren', 'seit zwei Jahren', '2 Jahren', 'seit 2 Jahren', 'zwei Jahre', '2 Jahre'] },
        { id: 'lektuere', label: 'Was lesen Sie gern?', erwartet: ['Krimis', 'am liebsten Krimis'] },
        { id: 'beginn', label: 'Beginn', erwartet: ['ab November', 'November', 'im November'] },
        { id: 'telefon', label: 'Telefon', erwartet: ['0176 5523 4410', '017655234410', '0176 55234410'] },
      ],
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Sprich etwa 75 Sekunden. Erzähl frei und in ganzen Sätzen.',
      aufgabe: 'Sprich über das Thema „Lesen auf Deutsch“: Was liest du, und wie liest du?',
      punkte: [
        'Was liest du auf Deutsch, und wo?',
        'Was machst du, wenn du ein Wort nicht verstehst?',
        'Welche Strategie hilft dir bei langen Texten?',
        'Welchen Tipp gibst du anderen Lernenden?',
      ],
      redemittel: ['Ich lese oft …', 'Wenn ich ein Wort nicht verstehe, …', 'Zuerst überfliege ich …', 'Mein Tipp ist: …'],
      maxSekunden: 75,
      beispielLoesung: 'Ich lese jeden Tag ein bisschen auf Deutsch. Morgens im Bus lese ich kurze Nachrichten auf dem Handy, und am Wochenende lese ich manchmal einen Blog über Reisen. Früher habe ich jedes unbekannte Wort im Wörterbuch gesucht. Das hat sehr lange gedauert! Heute lese ich einfach weiter, wenn ich ein Wort nicht verstehe. Meistens verstehe ich den Satz trotzdem. Bei langen Texten überfliege ich zuerst alles und suche die Schlüsselwörter. Erst dann lese ich die wichtigen Stellen genau. Mein Tipp für andere: Lest Texte über Themen, für die ihr euch interessiert. Dann macht das Lesen Spaß, und man lernt die Wörter fast automatisch.',
    },
  ],
}
