// Übungsheft B1 — Lektion 03: Diagnose B1 — Standortbestimmung
export default {
  lektion: 3,
  titel: 'Übungsheft — Diagnose: drei Mini-Tests',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Mini-Test 1 · Grammatik & Wortschatz',
      anweisung: 'Mach den Test ohne Hilfe. Notiere jeden Fehler. Bei jeder Korrektur steht, welche Lektion dir hilft.',
      items: [
        {
          typ: 'luecke',
          text: 'Mein {1} ist klar: Ich will B1 schaffen. Meine {2} ist Lesen, aber Sprechen ist noch meine {3}.',
          bank: ['Ziel', 'Stärke', 'Schwäche', 'Fehler'],
          loesungen: { 1: 'Ziel', 2: 'Stärke', 3: 'Schwäche' },
        },
        {
          typ: 'luecke',
          text: 'Die Wohnung ist schön, aber die {1} ist zu hoch. Für die neue Stelle schreibe ich eine {2}.',
          bank: ['Miete', 'Bewerbung', 'Fahrkarte', 'Rechnung'],
          loesungen: { 1: 'Miete', 2: 'Bewerbung' },
        },
        { typ: 'satzbau', woerter: ['noch', 'Regel', 'wiederhole', 'einmal', 'Ich', 'die'], loesung: 'Ich wiederhole die Regel noch einmal.', alt: ['Ich wiederhole noch einmal die Regel.'] },
        { typ: 'satzbau', woerter: ['zehn', 'ich', 'Tag', 'übe', 'Deshalb', 'jeden', 'Minuten'], loesung: 'Deshalb übe ich jeden Tag zehn Minuten.', alt: ['Deshalb übe ich zehn Minuten jeden Tag.'] },
        {
          typ: 'zuordnen',
          links: ['üben', 'wiederholen', 'verbessern', 'einschätzen'],
          rechts: ['etwas oft trainieren', 'etwas noch einmal lernen', 'etwas besser machen', 'sein Niveau realistisch sehen'],
          loesung: {
            'üben': 'etwas oft trainieren',
            'wiederholen': 'etwas noch einmal lernen',
            'verbessern': 'etwas besser machen',
            'einschätzen': 'sein Niveau realistisch sehen',
          },
        },
        {
          typ: 'korrektur',
          optionen: ['Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.', 'Ich lerne Deutsch, weil ich möchte in Deutschland arbeiten.'],
          loesung: 0,
          warum: 'Con **weil** el verbo conjugado va **al final**: *…weil ich in Deutschland arbeiten **möchte**.* ¿Fallo? → **Lektion 4**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Es regnet. Trotzdem wir gehen spazieren.', 'Es regnet. Trotzdem gehen wir spazieren.'],
          loesung: 1,
          warum: '**trotzdem** (aun así) ocupa la posición 1 → el **verbo** va justo detrás: *Trotzdem **gehen wir**…* ¿Fallo? → **Lektion 5**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Als ich ein Kind war, habe ich in Lima gewohnt.', 'Wenn ich ein Kind war, habe ich in Lima gewohnt.'],
          loesung: 0,
          warum: 'Una sola vez o una etapa en el **pasado** → **als**, no *wenn*: *Als ich ein Kind war…* ¿Fallo? → **Lektion 5**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Gestern habe ich nach Berlin gefahren.', 'Gestern bin ich nach Berlin gefahren.'],
          loesung: 1,
          warum: '**fahren** es movimiento de un lugar a otro → Perfekt con **sein**: *Ich **bin** gefahren.* En español siempre «he», en alemán no. ¿Fallo? → **Lektion 6**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Letztes Jahr bin ich oft krank und habe viel Stress.', 'Letztes Jahr war ich oft krank und hatte viel Stress.'],
          loesung: 1,
          warum: 'Para contar el pasado, **sein** y **haben** van casi siempre en **Präteritum**: *war, hatte*. ¿Fallo? → **Lektion 7**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich lege das Heft auf den Tisch.', 'Ich lege das Heft auf dem Tisch.'],
          loesung: 0,
          warum: '¿**Wohin?** (dirección, con *legen*) → **Akkusativ**: *auf **den** Tisch*. ¿Fallo? → **Lektion 8**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich warte für den Bus.', 'Ich warte auf den Bus.'],
          loesung: 1,
          warum: 'Muchos verbos llevan una **preposición fija**: *warten **auf** + Akkusativ*. No se traduce del español. ¿Fallo? → **Lektion 9**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Das ist ein neues Auto.', 'Das ist ein neue Auto.'],
          loesung: 0,
          warum: 'Tras **ein** con un sustantivo neutro, el adjetivo lleva **-es**: *ein neu**es** Auto*. ¿Fallo? → **Lektion 10**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Berlin ist mehr groß als München.', 'Berlin ist größer als München.'],
          loesung: 1,
          warum: 'El comparativo se forma con **-er** (a menudo con Umlaut), no con *mehr*: *groß → gr**ö**ß**er** als*. ¿Fallo? → **Lektion 11**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Das ist der Mann, der mir geholfen hat.', 'Das ist der Mann, den mir geholfen hat.'],
          loesung: 0,
          warum: 'El pronombre relativo es el **sujeto** de *geholfen hat* → **Nominativ**: *der*. ¿Fallo? → **Lektion 12**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich würde gern ein Glas Wasser.', 'Ich hätte gern ein Glas Wasser.'],
          loesung: 1,
          warum: 'Para pedir algo con cortesía: **Ich hätte gern…** *Würde* necesita otro verbo: *Ich würde gern Wasser **trinken***. ¿Fallo? → **Lektion 13**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Das ist das Auto meines Vaters.', 'Das ist das Auto meinem Vater.'],
          loesung: 0,
          warum: 'Posesión («de mi padre») → **Genitiv**: *das Auto mein**es** Vater**s***. ¿Fallo? → **Lektion 14**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Das Brot wird jeden Morgen backen.', 'Das Brot wird jeden Morgen gebacken.'],
          loesung: 1,
          warum: 'Pasiva = **werden + Partizip II**: *wird … **gebacken***. Con infinitivo sería futuro, y aquí no tiene sentido. ¿Fallo? → **Lektion 15**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich lerne Deutsch, um in Deutschland zu arbeiten.', 'Ich lerne Deutsch, für in Deutschland arbeiten.'],
          loesung: 0,
          warum: '«Para + infinitivo» → **um … zu** + infinitivo al final, nunca *für*: *um … zu arbeiten*. ¿Fallo? → **Lektion 16**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich freue auf das Wochenende.', 'Ich freue mich auf das Wochenende.'],
          loesung: 1,
          warum: '**sich freuen auf** es reflexivo: necesita **mich, dich, sich…** ¿Fallo? → **Lektion 17**.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Mini-Test 2 · Lesen',
      anweisung: 'Lies die Anzeige und löse die Aufgaben.',
      textTitel: 'Anzeige: Lerngruppe „Fit für B1“ sucht neue Mitglieder',
      text: 'Du lernst Deutsch und willst die B1-Prüfung schaffen? Unsere Lerngruppe trifft sich jeden Dienstag um 19 Uhr in der Stadtbibliothek, Raum 2. Wir sind sechs Personen aus fünf Ländern. Zuerst machen wir immer einen kurzen Test und notieren unsere Ergebnisse. So sehen wir jeden Monat unsere Fortschritte. Dann üben wir in kleinen Gruppen. Hast du eine Schwäche beim Sprechen? Dann sprichst du bei uns viel. Machst du beim Schreiben viele Fehler? Dann schreibst du E-Mails, und wir korrigieren sie zusammen. Die Teilnahme kostet nichts, nur den Kaffee bezahlt jeder selbst. Bitte bring ein Heft und einen Stift mit. Neue Mitglieder melden sich bis Freitag bei Irina: irina.lerngruppe@beispiel.de. Wir freuen uns auf dich!',
      items: [
        { typ: 'rf', aussage: 'Die Lerngruppe trifft sich einmal pro Woche.', loesung: true },
        { typ: 'rf', aussage: 'Die Teilnahme kostet fünf Euro.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was macht die Gruppe am Anfang?',
          optionen: ['Sie trinkt Kaffee.', 'Sie macht einen kurzen Test.', 'Sie schreibt E-Mails.'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Was sollen neue Mitglieder mitbringen?',
          optionen: ['ein Heft und einen Stift', 'einen Laptop', 'ein Wörterbuch'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'text',
      titel: 'Mini-Test 3 · Schreiben',
      anweisung: 'Schreib eine E-Mail mit mindestens 40 Wörtern. Verbinde deine Sätze mit weil, deshalb oder wenn.',
      aufgabe: 'Deine Freundin Ana fragt: „Wie läuft dein Deutschkurs?“ Antworte ihr mit einer E-Mail.',
      punkte: [
        'Wie ist dein Kurs?',
        'Was kannst du schon gut?',
        'Was ist noch schwer, und was machst du dagegen?',
      ],
      minWoerter: 40,
      beispielLoesung: 'Liebe Ana,\nmein Kurs läuft gut! Wir üben viel Grammatik, und ich verstehe schon fast alles, wenn der Lehrer langsam spricht. Lesen finde ich leicht, aber Sprechen ist noch schwer, weil ich Angst vor Fehlern habe. Deshalb übe ich jetzt jeden Tag zehn Minuten mit einer Kollegin.\nLiebe Grüße\nCarla',
    },
  ],
}
