// Übungsheft B1 — Lektion 10: Adjektivdeklination
export default {
  lektion: 10,
  titel: 'Übungsheft — Adjektivdeklination',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Schau zuerst auf den Artikel: der/die/das, ein/kein oder kein Artikel? Wähle dann die Endung.',
      items: [
        { typ: 'mc', frage: 'Ich kaufe den ___ Mantel.', optionen: ['schwarze', 'schwarzen', 'schwarzer'], loesung: 1 },
        { typ: 'mc', frage: 'Wir haben leider ein ___ Problem.', optionen: ['kleine', 'kleinen', 'kleines'], loesung: 2 },
        { typ: 'mc', frage: 'Zum Frühstück trinkt Jonas gern ___ Tee.', optionen: ['heißen', 'heißer', 'heiße'], loesung: 0 },
        {
          typ: 'luecke',
          text: 'Mein {1} Nachbar hat ein {2} Auto. Er fährt jeden Tag mit dem {3} Auto zur Arbeit.',
          bank: ['neuer', 'neues', 'rotes', 'rote', 'roten'],
          loesungen: { 1: 'neuer', 2: 'rotes', 3: 'roten' },
        },
        {
          typ: 'luecke',
          text: 'Emma sucht eine {1} Wohnung mit einem {2} Balkon. Die Wohnung darf nicht zu {3} sein.',
          bank: ['günstige', 'günstigen', 'großen', 'großem', 'teuer', 'teure'],
          loesungen: { 1: 'günstige', 2: 'großen', 3: 'teuer' },
        },
        {
          typ: 'luecke',
          text: 'Im Café Sonne gibt es {1} Kuchen mit {2} Sahne und {3} Brot.',
          bank: ['leckeren', 'leckerer', 'frischer', 'frischen', 'warmes', 'warme'],
          loesungen: { 1: 'leckeren', 2: 'frischer', 3: 'warmes' },
        },
        {
          typ: 'zuordnen',
          links: ['der klein__ Hund', 'ein klein__ Hund (Nom.)', 'ein klein__ Kind', 'mit kalt__ Wasser', 'mit dem klein__ Kind'],
          rechts: ['-e', '-er', '-es', '-em', '-en'],
          loesung: {
            'der klein__ Hund': '-e',
            'ein klein__ Hund (Nom.)': '-er',
            'ein klein__ Kind': '-es',
            'mit kalt__ Wasser': '-em',
            'mit dem klein__ Kind': '-en',
          },
        },
        { typ: 'satzbau', woerter: ['Kleid', 'trägt', 'rotes', 'heute', 'ein', 'Aylin'], loesung: 'Aylin trägt heute ein rotes Kleid.', alt: ['Heute trägt Aylin ein rotes Kleid.'] },
        {
          typ: 'korrektur',
          optionen: ['Der Pullover ist rote.', 'Der Pullover ist rot.'],
          loesung: 1,
          warum: 'Después de **sein** el adjetivo **no lleva terminación**. En español concuerda (*es roja*); en alemán no.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich habe einen neuen Computer gekauft.', 'Ich habe ein neuer Computer gekauft.'],
          loesung: 0,
          warum: '*Computer* es masculino y aquí es objeto → **Akkusativ: einen neu-en**. El error típico es dejar la forma del nominativo.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die Anzeige. Löse dann die vier Aufgaben.',
      textTitel: 'Anzeige: Wir ziehen um – günstige Möbel',
      text: 'Wir ziehen Ende Oktober nach Leipzig und verkaufen deshalb einige Möbel. Ein großer Esstisch aus hellem Holz, 1,80 Meter lang, in sehr gutem Zustand: 120 Euro. Dazu gibt es vier alte Stühle mit blauen Kissen, zusammen 60 Euro. Außerdem verkaufen wir ein kleines weißes Regal für 25 Euro. Es hat ein paar kleine Kratzer, aber es ist noch stabil. Das rote Sofa ist leider schon weg. Die Möbel stehen im dritten Stock, und es gibt keinen Aufzug. Sie müssen also alles selbst nach unten tragen und mit einem eigenen Auto abholen. Wir liefern nicht. Sie können die Möbel am Samstag zwischen 10 und 14 Uhr ansehen. Bitte schreiben Sie vorher eine kurze Nachricht. Familie Okafor',
      items: [
        { typ: 'rf', aussage: 'Der Esstisch ist aus dunklem Holz.', loesung: false },
        {
          typ: 'mc',
          frage: 'Was kostet das weiße Regal?',
          optionen: ['60 Euro', '25 Euro', '120 Euro'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Das rote Sofa kann man nicht mehr kaufen.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wie kommen die Möbel zum Käufer?',
          optionen: ['Der Käufer holt sie mit dem eigenen Auto ab.', 'Familie Okafor liefert sie.', 'Man bringt sie mit dem Aufzug nach unten.'],
          loesung: 0,
        },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Hör die Durchsage im Kaufhaus. Löse dann die vier Aufgaben.',
      audio: {
        transcript: 'Liebe Kundinnen und Kunden, herzlich willkommen im Kaufhaus am Markt! Heute haben wir tolle Angebote für Sie. In der ersten Etage finden Sie warme Winterjacken für Damen und Herren. Die blauen Jacken kosten heute nicht neunundachtzig, sondern nur neunundfünfzig Euro. Im Erdgeschoss gibt es bequeme Schuhe aus weichem Leder und bunte Schals zum halben Preis. Für Kinder haben wir einen kleinen roten Rucksack mit einer praktischen Trinkflasche im Angebot. Und haben Sie Hunger? In unserem neuen Restaurant in der dritten Etage bekommen Sie heute eine heiße Suppe und frisches Brot für vier Euro fünfzig. Bitte beachten Sie, dass wir heute schon um achtzehn Uhr schließen. Wir wünschen Ihnen einen schönen Einkauf!',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Was kosten die blauen Jacken heute?',
          optionen: ['89 Euro', '59 Euro', '50 Euro'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Die bequemen Schuhe gibt es im Erdgeschoss.', loesung: true },
        {
          typ: 'mc',
          frage: 'Was bekommt man im Restaurant für 4,50 Euro?',
          optionen: ['eine Suppe mit Brot', 'einen Kaffee mit Kuchen', 'ein Mittagessen mit Getränk'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Das Kaufhaus ist heute bis 20 Uhr geöffnet.', loesung: false },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'formular',
      titel: 'Schreiben',
      anweisung: 'Lies die Nachricht an das Fundbüro. Ergänze dann das Formular.',
      quelle: 'Guten Tag, mein Name ist Tomasz Nowak. Ich habe gestern Abend im Bus 42 meinen Rucksack verloren. Es ist ein kleiner grüner Rucksack mit einem schwarzen Reißverschluss. Darin sind eine blaue Jacke und ein altes Handy. Bitte rufen Sie mich an, wenn Sie ihn finden!',
      felder: [
        { id: 'name', label: 'Name', erwartet: ['Tomasz Nowak', 'Nowak'] },
        { id: 'gegenstand', label: 'Verlorener Gegenstand', erwartet: ['Rucksack', 'ein Rucksack', 'ein kleiner grüner Rucksack', 'kleiner grüner Rucksack', 'grüner Rucksack'] },
        { id: 'farbe', label: 'Rucksack — Farbe', erwartet: ['grün'] },
        { id: 'ort', label: 'Wo verloren?', erwartet: ['im Bus 42', 'Bus 42', 'im Bus', 'Bus Nummer 42'] },
        { id: 'jacke', label: 'Jacke — Farbe', erwartet: ['blau'] },
      ],
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Beschreib eine Person. Sprich ungefähr 75 Sekunden.',
      aufgabe: 'Beschreib eine Person aus deiner Familie oder einen guten Freund.',
      punkte: [
        'Wie sieht die Person aus? (Haare, Augen, Größe)',
        'Welche Kleidung trägt sie gern?',
        'Wie ist ihr Charakter? Gib ein Beispiel.',
      ],
      redemittel: ['Sie hat lange / kurze … Haare.', 'Er trägt oft einen … Pullover.', 'Sie ist ein sehr … Mensch.'],
      maxSekunden: 75,
      beispielLoesung: 'Ich beschreibe meine Schwester Carmen. Sie ist 35 Jahre alt und ziemlich groß. Sie hat lange schwarze Haare und dunkle Augen. Carmen trägt gern bequeme Kleidung: meistens eine blaue Jeans und einen weiten Pullover. Im Winter hat sie immer ihren alten roten Mantel an. Sie liebt diesen Mantel. Carmen ist ein sehr freundlicher und lustiger Mensch. Sie hat immer eine gute Idee und hilft allen. Letztes Jahr hatte ich zum Beispiel ein großes Problem mit meiner Wohnung, und sie hat mir sofort ein freies Zimmer bei sich angeboten. Sie ist wirklich eine tolle Schwester.',
    },
  ],
}
