// Übungsheft B1 — Lektion 12: Relativsätze
export default {
  lektion: 12,
  titel: 'Übungsheft — Relativsätze',
  teile: [
    {
      typ: 'grammatik',
      titel: 'Grammatik',
      anweisung: 'Welches Relativpronomen passt? Frag dich: Welches Nomen? Welche Rolle im Nebensatz?',
      items: [
        { typ: 'mc', frage: 'Das ist der Lehrer, ___ sehr gut erklärt.', optionen: ['den', 'der', 'dem'], loesung: 1 },
        { typ: 'mc', frage: 'Wie heißt der Film, ___ du mir empfohlen hast?', optionen: ['der', 'dem', 'den'], loesung: 2 },
        { typ: 'mc', frage: 'Das sind die Nachbarn, ___ ich oft beim Einkaufen helfe.', optionen: ['denen', 'die', 'den'], loesung: 0 },
        {
          typ: 'luecke',
          text: 'Die Frau, {1} neben mir wohnt, heißt Frau Brandt. Die Blumen, {2} sie im Garten hat, sind wunderschön. Ihr Hund, {3} ich manchmal Futter gebe, ist sehr lieb.',
          bank: ['die', 'der', 'dem', 'den'],
          loesungen: { 1: 'die', 2: 'die', 3: 'dem' },
        },
        {
          typ: 'luecke',
          text: 'Das ist das Café, {1} wir uns zum ersten Mal getroffen haben. Der Kellner, {2} dort arbeitet, kennt uns schon. Das Buch, {3} ich dort gelesen habe, war spannend.',
          bank: ['wo', 'der', 'das', 'dem', 'den'],
          loesungen: { 1: 'wo', 2: 'der', 3: 'das' },
        },
        {
          typ: 'zuordnen',
          links: ['der Mann, ___ ich jeden Tag sehe', 'die Kollegin, ___ ich helfe', 'das Kind, ___ dort spielt', 'die Leute, ___ ich schreibe', 'die Stadt, ___ ich wohne'],
          rechts: ['den', 'der', 'das', 'denen', 'wo'],
          loesung: {
            'der Mann, ___ ich jeden Tag sehe': 'den',
            'die Kollegin, ___ ich helfe': 'der',
            'das Kind, ___ dort spielt': 'das',
            'die Leute, ___ ich schreibe': 'denen',
            'die Stadt, ___ ich wohne': 'wo',
          },
        },
        { typ: 'satzbau', woerter: ['ist', 'der', 'Chef', 'dort', 'Mann', 'steht', 'mein', 'Der'], loesung: 'Der Mann, der dort steht, ist mein Chef.', alt: ['Der Chef, der dort steht, ist mein Mann.'] },
        {
          typ: 'korrektur',
          optionen: ['Das ist die Stadt, in der ich geboren bin.', 'Das ist die Stadt, in der ich bin geboren.'],
          loesung: 0,
          warum: 'El relativo es una subordinada: el verbo conjugado va **al final** (*geboren **bin***), no en segunda posición.',
        },
        {
          typ: 'korrektur',
          optionen: ['Der Film, der wir gesehen haben, war super.', 'Der Film, den wir gesehen haben, war super.'],
          loesung: 1,
          warum: 'En español «que» no cambia. En alemán el pronombre sigue su **función**: *wir* es el sujeto, el film es objeto → **Akkusativ: den**.',
        },
        {
          typ: 'korrektur',
          optionen: ['Ich habe einen Kuchen gebacken, der sehr gut schmeckt.', 'Ich habe einen Kuchen gebacken der sehr gut schmeckt.'],
          loesung: 0,
          warum: 'Antes del relativo la **coma es obligatoria** en alemán, aunque en español a menudo no se ponga.',
        },
      ],
    },
    {
      typ: 'lesen',
      titel: 'Lesen',
      anweisung: 'Lies die Zeitungsnotiz. Löse dann die vier Aufgaben.',
      textTitel: 'Neues Leben im alten Bahnhof',
      text: 'Das Café „Gleis 3“, das zwei Jahre lang geschlossen war, öffnet am 1. Mai wieder. Die neuen Besitzer sind Sofia und Karim Haddad, die vorher ein kleines Restaurant in Kassel hatten. Sie haben das alte Gebäude, das der Stadt gehört, zusammen mit Freunden renoviert. Im Café gibt es Kuchen, den Sofia selbst backt, und Kaffee aus einer kleinen Rösterei in der Region. Einmal im Monat organisieren die beiden einen Abend für Menschen, die neu in der Stadt sind. Dort können sie andere Leute kennenlernen, denen es genauso geht. Karim sagt: „Wir wollen einen Ort, wo alle willkommen sind.“ Das Café ist von Dienstag bis Sonntag von 9 bis 18 Uhr geöffnet. Montags bleibt es geschlossen.',
      items: [
        { typ: 'rf', aussage: 'Das Café war zwei Jahre lang geschlossen.', loesung: true },
        {
          typ: 'mc',
          frage: 'Wer backt den Kuchen im Café?',
          optionen: ['Karim', 'Sofia', 'Freunde von Sofia und Karim'],
          loesung: 1,
        },
        {
          typ: 'mc',
          frage: 'Für wen ist der Abend einmal im Monat?',
          optionen: ['für Menschen, die neu in der Stadt sind', 'für Freunde aus Kassel', 'für Leute, die Kaffee rösten'],
          loesung: 0,
        },
        { typ: 'rf', aussage: 'Am Montag kann man im Café frühstücken.', loesung: false },
      ],
    },
    {
      typ: 'hoeren',
      titel: 'Hören',
      anweisung: 'Du machst eine Stadtführung. Hör der Stadtführerin zu und löse die vier Aufgaben.',
      audio: {
        transcript: 'Herzlich willkommen zu unserer Führung durch die Altstadt! Ich heiße Martina und bin die Stadtführerin, die Sie heute begleitet. Wir stehen hier auf dem Marktplatz, wo früher jeden Samstag der Markt stattfand. Heute findet er nicht mehr samstags, sondern mittwochs statt. Das große Haus, das Sie links sehen, ist das alte Rathaus. Es ist über vierhundert Jahre alt. Der Turm, den Sie dahinter sehen, gehört zur Stadtkirche. Besucher, die gut zu Fuß sind, können später hinaufsteigen. Der Eintritt kostet zwei Euro. Danach gehen wir zu dem Brunnen, den die Kinder hier besonders lieben. Unsere Führung dauert ungefähr neunzig Minuten und endet in einem Café, wo Sie etwas trinken können. Haben Sie Fragen? Dann fragen Sie mich gern unterwegs.',
      },
      items: [
        {
          typ: 'mc',
          frage: 'Wann findet der Markt heute statt?',
          optionen: ['am Samstag', 'am Mittwoch', 'jeden Tag'],
          loesung: 1,
        },
        { typ: 'rf', aussage: 'Das alte Rathaus ist mehr als 400 Jahre alt.', loesung: true },
        { typ: 'rf', aussage: 'Für den Turm muss man nichts bezahlen.', loesung: false },
        {
          typ: 'mc',
          frage: 'Wo endet die Führung?',
          optionen: ['auf dem Marktplatz', 'am Brunnen', 'in einem Café'],
          loesung: 2,
        },
      ],
    },
    {
      typ: 'schreiben',
      variante: 'formular',
      titel: 'Schreiben',
      anweisung: 'Lies die Nachricht. Ergänze dann das Formular für die Tandembörse.',
      quelle: 'Hallo! Ich heiße Valentina Rossi und komme aus Italien. Meine Muttersprache ist Italienisch. Ich suche eine Tandempartnerin, die Deutsch als Muttersprache spricht und Italienisch lernen möchte. Am liebsten treffe ich mich am Mittwochabend in einem ruhigen Café. Ich wohne in Bremen-Neustadt, wo es viele schöne Cafés gibt.',
      felder: [
        { id: 'name', label: 'Name', erwartet: ['Valentina Rossi', 'Rossi'] },
        { id: 'muttersprache', label: 'Muttersprache', erwartet: ['Italienisch'] },
        { id: 'lernsprache', label: 'Ich möchte lernen', erwartet: ['Deutsch'] },
        { id: 'termin', label: 'Treffen — wann?', erwartet: ['Mittwochabend', 'am Mittwochabend', 'mittwochabends', 'Mittwoch', 'mittwochs'] },
        { id: 'wohnort', label: 'Wohnort', erwartet: ['Bremen-Neustadt', 'Bremen Neustadt', 'Bremen'] },
      ],
    },
    {
      typ: 'sprechen',
      titel: 'Sprechen',
      anweisung: 'Erzähl, was dir wichtig ist. Sprich ungefähr 75 Sekunden.',
      aufgabe: 'Stell einen Menschen, einen Ort und einen Gegenstand vor, die dir wichtig sind. Benutze Relativsätze.',
      punkte: [
        'ein Mensch, der dir oft hilft',
        'ein Ort, wo du dich wohlfühlst',
        'ein Gegenstand, den du jeden Tag benutzt',
      ],
      redemittel: ['… ist ein Mensch, der …', '… ist ein Ort, wo …', '… ist etwas, das ich …'],
      maxSekunden: 75,
      beispielLoesung: 'Ein Mensch, der mir sehr wichtig ist, ist mein Freund Diego. Er ist jemand, der immer Zeit für mich hat. Wenn ich ein Problem habe, ist er der Erste, den ich anrufe. Ein Ort, wo ich mich wohlfühle, ist der kleine Park in meinem Viertel. Dort gibt es eine Bank, die unter einem alten Baum steht. Da sitze ich oft und lese. Und der Gegenstand, den ich jeden Tag benutze, ist mein Fahrrad. Es ist ein altes Rad, das mir mein Onkel geschenkt hat. Ich fahre damit zur Arbeit und zum Deutschkurs.',
    },
  ],
}
